package com.xym.bossed.db.mybatis.danwei;

import java.io.Serializable;

public class DanWei implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = 2039400469343616262L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sm_danwlc.lc_mc
     *
     * @mbggenerated Mon Apr 21 17:52:08 CST 2014
     */
    private String lcMc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sm_danwlc.reco_no
     *
     * @mbggenerated Mon Apr 21 17:52:08 CST 2014
     */
    private Integer recoNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_danwlc.lc_mc
     *
     * @return the value of sm_danwlc.lc_mc
     *
     * @mbggenerated Mon Apr 21 17:52:08 CST 2014
     */
    public String getLcMc() {
        return lcMc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_danwlc.lc_mc
     *
     * @param lcMc the value for sm_danwlc.lc_mc
     *
     * @mbggenerated Mon Apr 21 17:52:08 CST 2014
     */
    public void setLcMc(String lcMc) {
        this.lcMc = lcMc == null ? null : lcMc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_danwlc.reco_no
     *
     * @return the value of sm_danwlc.reco_no
     *
     * @mbggenerated Mon Apr 21 17:52:08 CST 2014
     */
    public Integer getRecoNo() {
        return recoNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_danwlc.reco_no
     *
     * @param recoNo the value for sm_danwlc.reco_no
     *
     * @mbggenerated Mon Apr 21 17:52:08 CST 2014
     */
    public void setRecoNo(Integer recoNo) {
        this.recoNo = recoNo;
    }
}