package com.xym.bossed.db.mybatis.employee;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class EmployeeExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table gongzry
     *
     * @mbggenerated Tue Apr 08 20:09:00 CST 2014
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table gongzry
     *
     * @mbggenerated Tue Apr 08 20:09:00 CST 2014
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table gongzry
     *
     * @mbggenerated Tue Apr 08 20:09:00 CST 2014
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gongzry
     *
     * @mbggenerated Tue Apr 08 20:09:00 CST 2014
     */
    public EmployeeExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gongzry
     *
     * @mbggenerated Tue Apr 08 20:09:00 CST 2014
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gongzry
     *
     * @mbggenerated Tue Apr 08 20:09:00 CST 2014
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gongzry
     *
     * @mbggenerated Tue Apr 08 20:09:00 CST 2014
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gongzry
     *
     * @mbggenerated Tue Apr 08 20:09:00 CST 2014
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gongzry
     *
     * @mbggenerated Tue Apr 08 20:09:00 CST 2014
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gongzry
     *
     * @mbggenerated Tue Apr 08 20:09:00 CST 2014
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gongzry
     *
     * @mbggenerated Tue Apr 08 20:09:00 CST 2014
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gongzry
     *
     * @mbggenerated Tue Apr 08 20:09:00 CST 2014
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gongzry
     *
     * @mbggenerated Tue Apr 08 20:09:00 CST 2014
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gongzry
     *
     * @mbggenerated Tue Apr 08 20:09:00 CST 2014
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table gongzry
     *
     * @mbggenerated Tue Apr 08 20:09:00 CST 2014
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andRenyDmIsNull() {
            addCriterion("reny_dm is null");
            return (Criteria) this;
        }

        public Criteria andRenyDmIsNotNull() {
            addCriterion("reny_dm is not null");
            return (Criteria) this;
        }

        public Criteria andRenyDmEqualTo(String value) {
            addCriterion("reny_dm =", value, "renyDm");
            return (Criteria) this;
        }

        public Criteria andRenyDmNotEqualTo(String value) {
            addCriterion("reny_dm <>", value, "renyDm");
            return (Criteria) this;
        }

        public Criteria andRenyDmGreaterThan(String value) {
            addCriterion("reny_dm >", value, "renyDm");
            return (Criteria) this;
        }

        public Criteria andRenyDmGreaterThanOrEqualTo(String value) {
            addCriterion("reny_dm >=", value, "renyDm");
            return (Criteria) this;
        }

        public Criteria andRenyDmLessThan(String value) {
            addCriterion("reny_dm <", value, "renyDm");
            return (Criteria) this;
        }

        public Criteria andRenyDmLessThanOrEqualTo(String value) {
            addCriterion("reny_dm <=", value, "renyDm");
            return (Criteria) this;
        }

        public Criteria andRenyDmLike(String value) {
            addCriterion("reny_dm like", value, "renyDm");
            return (Criteria) this;
        }

        public Criteria andRenyDmNotLike(String value) {
            addCriterion("reny_dm not like", value, "renyDm");
            return (Criteria) this;
        }

        public Criteria andRenyDmIn(List<String> values) {
            addCriterion("reny_dm in", values, "renyDm");
            return (Criteria) this;
        }

        public Criteria andRenyDmNotIn(List<String> values) {
            addCriterion("reny_dm not in", values, "renyDm");
            return (Criteria) this;
        }

        public Criteria andRenyDmBetween(String value1, String value2) {
            addCriterion("reny_dm between", value1, value2, "renyDm");
            return (Criteria) this;
        }

        public Criteria andRenyDmNotBetween(String value1, String value2) {
            addCriterion("reny_dm not between", value1, value2, "renyDm");
            return (Criteria) this;
        }

        public Criteria andDanwDmIsNull() {
            addCriterion("danw_dm is null");
            return (Criteria) this;
        }

        public Criteria andDanwDmIsNotNull() {
            addCriterion("danw_dm is not null");
            return (Criteria) this;
        }

        public Criteria andDanwDmEqualTo(String value) {
            addCriterion("danw_dm =", value, "danwDm");
            return (Criteria) this;
        }

        public Criteria andDanwDmNotEqualTo(String value) {
            addCriterion("danw_dm <>", value, "danwDm");
            return (Criteria) this;
        }

        public Criteria andDanwDmGreaterThan(String value) {
            addCriterion("danw_dm >", value, "danwDm");
            return (Criteria) this;
        }

        public Criteria andDanwDmGreaterThanOrEqualTo(String value) {
            addCriterion("danw_dm >=", value, "danwDm");
            return (Criteria) this;
        }

        public Criteria andDanwDmLessThan(String value) {
            addCriterion("danw_dm <", value, "danwDm");
            return (Criteria) this;
        }

        public Criteria andDanwDmLessThanOrEqualTo(String value) {
            addCriterion("danw_dm <=", value, "danwDm");
            return (Criteria) this;
        }

        public Criteria andDanwDmLike(String value) {
            addCriterion("danw_dm like", value, "danwDm");
            return (Criteria) this;
        }

        public Criteria andDanwDmNotLike(String value) {
            addCriterion("danw_dm not like", value, "danwDm");
            return (Criteria) this;
        }

        public Criteria andDanwDmIn(List<String> values) {
            addCriterion("danw_dm in", values, "danwDm");
            return (Criteria) this;
        }

        public Criteria andDanwDmNotIn(List<String> values) {
            addCriterion("danw_dm not in", values, "danwDm");
            return (Criteria) this;
        }

        public Criteria andDanwDmBetween(String value1, String value2) {
            addCriterion("danw_dm between", value1, value2, "danwDm");
            return (Criteria) this;
        }

        public Criteria andDanwDmNotBetween(String value1, String value2) {
            addCriterion("danw_dm not between", value1, value2, "danwDm");
            return (Criteria) this;
        }

        public Criteria andDeptMcIsNull() {
            addCriterion("dept_mc is null");
            return (Criteria) this;
        }

        public Criteria andDeptMcIsNotNull() {
            addCriterion("dept_mc is not null");
            return (Criteria) this;
        }

        public Criteria andDeptMcEqualTo(String value) {
            addCriterion("dept_mc =", value, "deptMc");
            return (Criteria) this;
        }

        public Criteria andDeptMcNotEqualTo(String value) {
            addCriterion("dept_mc <>", value, "deptMc");
            return (Criteria) this;
        }

        public Criteria andDeptMcGreaterThan(String value) {
            addCriterion("dept_mc >", value, "deptMc");
            return (Criteria) this;
        }

        public Criteria andDeptMcGreaterThanOrEqualTo(String value) {
            addCriterion("dept_mc >=", value, "deptMc");
            return (Criteria) this;
        }

        public Criteria andDeptMcLessThan(String value) {
            addCriterion("dept_mc <", value, "deptMc");
            return (Criteria) this;
        }

        public Criteria andDeptMcLessThanOrEqualTo(String value) {
            addCriterion("dept_mc <=", value, "deptMc");
            return (Criteria) this;
        }

        public Criteria andDeptMcLike(String value) {
            addCriterion("dept_mc like", value, "deptMc");
            return (Criteria) this;
        }

        public Criteria andDeptMcNotLike(String value) {
            addCriterion("dept_mc not like", value, "deptMc");
            return (Criteria) this;
        }

        public Criteria andDeptMcIn(List<String> values) {
            addCriterion("dept_mc in", values, "deptMc");
            return (Criteria) this;
        }

        public Criteria andDeptMcNotIn(List<String> values) {
            addCriterion("dept_mc not in", values, "deptMc");
            return (Criteria) this;
        }

        public Criteria andDeptMcBetween(String value1, String value2) {
            addCriterion("dept_mc between", value1, value2, "deptMc");
            return (Criteria) this;
        }

        public Criteria andDeptMcNotBetween(String value1, String value2) {
            addCriterion("dept_mc not between", value1, value2, "deptMc");
            return (Criteria) this;
        }

        public Criteria andRenyXmIsNull() {
            addCriterion("reny_xm is null");
            return (Criteria) this;
        }

        public Criteria andRenyXmIsNotNull() {
            addCriterion("reny_xm is not null");
            return (Criteria) this;
        }

        public Criteria andRenyXmEqualTo(String value) {
            addCriterion("reny_xm =", value, "renyXm");
            return (Criteria) this;
        }

        public Criteria andRenyXmNotEqualTo(String value) {
            addCriterion("reny_xm <>", value, "renyXm");
            return (Criteria) this;
        }

        public Criteria andRenyXmGreaterThan(String value) {
            addCriterion("reny_xm >", value, "renyXm");
            return (Criteria) this;
        }

        public Criteria andRenyXmGreaterThanOrEqualTo(String value) {
            addCriterion("reny_xm >=", value, "renyXm");
            return (Criteria) this;
        }

        public Criteria andRenyXmLessThan(String value) {
            addCriterion("reny_xm <", value, "renyXm");
            return (Criteria) this;
        }

        public Criteria andRenyXmLessThanOrEqualTo(String value) {
            addCriterion("reny_xm <=", value, "renyXm");
            return (Criteria) this;
        }

        public Criteria andRenyXmLike(String value) {
            addCriterion("reny_xm like", value, "renyXm");
            return (Criteria) this;
        }

        public Criteria andRenyXmNotLike(String value) {
            addCriterion("reny_xm not like", value, "renyXm");
            return (Criteria) this;
        }

        public Criteria andRenyXmIn(List<String> values) {
            addCriterion("reny_xm in", values, "renyXm");
            return (Criteria) this;
        }

        public Criteria andRenyXmNotIn(List<String> values) {
            addCriterion("reny_xm not in", values, "renyXm");
            return (Criteria) this;
        }

        public Criteria andRenyXmBetween(String value1, String value2) {
            addCriterion("reny_xm between", value1, value2, "renyXm");
            return (Criteria) this;
        }

        public Criteria andRenyXmNotBetween(String value1, String value2) {
            addCriterion("reny_xm not between", value1, value2, "renyXm");
            return (Criteria) this;
        }

        public Criteria andRenyLpIsNull() {
            addCriterion("reny_lp is null");
            return (Criteria) this;
        }

        public Criteria andRenyLpIsNotNull() {
            addCriterion("reny_lp is not null");
            return (Criteria) this;
        }

        public Criteria andRenyLpEqualTo(String value) {
            addCriterion("reny_lp =", value, "renyLp");
            return (Criteria) this;
        }

        public Criteria andRenyLpNotEqualTo(String value) {
            addCriterion("reny_lp <>", value, "renyLp");
            return (Criteria) this;
        }

        public Criteria andRenyLpGreaterThan(String value) {
            addCriterion("reny_lp >", value, "renyLp");
            return (Criteria) this;
        }

        public Criteria andRenyLpGreaterThanOrEqualTo(String value) {
            addCriterion("reny_lp >=", value, "renyLp");
            return (Criteria) this;
        }

        public Criteria andRenyLpLessThan(String value) {
            addCriterion("reny_lp <", value, "renyLp");
            return (Criteria) this;
        }

        public Criteria andRenyLpLessThanOrEqualTo(String value) {
            addCriterion("reny_lp <=", value, "renyLp");
            return (Criteria) this;
        }

        public Criteria andRenyLpLike(String value) {
            addCriterion("reny_lp like", value, "renyLp");
            return (Criteria) this;
        }

        public Criteria andRenyLpNotLike(String value) {
            addCriterion("reny_lp not like", value, "renyLp");
            return (Criteria) this;
        }

        public Criteria andRenyLpIn(List<String> values) {
            addCriterion("reny_lp in", values, "renyLp");
            return (Criteria) this;
        }

        public Criteria andRenyLpNotIn(List<String> values) {
            addCriterion("reny_lp not in", values, "renyLp");
            return (Criteria) this;
        }

        public Criteria andRenyLpBetween(String value1, String value2) {
            addCriterion("reny_lp between", value1, value2, "renyLp");
            return (Criteria) this;
        }

        public Criteria andRenyLpNotBetween(String value1, String value2) {
            addCriterion("reny_lp not between", value1, value2, "renyLp");
            return (Criteria) this;
        }

        public Criteria andRenyXbIsNull() {
            addCriterion("reny_xb is null");
            return (Criteria) this;
        }

        public Criteria andRenyXbIsNotNull() {
            addCriterion("reny_xb is not null");
            return (Criteria) this;
        }

        public Criteria andRenyXbEqualTo(String value) {
            addCriterion("reny_xb =", value, "renyXb");
            return (Criteria) this;
        }

        public Criteria andRenyXbNotEqualTo(String value) {
            addCriterion("reny_xb <>", value, "renyXb");
            return (Criteria) this;
        }

        public Criteria andRenyXbGreaterThan(String value) {
            addCriterion("reny_xb >", value, "renyXb");
            return (Criteria) this;
        }

        public Criteria andRenyXbGreaterThanOrEqualTo(String value) {
            addCriterion("reny_xb >=", value, "renyXb");
            return (Criteria) this;
        }

        public Criteria andRenyXbLessThan(String value) {
            addCriterion("reny_xb <", value, "renyXb");
            return (Criteria) this;
        }

        public Criteria andRenyXbLessThanOrEqualTo(String value) {
            addCriterion("reny_xb <=", value, "renyXb");
            return (Criteria) this;
        }

        public Criteria andRenyXbLike(String value) {
            addCriterion("reny_xb like", value, "renyXb");
            return (Criteria) this;
        }

        public Criteria andRenyXbNotLike(String value) {
            addCriterion("reny_xb not like", value, "renyXb");
            return (Criteria) this;
        }

        public Criteria andRenyXbIn(List<String> values) {
            addCriterion("reny_xb in", values, "renyXb");
            return (Criteria) this;
        }

        public Criteria andRenyXbNotIn(List<String> values) {
            addCriterion("reny_xb not in", values, "renyXb");
            return (Criteria) this;
        }

        public Criteria andRenyXbBetween(String value1, String value2) {
            addCriterion("reny_xb between", value1, value2, "renyXb");
            return (Criteria) this;
        }

        public Criteria andRenyXbNotBetween(String value1, String value2) {
            addCriterion("reny_xb not between", value1, value2, "renyXb");
            return (Criteria) this;
        }

        public Criteria andRenyHbIsNull() {
            addCriterion("reny_hb is null");
            return (Criteria) this;
        }

        public Criteria andRenyHbIsNotNull() {
            addCriterion("reny_hb is not null");
            return (Criteria) this;
        }

        public Criteria andRenyHbEqualTo(String value) {
            addCriterion("reny_hb =", value, "renyHb");
            return (Criteria) this;
        }

        public Criteria andRenyHbNotEqualTo(String value) {
            addCriterion("reny_hb <>", value, "renyHb");
            return (Criteria) this;
        }

        public Criteria andRenyHbGreaterThan(String value) {
            addCriterion("reny_hb >", value, "renyHb");
            return (Criteria) this;
        }

        public Criteria andRenyHbGreaterThanOrEqualTo(String value) {
            addCriterion("reny_hb >=", value, "renyHb");
            return (Criteria) this;
        }

        public Criteria andRenyHbLessThan(String value) {
            addCriterion("reny_hb <", value, "renyHb");
            return (Criteria) this;
        }

        public Criteria andRenyHbLessThanOrEqualTo(String value) {
            addCriterion("reny_hb <=", value, "renyHb");
            return (Criteria) this;
        }

        public Criteria andRenyHbLike(String value) {
            addCriterion("reny_hb like", value, "renyHb");
            return (Criteria) this;
        }

        public Criteria andRenyHbNotLike(String value) {
            addCriterion("reny_hb not like", value, "renyHb");
            return (Criteria) this;
        }

        public Criteria andRenyHbIn(List<String> values) {
            addCriterion("reny_hb in", values, "renyHb");
            return (Criteria) this;
        }

        public Criteria andRenyHbNotIn(List<String> values) {
            addCriterion("reny_hb not in", values, "renyHb");
            return (Criteria) this;
        }

        public Criteria andRenyHbBetween(String value1, String value2) {
            addCriterion("reny_hb between", value1, value2, "renyHb");
            return (Criteria) this;
        }

        public Criteria andRenyHbNotBetween(String value1, String value2) {
            addCriterion("reny_hb not between", value1, value2, "renyHb");
            return (Criteria) this;
        }

        public Criteria andRenyGzIsNull() {
            addCriterion("reny_gz is null");
            return (Criteria) this;
        }

        public Criteria andRenyGzIsNotNull() {
            addCriterion("reny_gz is not null");
            return (Criteria) this;
        }

        public Criteria andRenyGzEqualTo(BigDecimal value) {
            addCriterion("reny_gz =", value, "renyGz");
            return (Criteria) this;
        }

        public Criteria andRenyGzNotEqualTo(BigDecimal value) {
            addCriterion("reny_gz <>", value, "renyGz");
            return (Criteria) this;
        }

        public Criteria andRenyGzGreaterThan(BigDecimal value) {
            addCriterion("reny_gz >", value, "renyGz");
            return (Criteria) this;
        }

        public Criteria andRenyGzGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("reny_gz >=", value, "renyGz");
            return (Criteria) this;
        }

        public Criteria andRenyGzLessThan(BigDecimal value) {
            addCriterion("reny_gz <", value, "renyGz");
            return (Criteria) this;
        }

        public Criteria andRenyGzLessThanOrEqualTo(BigDecimal value) {
            addCriterion("reny_gz <=", value, "renyGz");
            return (Criteria) this;
        }

        public Criteria andRenyGzIn(List<BigDecimal> values) {
            addCriterion("reny_gz in", values, "renyGz");
            return (Criteria) this;
        }

        public Criteria andRenyGzNotIn(List<BigDecimal> values) {
            addCriterion("reny_gz not in", values, "renyGz");
            return (Criteria) this;
        }

        public Criteria andRenyGzBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("reny_gz between", value1, value2, "renyGz");
            return (Criteria) this;
        }

        public Criteria andRenyGzNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("reny_gz not between", value1, value2, "renyGz");
            return (Criteria) this;
        }

        public Criteria andRenyZwIsNull() {
            addCriterion("reny_zw is null");
            return (Criteria) this;
        }

        public Criteria andRenyZwIsNotNull() {
            addCriterion("reny_zw is not null");
            return (Criteria) this;
        }

        public Criteria andRenyZwEqualTo(String value) {
            addCriterion("reny_zw =", value, "renyZw");
            return (Criteria) this;
        }

        public Criteria andRenyZwNotEqualTo(String value) {
            addCriterion("reny_zw <>", value, "renyZw");
            return (Criteria) this;
        }

        public Criteria andRenyZwGreaterThan(String value) {
            addCriterion("reny_zw >", value, "renyZw");
            return (Criteria) this;
        }

        public Criteria andRenyZwGreaterThanOrEqualTo(String value) {
            addCriterion("reny_zw >=", value, "renyZw");
            return (Criteria) this;
        }

        public Criteria andRenyZwLessThan(String value) {
            addCriterion("reny_zw <", value, "renyZw");
            return (Criteria) this;
        }

        public Criteria andRenyZwLessThanOrEqualTo(String value) {
            addCriterion("reny_zw <=", value, "renyZw");
            return (Criteria) this;
        }

        public Criteria andRenyZwLike(String value) {
            addCriterion("reny_zw like", value, "renyZw");
            return (Criteria) this;
        }

        public Criteria andRenyZwNotLike(String value) {
            addCriterion("reny_zw not like", value, "renyZw");
            return (Criteria) this;
        }

        public Criteria andRenyZwIn(List<String> values) {
            addCriterion("reny_zw in", values, "renyZw");
            return (Criteria) this;
        }

        public Criteria andRenyZwNotIn(List<String> values) {
            addCriterion("reny_zw not in", values, "renyZw");
            return (Criteria) this;
        }

        public Criteria andRenyZwBetween(String value1, String value2) {
            addCriterion("reny_zw between", value1, value2, "renyZw");
            return (Criteria) this;
        }

        public Criteria andRenyZwNotBetween(String value1, String value2) {
            addCriterion("reny_zw not between", value1, value2, "renyZw");
            return (Criteria) this;
        }

        public Criteria andRenyLyIsNull() {
            addCriterion("reny_ly is null");
            return (Criteria) this;
        }

        public Criteria andRenyLyIsNotNull() {
            addCriterion("reny_ly is not null");
            return (Criteria) this;
        }

        public Criteria andRenyLyEqualTo(String value) {
            addCriterion("reny_ly =", value, "renyLy");
            return (Criteria) this;
        }

        public Criteria andRenyLyNotEqualTo(String value) {
            addCriterion("reny_ly <>", value, "renyLy");
            return (Criteria) this;
        }

        public Criteria andRenyLyGreaterThan(String value) {
            addCriterion("reny_ly >", value, "renyLy");
            return (Criteria) this;
        }

        public Criteria andRenyLyGreaterThanOrEqualTo(String value) {
            addCriterion("reny_ly >=", value, "renyLy");
            return (Criteria) this;
        }

        public Criteria andRenyLyLessThan(String value) {
            addCriterion("reny_ly <", value, "renyLy");
            return (Criteria) this;
        }

        public Criteria andRenyLyLessThanOrEqualTo(String value) {
            addCriterion("reny_ly <=", value, "renyLy");
            return (Criteria) this;
        }

        public Criteria andRenyLyLike(String value) {
            addCriterion("reny_ly like", value, "renyLy");
            return (Criteria) this;
        }

        public Criteria andRenyLyNotLike(String value) {
            addCriterion("reny_ly not like", value, "renyLy");
            return (Criteria) this;
        }

        public Criteria andRenyLyIn(List<String> values) {
            addCriterion("reny_ly in", values, "renyLy");
            return (Criteria) this;
        }

        public Criteria andRenyLyNotIn(List<String> values) {
            addCriterion("reny_ly not in", values, "renyLy");
            return (Criteria) this;
        }

        public Criteria andRenyLyBetween(String value1, String value2) {
            addCriterion("reny_ly between", value1, value2, "renyLy");
            return (Criteria) this;
        }

        public Criteria andRenyLyNotBetween(String value1, String value2) {
            addCriterion("reny_ly not between", value1, value2, "renyLy");
            return (Criteria) this;
        }

        public Criteria andRenyWhIsNull() {
            addCriterion("reny_wh is null");
            return (Criteria) this;
        }

        public Criteria andRenyWhIsNotNull() {
            addCriterion("reny_wh is not null");
            return (Criteria) this;
        }

        public Criteria andRenyWhEqualTo(String value) {
            addCriterion("reny_wh =", value, "renyWh");
            return (Criteria) this;
        }

        public Criteria andRenyWhNotEqualTo(String value) {
            addCriterion("reny_wh <>", value, "renyWh");
            return (Criteria) this;
        }

        public Criteria andRenyWhGreaterThan(String value) {
            addCriterion("reny_wh >", value, "renyWh");
            return (Criteria) this;
        }

        public Criteria andRenyWhGreaterThanOrEqualTo(String value) {
            addCriterion("reny_wh >=", value, "renyWh");
            return (Criteria) this;
        }

        public Criteria andRenyWhLessThan(String value) {
            addCriterion("reny_wh <", value, "renyWh");
            return (Criteria) this;
        }

        public Criteria andRenyWhLessThanOrEqualTo(String value) {
            addCriterion("reny_wh <=", value, "renyWh");
            return (Criteria) this;
        }

        public Criteria andRenyWhLike(String value) {
            addCriterion("reny_wh like", value, "renyWh");
            return (Criteria) this;
        }

        public Criteria andRenyWhNotLike(String value) {
            addCriterion("reny_wh not like", value, "renyWh");
            return (Criteria) this;
        }

        public Criteria andRenyWhIn(List<String> values) {
            addCriterion("reny_wh in", values, "renyWh");
            return (Criteria) this;
        }

        public Criteria andRenyWhNotIn(List<String> values) {
            addCriterion("reny_wh not in", values, "renyWh");
            return (Criteria) this;
        }

        public Criteria andRenyWhBetween(String value1, String value2) {
            addCriterion("reny_wh between", value1, value2, "renyWh");
            return (Criteria) this;
        }

        public Criteria andRenyWhNotBetween(String value1, String value2) {
            addCriterion("reny_wh not between", value1, value2, "renyWh");
            return (Criteria) this;
        }

        public Criteria andRenyCsIsNull() {
            addCriterion("reny_cs is null");
            return (Criteria) this;
        }

        public Criteria andRenyCsIsNotNull() {
            addCriterion("reny_cs is not null");
            return (Criteria) this;
        }

        public Criteria andRenyCsEqualTo(Date value) {
            addCriterion("reny_cs =", value, "renyCs");
            return (Criteria) this;
        }

        public Criteria andRenyCsNotEqualTo(Date value) {
            addCriterion("reny_cs <>", value, "renyCs");
            return (Criteria) this;
        }

        public Criteria andRenyCsGreaterThan(Date value) {
            addCriterion("reny_cs >", value, "renyCs");
            return (Criteria) this;
        }

        public Criteria andRenyCsGreaterThanOrEqualTo(Date value) {
            addCriterion("reny_cs >=", value, "renyCs");
            return (Criteria) this;
        }

        public Criteria andRenyCsLessThan(Date value) {
            addCriterion("reny_cs <", value, "renyCs");
            return (Criteria) this;
        }

        public Criteria andRenyCsLessThanOrEqualTo(Date value) {
            addCriterion("reny_cs <=", value, "renyCs");
            return (Criteria) this;
        }

        public Criteria andRenyCsIn(List<Date> values) {
            addCriterion("reny_cs in", values, "renyCs");
            return (Criteria) this;
        }

        public Criteria andRenyCsNotIn(List<Date> values) {
            addCriterion("reny_cs not in", values, "renyCs");
            return (Criteria) this;
        }

        public Criteria andRenyCsBetween(Date value1, Date value2) {
            addCriterion("reny_cs between", value1, value2, "renyCs");
            return (Criteria) this;
        }

        public Criteria andRenyCsNotBetween(Date value1, Date value2) {
            addCriterion("reny_cs not between", value1, value2, "renyCs");
            return (Criteria) this;
        }

        public Criteria andRenySjIsNull() {
            addCriterion("reny_sj is null");
            return (Criteria) this;
        }

        public Criteria andRenySjIsNotNull() {
            addCriterion("reny_sj is not null");
            return (Criteria) this;
        }

        public Criteria andRenySjEqualTo(Date value) {
            addCriterion("reny_sj =", value, "renySj");
            return (Criteria) this;
        }

        public Criteria andRenySjNotEqualTo(Date value) {
            addCriterion("reny_sj <>", value, "renySj");
            return (Criteria) this;
        }

        public Criteria andRenySjGreaterThan(Date value) {
            addCriterion("reny_sj >", value, "renySj");
            return (Criteria) this;
        }

        public Criteria andRenySjGreaterThanOrEqualTo(Date value) {
            addCriterion("reny_sj >=", value, "renySj");
            return (Criteria) this;
        }

        public Criteria andRenySjLessThan(Date value) {
            addCriterion("reny_sj <", value, "renySj");
            return (Criteria) this;
        }

        public Criteria andRenySjLessThanOrEqualTo(Date value) {
            addCriterion("reny_sj <=", value, "renySj");
            return (Criteria) this;
        }

        public Criteria andRenySjIn(List<Date> values) {
            addCriterion("reny_sj in", values, "renySj");
            return (Criteria) this;
        }

        public Criteria andRenySjNotIn(List<Date> values) {
            addCriterion("reny_sj not in", values, "renySj");
            return (Criteria) this;
        }

        public Criteria andRenySjBetween(Date value1, Date value2) {
            addCriterion("reny_sj between", value1, value2, "renySj");
            return (Criteria) this;
        }

        public Criteria andRenySjNotBetween(Date value1, Date value2) {
            addCriterion("reny_sj not between", value1, value2, "renySj");
            return (Criteria) this;
        }

        public Criteria andRenyGlIsNull() {
            addCriterion("reny_gl is null");
            return (Criteria) this;
        }

        public Criteria andRenyGlIsNotNull() {
            addCriterion("reny_gl is not null");
            return (Criteria) this;
        }

        public Criteria andRenyGlEqualTo(Short value) {
            addCriterion("reny_gl =", value, "renyGl");
            return (Criteria) this;
        }

        public Criteria andRenyGlNotEqualTo(Short value) {
            addCriterion("reny_gl <>", value, "renyGl");
            return (Criteria) this;
        }

        public Criteria andRenyGlGreaterThan(Short value) {
            addCriterion("reny_gl >", value, "renyGl");
            return (Criteria) this;
        }

        public Criteria andRenyGlGreaterThanOrEqualTo(Short value) {
            addCriterion("reny_gl >=", value, "renyGl");
            return (Criteria) this;
        }

        public Criteria andRenyGlLessThan(Short value) {
            addCriterion("reny_gl <", value, "renyGl");
            return (Criteria) this;
        }

        public Criteria andRenyGlLessThanOrEqualTo(Short value) {
            addCriterion("reny_gl <=", value, "renyGl");
            return (Criteria) this;
        }

        public Criteria andRenyGlIn(List<Short> values) {
            addCriterion("reny_gl in", values, "renyGl");
            return (Criteria) this;
        }

        public Criteria andRenyGlNotIn(List<Short> values) {
            addCriterion("reny_gl not in", values, "renyGl");
            return (Criteria) this;
        }

        public Criteria andRenyGlBetween(Short value1, Short value2) {
            addCriterion("reny_gl between", value1, value2, "renyGl");
            return (Criteria) this;
        }

        public Criteria andRenyGlNotBetween(Short value1, Short value2) {
            addCriterion("reny_gl not between", value1, value2, "renyGl");
            return (Criteria) this;
        }

        public Criteria andRenyJgIsNull() {
            addCriterion("reny_jg is null");
            return (Criteria) this;
        }

        public Criteria andRenyJgIsNotNull() {
            addCriterion("reny_jg is not null");
            return (Criteria) this;
        }

        public Criteria andRenyJgEqualTo(String value) {
            addCriterion("reny_jg =", value, "renyJg");
            return (Criteria) this;
        }

        public Criteria andRenyJgNotEqualTo(String value) {
            addCriterion("reny_jg <>", value, "renyJg");
            return (Criteria) this;
        }

        public Criteria andRenyJgGreaterThan(String value) {
            addCriterion("reny_jg >", value, "renyJg");
            return (Criteria) this;
        }

        public Criteria andRenyJgGreaterThanOrEqualTo(String value) {
            addCriterion("reny_jg >=", value, "renyJg");
            return (Criteria) this;
        }

        public Criteria andRenyJgLessThan(String value) {
            addCriterion("reny_jg <", value, "renyJg");
            return (Criteria) this;
        }

        public Criteria andRenyJgLessThanOrEqualTo(String value) {
            addCriterion("reny_jg <=", value, "renyJg");
            return (Criteria) this;
        }

        public Criteria andRenyJgLike(String value) {
            addCriterion("reny_jg like", value, "renyJg");
            return (Criteria) this;
        }

        public Criteria andRenyJgNotLike(String value) {
            addCriterion("reny_jg not like", value, "renyJg");
            return (Criteria) this;
        }

        public Criteria andRenyJgIn(List<String> values) {
            addCriterion("reny_jg in", values, "renyJg");
            return (Criteria) this;
        }

        public Criteria andRenyJgNotIn(List<String> values) {
            addCriterion("reny_jg not in", values, "renyJg");
            return (Criteria) this;
        }

        public Criteria andRenyJgBetween(String value1, String value2) {
            addCriterion("reny_jg between", value1, value2, "renyJg");
            return (Criteria) this;
        }

        public Criteria andRenyJgNotBetween(String value1, String value2) {
            addCriterion("reny_jg not between", value1, value2, "renyJg");
            return (Criteria) this;
        }

        public Criteria andRenyMzIsNull() {
            addCriterion("reny_mz is null");
            return (Criteria) this;
        }

        public Criteria andRenyMzIsNotNull() {
            addCriterion("reny_mz is not null");
            return (Criteria) this;
        }

        public Criteria andRenyMzEqualTo(String value) {
            addCriterion("reny_mz =", value, "renyMz");
            return (Criteria) this;
        }

        public Criteria andRenyMzNotEqualTo(String value) {
            addCriterion("reny_mz <>", value, "renyMz");
            return (Criteria) this;
        }

        public Criteria andRenyMzGreaterThan(String value) {
            addCriterion("reny_mz >", value, "renyMz");
            return (Criteria) this;
        }

        public Criteria andRenyMzGreaterThanOrEqualTo(String value) {
            addCriterion("reny_mz >=", value, "renyMz");
            return (Criteria) this;
        }

        public Criteria andRenyMzLessThan(String value) {
            addCriterion("reny_mz <", value, "renyMz");
            return (Criteria) this;
        }

        public Criteria andRenyMzLessThanOrEqualTo(String value) {
            addCriterion("reny_mz <=", value, "renyMz");
            return (Criteria) this;
        }

        public Criteria andRenyMzLike(String value) {
            addCriterion("reny_mz like", value, "renyMz");
            return (Criteria) this;
        }

        public Criteria andRenyMzNotLike(String value) {
            addCriterion("reny_mz not like", value, "renyMz");
            return (Criteria) this;
        }

        public Criteria andRenyMzIn(List<String> values) {
            addCriterion("reny_mz in", values, "renyMz");
            return (Criteria) this;
        }

        public Criteria andRenyMzNotIn(List<String> values) {
            addCriterion("reny_mz not in", values, "renyMz");
            return (Criteria) this;
        }

        public Criteria andRenyMzBetween(String value1, String value2) {
            addCriterion("reny_mz between", value1, value2, "renyMz");
            return (Criteria) this;
        }

        public Criteria andRenyMzNotBetween(String value1, String value2) {
            addCriterion("reny_mz not between", value1, value2, "renyMz");
            return (Criteria) this;
        }

        public Criteria andRenyYbIsNull() {
            addCriterion("reny_yb is null");
            return (Criteria) this;
        }

        public Criteria andRenyYbIsNotNull() {
            addCriterion("reny_yb is not null");
            return (Criteria) this;
        }

        public Criteria andRenyYbEqualTo(String value) {
            addCriterion("reny_yb =", value, "renyYb");
            return (Criteria) this;
        }

        public Criteria andRenyYbNotEqualTo(String value) {
            addCriterion("reny_yb <>", value, "renyYb");
            return (Criteria) this;
        }

        public Criteria andRenyYbGreaterThan(String value) {
            addCriterion("reny_yb >", value, "renyYb");
            return (Criteria) this;
        }

        public Criteria andRenyYbGreaterThanOrEqualTo(String value) {
            addCriterion("reny_yb >=", value, "renyYb");
            return (Criteria) this;
        }

        public Criteria andRenyYbLessThan(String value) {
            addCriterion("reny_yb <", value, "renyYb");
            return (Criteria) this;
        }

        public Criteria andRenyYbLessThanOrEqualTo(String value) {
            addCriterion("reny_yb <=", value, "renyYb");
            return (Criteria) this;
        }

        public Criteria andRenyYbLike(String value) {
            addCriterion("reny_yb like", value, "renyYb");
            return (Criteria) this;
        }

        public Criteria andRenyYbNotLike(String value) {
            addCriterion("reny_yb not like", value, "renyYb");
            return (Criteria) this;
        }

        public Criteria andRenyYbIn(List<String> values) {
            addCriterion("reny_yb in", values, "renyYb");
            return (Criteria) this;
        }

        public Criteria andRenyYbNotIn(List<String> values) {
            addCriterion("reny_yb not in", values, "renyYb");
            return (Criteria) this;
        }

        public Criteria andRenyYbBetween(String value1, String value2) {
            addCriterion("reny_yb between", value1, value2, "renyYb");
            return (Criteria) this;
        }

        public Criteria andRenyYbNotBetween(String value1, String value2) {
            addCriterion("reny_yb not between", value1, value2, "renyYb");
            return (Criteria) this;
        }

        public Criteria andRenyZzIsNull() {
            addCriterion("reny_zz is null");
            return (Criteria) this;
        }

        public Criteria andRenyZzIsNotNull() {
            addCriterion("reny_zz is not null");
            return (Criteria) this;
        }

        public Criteria andRenyZzEqualTo(String value) {
            addCriterion("reny_zz =", value, "renyZz");
            return (Criteria) this;
        }

        public Criteria andRenyZzNotEqualTo(String value) {
            addCriterion("reny_zz <>", value, "renyZz");
            return (Criteria) this;
        }

        public Criteria andRenyZzGreaterThan(String value) {
            addCriterion("reny_zz >", value, "renyZz");
            return (Criteria) this;
        }

        public Criteria andRenyZzGreaterThanOrEqualTo(String value) {
            addCriterion("reny_zz >=", value, "renyZz");
            return (Criteria) this;
        }

        public Criteria andRenyZzLessThan(String value) {
            addCriterion("reny_zz <", value, "renyZz");
            return (Criteria) this;
        }

        public Criteria andRenyZzLessThanOrEqualTo(String value) {
            addCriterion("reny_zz <=", value, "renyZz");
            return (Criteria) this;
        }

        public Criteria andRenyZzLike(String value) {
            addCriterion("reny_zz like", value, "renyZz");
            return (Criteria) this;
        }

        public Criteria andRenyZzNotLike(String value) {
            addCriterion("reny_zz not like", value, "renyZz");
            return (Criteria) this;
        }

        public Criteria andRenyZzIn(List<String> values) {
            addCriterion("reny_zz in", values, "renyZz");
            return (Criteria) this;
        }

        public Criteria andRenyZzNotIn(List<String> values) {
            addCriterion("reny_zz not in", values, "renyZz");
            return (Criteria) this;
        }

        public Criteria andRenyZzBetween(String value1, String value2) {
            addCriterion("reny_zz between", value1, value2, "renyZz");
            return (Criteria) this;
        }

        public Criteria andRenyZzNotBetween(String value1, String value2) {
            addCriterion("reny_zz not between", value1, value2, "renyZz");
            return (Criteria) this;
        }

        public Criteria andRenySfIsNull() {
            addCriterion("reny_sf is null");
            return (Criteria) this;
        }

        public Criteria andRenySfIsNotNull() {
            addCriterion("reny_sf is not null");
            return (Criteria) this;
        }

        public Criteria andRenySfEqualTo(String value) {
            addCriterion("reny_sf =", value, "renySf");
            return (Criteria) this;
        }

        public Criteria andRenySfNotEqualTo(String value) {
            addCriterion("reny_sf <>", value, "renySf");
            return (Criteria) this;
        }

        public Criteria andRenySfGreaterThan(String value) {
            addCriterion("reny_sf >", value, "renySf");
            return (Criteria) this;
        }

        public Criteria andRenySfGreaterThanOrEqualTo(String value) {
            addCriterion("reny_sf >=", value, "renySf");
            return (Criteria) this;
        }

        public Criteria andRenySfLessThan(String value) {
            addCriterion("reny_sf <", value, "renySf");
            return (Criteria) this;
        }

        public Criteria andRenySfLessThanOrEqualTo(String value) {
            addCriterion("reny_sf <=", value, "renySf");
            return (Criteria) this;
        }

        public Criteria andRenySfLike(String value) {
            addCriterion("reny_sf like", value, "renySf");
            return (Criteria) this;
        }

        public Criteria andRenySfNotLike(String value) {
            addCriterion("reny_sf not like", value, "renySf");
            return (Criteria) this;
        }

        public Criteria andRenySfIn(List<String> values) {
            addCriterion("reny_sf in", values, "renySf");
            return (Criteria) this;
        }

        public Criteria andRenySfNotIn(List<String> values) {
            addCriterion("reny_sf not in", values, "renySf");
            return (Criteria) this;
        }

        public Criteria andRenySfBetween(String value1, String value2) {
            addCriterion("reny_sf between", value1, value2, "renySf");
            return (Criteria) this;
        }

        public Criteria andRenySfNotBetween(String value1, String value2) {
            addCriterion("reny_sf not between", value1, value2, "renySf");
            return (Criteria) this;
        }

        public Criteria andRenyDhIsNull() {
            addCriterion("reny_dh is null");
            return (Criteria) this;
        }

        public Criteria andRenyDhIsNotNull() {
            addCriterion("reny_dh is not null");
            return (Criteria) this;
        }

        public Criteria andRenyDhEqualTo(String value) {
            addCriterion("reny_dh =", value, "renyDh");
            return (Criteria) this;
        }

        public Criteria andRenyDhNotEqualTo(String value) {
            addCriterion("reny_dh <>", value, "renyDh");
            return (Criteria) this;
        }

        public Criteria andRenyDhGreaterThan(String value) {
            addCriterion("reny_dh >", value, "renyDh");
            return (Criteria) this;
        }

        public Criteria andRenyDhGreaterThanOrEqualTo(String value) {
            addCriterion("reny_dh >=", value, "renyDh");
            return (Criteria) this;
        }

        public Criteria andRenyDhLessThan(String value) {
            addCriterion("reny_dh <", value, "renyDh");
            return (Criteria) this;
        }

        public Criteria andRenyDhLessThanOrEqualTo(String value) {
            addCriterion("reny_dh <=", value, "renyDh");
            return (Criteria) this;
        }

        public Criteria andRenyDhLike(String value) {
            addCriterion("reny_dh like", value, "renyDh");
            return (Criteria) this;
        }

        public Criteria andRenyDhNotLike(String value) {
            addCriterion("reny_dh not like", value, "renyDh");
            return (Criteria) this;
        }

        public Criteria andRenyDhIn(List<String> values) {
            addCriterion("reny_dh in", values, "renyDh");
            return (Criteria) this;
        }

        public Criteria andRenyDhNotIn(List<String> values) {
            addCriterion("reny_dh not in", values, "renyDh");
            return (Criteria) this;
        }

        public Criteria andRenyDhBetween(String value1, String value2) {
            addCriterion("reny_dh between", value1, value2, "renyDh");
            return (Criteria) this;
        }

        public Criteria andRenyDhNotBetween(String value1, String value2) {
            addCriterion("reny_dh not between", value1, value2, "renyDh");
            return (Criteria) this;
        }

        public Criteria andRenyYxIsNull() {
            addCriterion("reny_yx is null");
            return (Criteria) this;
        }

        public Criteria andRenyYxIsNotNull() {
            addCriterion("reny_yx is not null");
            return (Criteria) this;
        }

        public Criteria andRenyYxEqualTo(String value) {
            addCriterion("reny_yx =", value, "renyYx");
            return (Criteria) this;
        }

        public Criteria andRenyYxNotEqualTo(String value) {
            addCriterion("reny_yx <>", value, "renyYx");
            return (Criteria) this;
        }

        public Criteria andRenyYxGreaterThan(String value) {
            addCriterion("reny_yx >", value, "renyYx");
            return (Criteria) this;
        }

        public Criteria andRenyYxGreaterThanOrEqualTo(String value) {
            addCriterion("reny_yx >=", value, "renyYx");
            return (Criteria) this;
        }

        public Criteria andRenyYxLessThan(String value) {
            addCriterion("reny_yx <", value, "renyYx");
            return (Criteria) this;
        }

        public Criteria andRenyYxLessThanOrEqualTo(String value) {
            addCriterion("reny_yx <=", value, "renyYx");
            return (Criteria) this;
        }

        public Criteria andRenyYxLike(String value) {
            addCriterion("reny_yx like", value, "renyYx");
            return (Criteria) this;
        }

        public Criteria andRenyYxNotLike(String value) {
            addCriterion("reny_yx not like", value, "renyYx");
            return (Criteria) this;
        }

        public Criteria andRenyYxIn(List<String> values) {
            addCriterion("reny_yx in", values, "renyYx");
            return (Criteria) this;
        }

        public Criteria andRenyYxNotIn(List<String> values) {
            addCriterion("reny_yx not in", values, "renyYx");
            return (Criteria) this;
        }

        public Criteria andRenyYxBetween(String value1, String value2) {
            addCriterion("reny_yx between", value1, value2, "renyYx");
            return (Criteria) this;
        }

        public Criteria andRenyYxNotBetween(String value1, String value2) {
            addCriterion("reny_yx not between", value1, value2, "renyYx");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table gongzry
     *
     * @mbggenerated do_not_delete_during_merge Tue Apr 08 20:09:00 CST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table gongzry
     *
     * @mbggenerated Tue Apr 08 20:09:00 CST 2014
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}