package com.xym.bossed.db.mybatis.employee;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class Employee implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = -6050095628648812941L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gongzry.reny_dm
     *
     * @mbggenerated Tue Apr 08 20:09:00 CST 2014
     */
    private String renyDm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gongzry.danw_dm
     *
     * @mbggenerated Tue Apr 08 20:09:00 CST 2014
     */
    private String danwDm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gongzry.dept_mc
     *
     * @mbggenerated Tue Apr 08 20:09:00 CST 2014
     */
    private String deptMc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gongzry.reny_xm
     *
     * @mbggenerated Tue Apr 08 20:09:00 CST 2014
     */
    private String renyXm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gongzry.reny_lp
     *
     * @mbggenerated Tue Apr 08 20:09:00 CST 2014
     */
    private String renyLp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gongzry.reny_xb
     *
     * @mbggenerated Tue Apr 08 20:09:00 CST 2014
     */
    private String renyXb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gongzry.reny_hb
     *
     * @mbggenerated Tue Apr 08 20:09:00 CST 2014
     */
    private String renyHb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gongzry.reny_gz
     *
     * @mbggenerated Tue Apr 08 20:09:00 CST 2014
     */
    private BigDecimal renyGz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gongzry.reny_zw
     *
     * @mbggenerated Tue Apr 08 20:09:00 CST 2014
     */
    private String renyZw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gongzry.reny_ly
     *
     * @mbggenerated Tue Apr 08 20:09:00 CST 2014
     */
    private String renyLy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gongzry.reny_wh
     *
     * @mbggenerated Tue Apr 08 20:09:00 CST 2014
     */
    private String renyWh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gongzry.reny_cs
     *
     * @mbggenerated Tue Apr 08 20:09:00 CST 2014
     */
    private Date renyCs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gongzry.reny_sj
     *
     * @mbggenerated Tue Apr 08 20:09:00 CST 2014
     */
    private Date renySj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gongzry.reny_gl
     *
     * @mbggenerated Tue Apr 08 20:09:00 CST 2014
     */
    private Short renyGl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gongzry.reny_jg
     *
     * @mbggenerated Tue Apr 08 20:09:00 CST 2014
     */
    private String renyJg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gongzry.reny_mz
     *
     * @mbggenerated Tue Apr 08 20:09:00 CST 2014
     */
    private String renyMz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gongzry.reny_yb
     *
     * @mbggenerated Tue Apr 08 20:09:00 CST 2014
     */
    private String renyYb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gongzry.reny_zz
     *
     * @mbggenerated Tue Apr 08 20:09:00 CST 2014
     */
    private String renyZz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gongzry.reny_sf
     *
     * @mbggenerated Tue Apr 08 20:09:00 CST 2014
     */
    private String renySf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gongzry.reny_dh
     *
     * @mbggenerated Tue Apr 08 20:09:00 CST 2014
     */
    private String renyDh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gongzry.reny_yx
     *
     * @mbggenerated Tue Apr 08 20:09:00 CST 2014
     */
    private String renyYx;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gongzry.reny_dm
     *
     * @return the value of gongzry.reny_dm
     *
     * @mbggenerated Tue Apr 08 20:09:00 CST 2014
     */
    public String getRenyDm() {
        return renyDm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gongzry.reny_dm
     *
     * @param renyDm the value for gongzry.reny_dm
     *
     * @mbggenerated Tue Apr 08 20:09:00 CST 2014
     */
    public void setRenyDm(String renyDm) {
        this.renyDm = renyDm == null ? null : renyDm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gongzry.danw_dm
     *
     * @return the value of gongzry.danw_dm
     *
     * @mbggenerated Tue Apr 08 20:09:00 CST 2014
     */
    public String getDanwDm() {
        return danwDm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gongzry.danw_dm
     *
     * @param danwDm the value for gongzry.danw_dm
     *
     * @mbggenerated Tue Apr 08 20:09:00 CST 2014
     */
    public void setDanwDm(String danwDm) {
        this.danwDm = danwDm == null ? null : danwDm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gongzry.dept_mc
     *
     * @return the value of gongzry.dept_mc
     *
     * @mbggenerated Tue Apr 08 20:09:00 CST 2014
     */
    public String getDeptMc() {
        return deptMc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gongzry.dept_mc
     *
     * @param deptMc the value for gongzry.dept_mc
     *
     * @mbggenerated Tue Apr 08 20:09:00 CST 2014
     */
    public void setDeptMc(String deptMc) {
        this.deptMc = deptMc == null ? null : deptMc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gongzry.reny_xm
     *
     * @return the value of gongzry.reny_xm
     *
     * @mbggenerated Tue Apr 08 20:09:00 CST 2014
     */
    public String getRenyXm() {
        return renyXm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gongzry.reny_xm
     *
     * @param renyXm the value for gongzry.reny_xm
     *
     * @mbggenerated Tue Apr 08 20:09:00 CST 2014
     */
    public void setRenyXm(String renyXm) {
        this.renyXm = renyXm == null ? null : renyXm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gongzry.reny_lp
     *
     * @return the value of gongzry.reny_lp
     *
     * @mbggenerated Tue Apr 08 20:09:00 CST 2014
     */
    public String getRenyLp() {
        return renyLp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gongzry.reny_lp
     *
     * @param renyLp the value for gongzry.reny_lp
     *
     * @mbggenerated Tue Apr 08 20:09:00 CST 2014
     */
    public void setRenyLp(String renyLp) {
        this.renyLp = renyLp == null ? null : renyLp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gongzry.reny_xb
     *
     * @return the value of gongzry.reny_xb
     *
     * @mbggenerated Tue Apr 08 20:09:00 CST 2014
     */
    public String getRenyXb() {
        return renyXb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gongzry.reny_xb
     *
     * @param renyXb the value for gongzry.reny_xb
     *
     * @mbggenerated Tue Apr 08 20:09:00 CST 2014
     */
    public void setRenyXb(String renyXb) {
        this.renyXb = renyXb == null ? null : renyXb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gongzry.reny_hb
     *
     * @return the value of gongzry.reny_hb
     *
     * @mbggenerated Tue Apr 08 20:09:00 CST 2014
     */
    public String getRenyHb() {
        return renyHb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gongzry.reny_hb
     *
     * @param renyHb the value for gongzry.reny_hb
     *
     * @mbggenerated Tue Apr 08 20:09:00 CST 2014
     */
    public void setRenyHb(String renyHb) {
        this.renyHb = renyHb == null ? null : renyHb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gongzry.reny_gz
     *
     * @return the value of gongzry.reny_gz
     *
     * @mbggenerated Tue Apr 08 20:09:00 CST 2014
     */
    public BigDecimal getRenyGz() {
        return renyGz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gongzry.reny_gz
     *
     * @param renyGz the value for gongzry.reny_gz
     *
     * @mbggenerated Tue Apr 08 20:09:00 CST 2014
     */
    public void setRenyGz(BigDecimal renyGz) {
        this.renyGz = renyGz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gongzry.reny_zw
     *
     * @return the value of gongzry.reny_zw
     *
     * @mbggenerated Tue Apr 08 20:09:00 CST 2014
     */
    public String getRenyZw() {
        return renyZw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gongzry.reny_zw
     *
     * @param renyZw the value for gongzry.reny_zw
     *
     * @mbggenerated Tue Apr 08 20:09:00 CST 2014
     */
    public void setRenyZw(String renyZw) {
        this.renyZw = renyZw == null ? null : renyZw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gongzry.reny_ly
     *
     * @return the value of gongzry.reny_ly
     *
     * @mbggenerated Tue Apr 08 20:09:00 CST 2014
     */
    public String getRenyLy() {
        return renyLy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gongzry.reny_ly
     *
     * @param renyLy the value for gongzry.reny_ly
     *
     * @mbggenerated Tue Apr 08 20:09:00 CST 2014
     */
    public void setRenyLy(String renyLy) {
        this.renyLy = renyLy == null ? null : renyLy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gongzry.reny_wh
     *
     * @return the value of gongzry.reny_wh
     *
     * @mbggenerated Tue Apr 08 20:09:00 CST 2014
     */
    public String getRenyWh() {
        return renyWh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gongzry.reny_wh
     *
     * @param renyWh the value for gongzry.reny_wh
     *
     * @mbggenerated Tue Apr 08 20:09:00 CST 2014
     */
    public void setRenyWh(String renyWh) {
        this.renyWh = renyWh == null ? null : renyWh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gongzry.reny_cs
     *
     * @return the value of gongzry.reny_cs
     *
     * @mbggenerated Tue Apr 08 20:09:00 CST 2014
     */
    public Date getRenyCs() {
        return renyCs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gongzry.reny_cs
     *
     * @param renyCs the value for gongzry.reny_cs
     *
     * @mbggenerated Tue Apr 08 20:09:00 CST 2014
     */
    public void setRenyCs(Date renyCs) {
        this.renyCs = renyCs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gongzry.reny_sj
     *
     * @return the value of gongzry.reny_sj
     *
     * @mbggenerated Tue Apr 08 20:09:00 CST 2014
     */
    public Date getRenySj() {
        return renySj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gongzry.reny_sj
     *
     * @param renySj the value for gongzry.reny_sj
     *
     * @mbggenerated Tue Apr 08 20:09:00 CST 2014
     */
    public void setRenySj(Date renySj) {
        this.renySj = renySj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gongzry.reny_gl
     *
     * @return the value of gongzry.reny_gl
     *
     * @mbggenerated Tue Apr 08 20:09:00 CST 2014
     */
    public Short getRenyGl() {
        return renyGl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gongzry.reny_gl
     *
     * @param renyGl the value for gongzry.reny_gl
     *
     * @mbggenerated Tue Apr 08 20:09:00 CST 2014
     */
    public void setRenyGl(Short renyGl) {
        this.renyGl = renyGl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gongzry.reny_jg
     *
     * @return the value of gongzry.reny_jg
     *
     * @mbggenerated Tue Apr 08 20:09:00 CST 2014
     */
    public String getRenyJg() {
        return renyJg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gongzry.reny_jg
     *
     * @param renyJg the value for gongzry.reny_jg
     *
     * @mbggenerated Tue Apr 08 20:09:00 CST 2014
     */
    public void setRenyJg(String renyJg) {
        this.renyJg = renyJg == null ? null : renyJg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gongzry.reny_mz
     *
     * @return the value of gongzry.reny_mz
     *
     * @mbggenerated Tue Apr 08 20:09:00 CST 2014
     */
    public String getRenyMz() {
        return renyMz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gongzry.reny_mz
     *
     * @param renyMz the value for gongzry.reny_mz
     *
     * @mbggenerated Tue Apr 08 20:09:00 CST 2014
     */
    public void setRenyMz(String renyMz) {
        this.renyMz = renyMz == null ? null : renyMz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gongzry.reny_yb
     *
     * @return the value of gongzry.reny_yb
     *
     * @mbggenerated Tue Apr 08 20:09:00 CST 2014
     */
    public String getRenyYb() {
        return renyYb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gongzry.reny_yb
     *
     * @param renyYb the value for gongzry.reny_yb
     *
     * @mbggenerated Tue Apr 08 20:09:00 CST 2014
     */
    public void setRenyYb(String renyYb) {
        this.renyYb = renyYb == null ? null : renyYb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gongzry.reny_zz
     *
     * @return the value of gongzry.reny_zz
     *
     * @mbggenerated Tue Apr 08 20:09:00 CST 2014
     */
    public String getRenyZz() {
        return renyZz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gongzry.reny_zz
     *
     * @param renyZz the value for gongzry.reny_zz
     *
     * @mbggenerated Tue Apr 08 20:09:00 CST 2014
     */
    public void setRenyZz(String renyZz) {
        this.renyZz = renyZz == null ? null : renyZz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gongzry.reny_sf
     *
     * @return the value of gongzry.reny_sf
     *
     * @mbggenerated Tue Apr 08 20:09:00 CST 2014
     */
    public String getRenySf() {
        return renySf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gongzry.reny_sf
     *
     * @param renySf the value for gongzry.reny_sf
     *
     * @mbggenerated Tue Apr 08 20:09:00 CST 2014
     */
    public void setRenySf(String renySf) {
        this.renySf = renySf == null ? null : renySf.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gongzry.reny_dh
     *
     * @return the value of gongzry.reny_dh
     *
     * @mbggenerated Tue Apr 08 20:09:00 CST 2014
     */
    public String getRenyDh() {
        return renyDh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gongzry.reny_dh
     *
     * @param renyDh the value for gongzry.reny_dh
     *
     * @mbggenerated Tue Apr 08 20:09:00 CST 2014
     */
    public void setRenyDh(String renyDh) {
        this.renyDh = renyDh == null ? null : renyDh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gongzry.reny_yx
     *
     * @return the value of gongzry.reny_yx
     *
     * @mbggenerated Tue Apr 08 20:09:00 CST 2014
     */
    public String getRenyYx() {
        return renyYx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gongzry.reny_yx
     *
     * @param renyYx the value for gongzry.reny_yx
     *
     * @mbggenerated Tue Apr 08 20:09:00 CST 2014
     */
    public void setRenyYx(String renyYx) {
        this.renyYx = renyYx == null ? null : renyYx.trim();
    }
}