package com.xym.bossed.db.mybatis.employee;

import com.xym.bossed.db.mybatis.employee.Employee;
import com.xym.bossed.db.mybatis.employee.EmployeeExample;
import com.xym.bossed.db.mybatis.employee.EmployeeWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EmployeeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gongzry
     *
     * @mbggenerated Tue Apr 08 20:09:00 CST 2014
     */
    int countByExample(EmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gongzry
     *
     * @mbggenerated Tue Apr 08 20:09:00 CST 2014
     */
    int deleteByExample(EmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gongzry
     *
     * @mbggenerated Tue Apr 08 20:09:00 CST 2014
     */
    int deleteByPrimaryKey(String renyDm);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gongzry
     *
     * @mbggenerated Tue Apr 08 20:09:00 CST 2014
     */
    int insert(EmployeeWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gongzry
     *
     * @mbggenerated Tue Apr 08 20:09:00 CST 2014
     */
    int insertSelective(EmployeeWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gongzry
     *
     * @mbggenerated Tue Apr 08 20:09:00 CST 2014
     */
    List<EmployeeWithBLOBs> selectByExampleWithBLOBs(EmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gongzry
     *
     * @mbggenerated Tue Apr 08 20:09:00 CST 2014
     */
    List<Employee> selectByExample(EmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gongzry
     *
     * @mbggenerated Tue Apr 08 20:09:00 CST 2014
     */
    EmployeeWithBLOBs selectByPrimaryKey(String renyDm);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gongzry
     *
     * @mbggenerated Tue Apr 08 20:09:00 CST 2014
     */
    int updateByExampleSelective(@Param("record") EmployeeWithBLOBs record, @Param("example") EmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gongzry
     *
     * @mbggenerated Tue Apr 08 20:09:00 CST 2014
     */
    int updateByExampleWithBLOBs(@Param("record") EmployeeWithBLOBs record, @Param("example") EmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gongzry
     *
     * @mbggenerated Tue Apr 08 20:09:00 CST 2014
     */
    int updateByExample(@Param("record") Employee record, @Param("example") EmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gongzry
     *
     * @mbggenerated Tue Apr 08 20:09:00 CST 2014
     */
    int updateByPrimaryKeySelective(EmployeeWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gongzry
     *
     * @mbggenerated Tue Apr 08 20:09:00 CST 2014
     */
    int updateByPrimaryKeyWithBLOBs(EmployeeWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gongzry
     *
     * @mbggenerated Tue Apr 08 20:09:00 CST 2014
     */
    int updateByPrimaryKey(Employee record);
}