package com.xym.bossed.db.mybatis.gys.leibie;

import java.io.Serializable;

public class GongYSLeibie implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = -7114601389274539553L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sm_gongyshlb.kehulb_dm
     *
     * @mbggenerated Mon Jul 15 16:35:50 CST 2013
     */
    private String kehulbDm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sm_gongyshlb.kehulb_mc
     *
     * @mbggenerated Mon Jul 15 16:35:50 CST 2013
     */
    private String kehulbMc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sm_gongyshlb.kehulb_top
     *
     * @mbggenerated Mon Jul 15 16:35:50 CST 2013
     */
    private String kehulbTop;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sm_gongyshlb.kehulb_qz
     *
     * @mbggenerated Mon Jul 15 16:35:50 CST 2013
     */
    private String kehulbQz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sm_gongyshlb.kehulb_len
     *
     * @mbggenerated Mon Jul 15 16:35:50 CST 2013
     */
    private Integer kehulbLen;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_gongyshlb.kehulb_dm
     *
     * @return the value of sm_gongyshlb.kehulb_dm
     *
     * @mbggenerated Mon Jul 15 16:35:50 CST 2013
     */
    public String getKehulbDm() {
        return kehulbDm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_gongyshlb.kehulb_dm
     *
     * @param kehulbDm the value for sm_gongyshlb.kehulb_dm
     *
     * @mbggenerated Mon Jul 15 16:35:50 CST 2013
     */
    public void setKehulbDm(String kehulbDm) {
        this.kehulbDm = kehulbDm == null ? null : kehulbDm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_gongyshlb.kehulb_mc
     *
     * @return the value of sm_gongyshlb.kehulb_mc
     *
     * @mbggenerated Mon Jul 15 16:35:50 CST 2013
     */
    public String getKehulbMc() {
        return kehulbMc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_gongyshlb.kehulb_mc
     *
     * @param kehulbMc the value for sm_gongyshlb.kehulb_mc
     *
     * @mbggenerated Mon Jul 15 16:35:50 CST 2013
     */
    public void setKehulbMc(String kehulbMc) {
        this.kehulbMc = kehulbMc == null ? null : kehulbMc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_gongyshlb.kehulb_top
     *
     * @return the value of sm_gongyshlb.kehulb_top
     *
     * @mbggenerated Mon Jul 15 16:35:50 CST 2013
     */
    public String getKehulbTop() {
        return kehulbTop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_gongyshlb.kehulb_top
     *
     * @param kehulbTop the value for sm_gongyshlb.kehulb_top
     *
     * @mbggenerated Mon Jul 15 16:35:50 CST 2013
     */
    public void setKehulbTop(String kehulbTop) {
        this.kehulbTop = kehulbTop == null ? null : kehulbTop.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_gongyshlb.kehulb_qz
     *
     * @return the value of sm_gongyshlb.kehulb_qz
     *
     * @mbggenerated Mon Jul 15 16:35:50 CST 2013
     */
    public String getKehulbQz() {
        return kehulbQz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_gongyshlb.kehulb_qz
     *
     * @param kehulbQz the value for sm_gongyshlb.kehulb_qz
     *
     * @mbggenerated Mon Jul 15 16:35:50 CST 2013
     */
    public void setKehulbQz(String kehulbQz) {
        this.kehulbQz = kehulbQz == null ? null : kehulbQz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_gongyshlb.kehulb_len
     *
     * @return the value of sm_gongyshlb.kehulb_len
     *
     * @mbggenerated Mon Jul 15 16:35:50 CST 2013
     */
    public Integer getKehulbLen() {
        return kehulbLen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_gongyshlb.kehulb_len
     *
     * @param kehulbLen the value for sm_gongyshlb.kehulb_len
     *
     * @mbggenerated Mon Jul 15 16:35:50 CST 2013
     */
    public void setKehulbLen(Integer kehulbLen) {
        this.kehulbLen = kehulbLen;
    }
}