package com.xym.bossed.db.mybatis.parts.fenlu;

import com.xym.bossed.db.mybatis.parts.fenlu.PartsFenLu;
import com.xym.bossed.db.mybatis.parts.fenlu.PartsFenLuExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PartsFenLuMapper {
	
	List<PartsFenLu> selectByPartsNo(String partsNo);
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kucshp_fl
     *
     * @mbggenerated Fri Apr 25 10:12:29 CST 2014
     */
    int countByExample(PartsFenLuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kucshp_fl
     *
     * @mbggenerated Fri Apr 25 10:12:29 CST 2014
     */
    int deleteByExample(PartsFenLuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kucshp_fl
     *
     * @mbggenerated Fri Apr 25 10:12:29 CST 2014
     */
    int deleteByPrimaryKey(Long recoNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kucshp_fl
     *
     * @mbggenerated Fri Apr 25 10:12:29 CST 2014
     */
    int insert(PartsFenLu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kucshp_fl
     *
     * @mbggenerated Fri Apr 25 10:12:29 CST 2014
     */
    int insertSelective(PartsFenLu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kucshp_fl
     *
     * @mbggenerated Fri Apr 25 10:12:29 CST 2014
     */
    List<PartsFenLu> selectByExample(PartsFenLuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kucshp_fl
     *
     * @mbggenerated Fri Apr 25 10:12:29 CST 2014
     */
    PartsFenLu selectByPrimaryKey(Long recoNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kucshp_fl
     *
     * @mbggenerated Fri Apr 25 10:12:29 CST 2014
     */
    int updateByExampleSelective(@Param("record") PartsFenLu record, @Param("example") PartsFenLuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kucshp_fl
     *
     * @mbggenerated Fri Apr 25 10:12:29 CST 2014
     */
    int updateByExample(@Param("record") PartsFenLu record, @Param("example") PartsFenLuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kucshp_fl
     *
     * @mbggenerated Fri Apr 25 10:12:29 CST 2014
     */
    int updateByPrimaryKeySelective(PartsFenLu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kucshp_fl
     *
     * @mbggenerated Fri Apr 25 10:12:29 CST 2014
     */
    int updateByPrimaryKey(PartsFenLu record);
}