package com.xym.bossed.db.mybatis.parts.fenlu;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class PartsFenLuExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table kucshp_fl
     *
     * @mbggenerated Fri Apr 25 10:12:29 CST 2014
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table kucshp_fl
     *
     * @mbggenerated Fri Apr 25 10:12:29 CST 2014
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table kucshp_fl
     *
     * @mbggenerated Fri Apr 25 10:12:29 CST 2014
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kucshp_fl
     *
     * @mbggenerated Fri Apr 25 10:12:29 CST 2014
     */
    public PartsFenLuExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kucshp_fl
     *
     * @mbggenerated Fri Apr 25 10:12:29 CST 2014
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kucshp_fl
     *
     * @mbggenerated Fri Apr 25 10:12:29 CST 2014
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kucshp_fl
     *
     * @mbggenerated Fri Apr 25 10:12:29 CST 2014
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kucshp_fl
     *
     * @mbggenerated Fri Apr 25 10:12:29 CST 2014
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kucshp_fl
     *
     * @mbggenerated Fri Apr 25 10:12:29 CST 2014
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kucshp_fl
     *
     * @mbggenerated Fri Apr 25 10:12:29 CST 2014
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kucshp_fl
     *
     * @mbggenerated Fri Apr 25 10:12:29 CST 2014
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kucshp_fl
     *
     * @mbggenerated Fri Apr 25 10:12:29 CST 2014
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kucshp_fl
     *
     * @mbggenerated Fri Apr 25 10:12:29 CST 2014
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kucshp_fl
     *
     * @mbggenerated Fri Apr 25 10:12:29 CST 2014
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table kucshp_fl
     *
     * @mbggenerated Fri Apr 25 10:12:29 CST 2014
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andRecoNoIsNull() {
            addCriterion("reco_no is null");
            return (Criteria) this;
        }

        public Criteria andRecoNoIsNotNull() {
            addCriterion("reco_no is not null");
            return (Criteria) this;
        }

        public Criteria andRecoNoEqualTo(Long value) {
            addCriterion("reco_no =", value, "recoNo");
            return (Criteria) this;
        }

        public Criteria andRecoNoNotEqualTo(Long value) {
            addCriterion("reco_no <>", value, "recoNo");
            return (Criteria) this;
        }

        public Criteria andRecoNoGreaterThan(Long value) {
            addCriterion("reco_no >", value, "recoNo");
            return (Criteria) this;
        }

        public Criteria andRecoNoGreaterThanOrEqualTo(Long value) {
            addCriterion("reco_no >=", value, "recoNo");
            return (Criteria) this;
        }

        public Criteria andRecoNoLessThan(Long value) {
            addCriterion("reco_no <", value, "recoNo");
            return (Criteria) this;
        }

        public Criteria andRecoNoLessThanOrEqualTo(Long value) {
            addCriterion("reco_no <=", value, "recoNo");
            return (Criteria) this;
        }

        public Criteria andRecoNoIn(List<Long> values) {
            addCriterion("reco_no in", values, "recoNo");
            return (Criteria) this;
        }

        public Criteria andRecoNoNotIn(List<Long> values) {
            addCriterion("reco_no not in", values, "recoNo");
            return (Criteria) this;
        }

        public Criteria andRecoNoBetween(Long value1, Long value2) {
            addCriterion("reco_no between", value1, value2, "recoNo");
            return (Criteria) this;
        }

        public Criteria andRecoNoNotBetween(Long value1, Long value2) {
            addCriterion("reco_no not between", value1, value2, "recoNo");
            return (Criteria) this;
        }

        public Criteria andCangkDmIsNull() {
            addCriterion("cangk_dm is null");
            return (Criteria) this;
        }

        public Criteria andCangkDmIsNotNull() {
            addCriterion("cangk_dm is not null");
            return (Criteria) this;
        }

        public Criteria andCangkDmEqualTo(String value) {
            addCriterion("cangk_dm =", value, "cangkDm");
            return (Criteria) this;
        }

        public Criteria andCangkDmNotEqualTo(String value) {
            addCriterion("cangk_dm <>", value, "cangkDm");
            return (Criteria) this;
        }

        public Criteria andCangkDmGreaterThan(String value) {
            addCriterion("cangk_dm >", value, "cangkDm");
            return (Criteria) this;
        }

        public Criteria andCangkDmGreaterThanOrEqualTo(String value) {
            addCriterion("cangk_dm >=", value, "cangkDm");
            return (Criteria) this;
        }

        public Criteria andCangkDmLessThan(String value) {
            addCriterion("cangk_dm <", value, "cangkDm");
            return (Criteria) this;
        }

        public Criteria andCangkDmLessThanOrEqualTo(String value) {
            addCriterion("cangk_dm <=", value, "cangkDm");
            return (Criteria) this;
        }

        public Criteria andCangkDmLike(String value) {
            addCriterion("cangk_dm like", value, "cangkDm");
            return (Criteria) this;
        }

        public Criteria andCangkDmNotLike(String value) {
            addCriterion("cangk_dm not like", value, "cangkDm");
            return (Criteria) this;
        }

        public Criteria andCangkDmIn(List<String> values) {
            addCriterion("cangk_dm in", values, "cangkDm");
            return (Criteria) this;
        }

        public Criteria andCangkDmNotIn(List<String> values) {
            addCriterion("cangk_dm not in", values, "cangkDm");
            return (Criteria) this;
        }

        public Criteria andCangkDmBetween(String value1, String value2) {
            addCriterion("cangk_dm between", value1, value2, "cangkDm");
            return (Criteria) this;
        }

        public Criteria andCangkDmNotBetween(String value1, String value2) {
            addCriterion("cangk_dm not between", value1, value2, "cangkDm");
            return (Criteria) this;
        }

        public Criteria andDanwDmIsNull() {
            addCriterion("danw_dm is null");
            return (Criteria) this;
        }

        public Criteria andDanwDmIsNotNull() {
            addCriterion("danw_dm is not null");
            return (Criteria) this;
        }

        public Criteria andDanwDmEqualTo(String value) {
            addCriterion("danw_dm =", value, "danwDm");
            return (Criteria) this;
        }

        public Criteria andDanwDmNotEqualTo(String value) {
            addCriterion("danw_dm <>", value, "danwDm");
            return (Criteria) this;
        }

        public Criteria andDanwDmGreaterThan(String value) {
            addCriterion("danw_dm >", value, "danwDm");
            return (Criteria) this;
        }

        public Criteria andDanwDmGreaterThanOrEqualTo(String value) {
            addCriterion("danw_dm >=", value, "danwDm");
            return (Criteria) this;
        }

        public Criteria andDanwDmLessThan(String value) {
            addCriterion("danw_dm <", value, "danwDm");
            return (Criteria) this;
        }

        public Criteria andDanwDmLessThanOrEqualTo(String value) {
            addCriterion("danw_dm <=", value, "danwDm");
            return (Criteria) this;
        }

        public Criteria andDanwDmLike(String value) {
            addCriterion("danw_dm like", value, "danwDm");
            return (Criteria) this;
        }

        public Criteria andDanwDmNotLike(String value) {
            addCriterion("danw_dm not like", value, "danwDm");
            return (Criteria) this;
        }

        public Criteria andDanwDmIn(List<String> values) {
            addCriterion("danw_dm in", values, "danwDm");
            return (Criteria) this;
        }

        public Criteria andDanwDmNotIn(List<String> values) {
            addCriterion("danw_dm not in", values, "danwDm");
            return (Criteria) this;
        }

        public Criteria andDanwDmBetween(String value1, String value2) {
            addCriterion("danw_dm between", value1, value2, "danwDm");
            return (Criteria) this;
        }

        public Criteria andDanwDmNotBetween(String value1, String value2) {
            addCriterion("danw_dm not between", value1, value2, "danwDm");
            return (Criteria) this;
        }

        public Criteria andPeijNoIsNull() {
            addCriterion("peij_no is null");
            return (Criteria) this;
        }

        public Criteria andPeijNoIsNotNull() {
            addCriterion("peij_no is not null");
            return (Criteria) this;
        }

        public Criteria andPeijNoEqualTo(String value) {
            addCriterion("peij_no =", value, "peijNo");
            return (Criteria) this;
        }

        public Criteria andPeijNoNotEqualTo(String value) {
            addCriterion("peij_no <>", value, "peijNo");
            return (Criteria) this;
        }

        public Criteria andPeijNoGreaterThan(String value) {
            addCriterion("peij_no >", value, "peijNo");
            return (Criteria) this;
        }

        public Criteria andPeijNoGreaterThanOrEqualTo(String value) {
            addCriterion("peij_no >=", value, "peijNo");
            return (Criteria) this;
        }

        public Criteria andPeijNoLessThan(String value) {
            addCriterion("peij_no <", value, "peijNo");
            return (Criteria) this;
        }

        public Criteria andPeijNoLessThanOrEqualTo(String value) {
            addCriterion("peij_no <=", value, "peijNo");
            return (Criteria) this;
        }

        public Criteria andPeijNoLike(String value) {
            addCriterion("peij_no like", value, "peijNo");
            return (Criteria) this;
        }

        public Criteria andPeijNoNotLike(String value) {
            addCriterion("peij_no not like", value, "peijNo");
            return (Criteria) this;
        }

        public Criteria andPeijNoIn(List<String> values) {
            addCriterion("peij_no in", values, "peijNo");
            return (Criteria) this;
        }

        public Criteria andPeijNoNotIn(List<String> values) {
            addCriterion("peij_no not in", values, "peijNo");
            return (Criteria) this;
        }

        public Criteria andPeijNoBetween(String value1, String value2) {
            addCriterion("peij_no between", value1, value2, "peijNo");
            return (Criteria) this;
        }

        public Criteria andPeijNoNotBetween(String value1, String value2) {
            addCriterion("peij_no not between", value1, value2, "peijNo");
            return (Criteria) this;
        }

        public Criteria andPeijKcIsNull() {
            addCriterion("peij_kc is null");
            return (Criteria) this;
        }

        public Criteria andPeijKcIsNotNull() {
            addCriterion("peij_kc is not null");
            return (Criteria) this;
        }

        public Criteria andPeijKcEqualTo(BigDecimal value) {
            addCriterion("peij_kc =", value, "peijKc");
            return (Criteria) this;
        }

        public Criteria andPeijKcNotEqualTo(BigDecimal value) {
            addCriterion("peij_kc <>", value, "peijKc");
            return (Criteria) this;
        }

        public Criteria andPeijKcGreaterThan(BigDecimal value) {
            addCriterion("peij_kc >", value, "peijKc");
            return (Criteria) this;
        }

        public Criteria andPeijKcGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("peij_kc >=", value, "peijKc");
            return (Criteria) this;
        }

        public Criteria andPeijKcLessThan(BigDecimal value) {
            addCriterion("peij_kc <", value, "peijKc");
            return (Criteria) this;
        }

        public Criteria andPeijKcLessThanOrEqualTo(BigDecimal value) {
            addCriterion("peij_kc <=", value, "peijKc");
            return (Criteria) this;
        }

        public Criteria andPeijKcIn(List<BigDecimal> values) {
            addCriterion("peij_kc in", values, "peijKc");
            return (Criteria) this;
        }

        public Criteria andPeijKcNotIn(List<BigDecimal> values) {
            addCriterion("peij_kc not in", values, "peijKc");
            return (Criteria) this;
        }

        public Criteria andPeijKcBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("peij_kc between", value1, value2, "peijKc");
            return (Criteria) this;
        }

        public Criteria andPeijKcNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("peij_kc not between", value1, value2, "peijKc");
            return (Criteria) this;
        }

        public Criteria andJiagJpIsNull() {
            addCriterion("jiag_jp is null");
            return (Criteria) this;
        }

        public Criteria andJiagJpIsNotNull() {
            addCriterion("jiag_jp is not null");
            return (Criteria) this;
        }

        public Criteria andJiagJpEqualTo(BigDecimal value) {
            addCriterion("jiag_jp =", value, "jiagJp");
            return (Criteria) this;
        }

        public Criteria andJiagJpNotEqualTo(BigDecimal value) {
            addCriterion("jiag_jp <>", value, "jiagJp");
            return (Criteria) this;
        }

        public Criteria andJiagJpGreaterThan(BigDecimal value) {
            addCriterion("jiag_jp >", value, "jiagJp");
            return (Criteria) this;
        }

        public Criteria andJiagJpGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("jiag_jp >=", value, "jiagJp");
            return (Criteria) this;
        }

        public Criteria andJiagJpLessThan(BigDecimal value) {
            addCriterion("jiag_jp <", value, "jiagJp");
            return (Criteria) this;
        }

        public Criteria andJiagJpLessThanOrEqualTo(BigDecimal value) {
            addCriterion("jiag_jp <=", value, "jiagJp");
            return (Criteria) this;
        }

        public Criteria andJiagJpIn(List<BigDecimal> values) {
            addCriterion("jiag_jp in", values, "jiagJp");
            return (Criteria) this;
        }

        public Criteria andJiagJpNotIn(List<BigDecimal> values) {
            addCriterion("jiag_jp not in", values, "jiagJp");
            return (Criteria) this;
        }

        public Criteria andJiagJpBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("jiag_jp between", value1, value2, "jiagJp");
            return (Criteria) this;
        }

        public Criteria andJiagJpNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("jiag_jp not between", value1, value2, "jiagJp");
            return (Criteria) this;
        }

        public Criteria andPeijJeIsNull() {
            addCriterion("peij_je is null");
            return (Criteria) this;
        }

        public Criteria andPeijJeIsNotNull() {
            addCriterion("peij_je is not null");
            return (Criteria) this;
        }

        public Criteria andPeijJeEqualTo(BigDecimal value) {
            addCriterion("peij_je =", value, "peijJe");
            return (Criteria) this;
        }

        public Criteria andPeijJeNotEqualTo(BigDecimal value) {
            addCriterion("peij_je <>", value, "peijJe");
            return (Criteria) this;
        }

        public Criteria andPeijJeGreaterThan(BigDecimal value) {
            addCriterion("peij_je >", value, "peijJe");
            return (Criteria) this;
        }

        public Criteria andPeijJeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("peij_je >=", value, "peijJe");
            return (Criteria) this;
        }

        public Criteria andPeijJeLessThan(BigDecimal value) {
            addCriterion("peij_je <", value, "peijJe");
            return (Criteria) this;
        }

        public Criteria andPeijJeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("peij_je <=", value, "peijJe");
            return (Criteria) this;
        }

        public Criteria andPeijJeIn(List<BigDecimal> values) {
            addCriterion("peij_je in", values, "peijJe");
            return (Criteria) this;
        }

        public Criteria andPeijJeNotIn(List<BigDecimal> values) {
            addCriterion("peij_je not in", values, "peijJe");
            return (Criteria) this;
        }

        public Criteria andPeijJeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("peij_je between", value1, value2, "peijJe");
            return (Criteria) this;
        }

        public Criteria andPeijJeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("peij_je not between", value1, value2, "peijJe");
            return (Criteria) this;
        }

        public Criteria andKucSxIsNull() {
            addCriterion("kuc_sx is null");
            return (Criteria) this;
        }

        public Criteria andKucSxIsNotNull() {
            addCriterion("kuc_sx is not null");
            return (Criteria) this;
        }

        public Criteria andKucSxEqualTo(BigDecimal value) {
            addCriterion("kuc_sx =", value, "kucSx");
            return (Criteria) this;
        }

        public Criteria andKucSxNotEqualTo(BigDecimal value) {
            addCriterion("kuc_sx <>", value, "kucSx");
            return (Criteria) this;
        }

        public Criteria andKucSxGreaterThan(BigDecimal value) {
            addCriterion("kuc_sx >", value, "kucSx");
            return (Criteria) this;
        }

        public Criteria andKucSxGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("kuc_sx >=", value, "kucSx");
            return (Criteria) this;
        }

        public Criteria andKucSxLessThan(BigDecimal value) {
            addCriterion("kuc_sx <", value, "kucSx");
            return (Criteria) this;
        }

        public Criteria andKucSxLessThanOrEqualTo(BigDecimal value) {
            addCriterion("kuc_sx <=", value, "kucSx");
            return (Criteria) this;
        }

        public Criteria andKucSxIn(List<BigDecimal> values) {
            addCriterion("kuc_sx in", values, "kucSx");
            return (Criteria) this;
        }

        public Criteria andKucSxNotIn(List<BigDecimal> values) {
            addCriterion("kuc_sx not in", values, "kucSx");
            return (Criteria) this;
        }

        public Criteria andKucSxBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("kuc_sx between", value1, value2, "kucSx");
            return (Criteria) this;
        }

        public Criteria andKucSxNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("kuc_sx not between", value1, value2, "kucSx");
            return (Criteria) this;
        }

        public Criteria andKucXxIsNull() {
            addCriterion("kuc_xx is null");
            return (Criteria) this;
        }

        public Criteria andKucXxIsNotNull() {
            addCriterion("kuc_xx is not null");
            return (Criteria) this;
        }

        public Criteria andKucXxEqualTo(BigDecimal value) {
            addCriterion("kuc_xx =", value, "kucXx");
            return (Criteria) this;
        }

        public Criteria andKucXxNotEqualTo(BigDecimal value) {
            addCriterion("kuc_xx <>", value, "kucXx");
            return (Criteria) this;
        }

        public Criteria andKucXxGreaterThan(BigDecimal value) {
            addCriterion("kuc_xx >", value, "kucXx");
            return (Criteria) this;
        }

        public Criteria andKucXxGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("kuc_xx >=", value, "kucXx");
            return (Criteria) this;
        }

        public Criteria andKucXxLessThan(BigDecimal value) {
            addCriterion("kuc_xx <", value, "kucXx");
            return (Criteria) this;
        }

        public Criteria andKucXxLessThanOrEqualTo(BigDecimal value) {
            addCriterion("kuc_xx <=", value, "kucXx");
            return (Criteria) this;
        }

        public Criteria andKucXxIn(List<BigDecimal> values) {
            addCriterion("kuc_xx in", values, "kucXx");
            return (Criteria) this;
        }

        public Criteria andKucXxNotIn(List<BigDecimal> values) {
            addCriterion("kuc_xx not in", values, "kucXx");
            return (Criteria) this;
        }

        public Criteria andKucXxBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("kuc_xx between", value1, value2, "kucXx");
            return (Criteria) this;
        }

        public Criteria andKucXxNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("kuc_xx not between", value1, value2, "kucXx");
            return (Criteria) this;
        }

        public Criteria andKucDhIsNull() {
            addCriterion("kuc_dh is null");
            return (Criteria) this;
        }

        public Criteria andKucDhIsNotNull() {
            addCriterion("kuc_dh is not null");
            return (Criteria) this;
        }

        public Criteria andKucDhEqualTo(BigDecimal value) {
            addCriterion("kuc_dh =", value, "kucDh");
            return (Criteria) this;
        }

        public Criteria andKucDhNotEqualTo(BigDecimal value) {
            addCriterion("kuc_dh <>", value, "kucDh");
            return (Criteria) this;
        }

        public Criteria andKucDhGreaterThan(BigDecimal value) {
            addCriterion("kuc_dh >", value, "kucDh");
            return (Criteria) this;
        }

        public Criteria andKucDhGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("kuc_dh >=", value, "kucDh");
            return (Criteria) this;
        }

        public Criteria andKucDhLessThan(BigDecimal value) {
            addCriterion("kuc_dh <", value, "kucDh");
            return (Criteria) this;
        }

        public Criteria andKucDhLessThanOrEqualTo(BigDecimal value) {
            addCriterion("kuc_dh <=", value, "kucDh");
            return (Criteria) this;
        }

        public Criteria andKucDhIn(List<BigDecimal> values) {
            addCriterion("kuc_dh in", values, "kucDh");
            return (Criteria) this;
        }

        public Criteria andKucDhNotIn(List<BigDecimal> values) {
            addCriterion("kuc_dh not in", values, "kucDh");
            return (Criteria) this;
        }

        public Criteria andKucDhBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("kuc_dh between", value1, value2, "kucDh");
            return (Criteria) this;
        }

        public Criteria andKucDhNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("kuc_dh not between", value1, value2, "kucDh");
            return (Criteria) this;
        }

        public Criteria andKucHwIsNull() {
            addCriterion("kuc_hw is null");
            return (Criteria) this;
        }

        public Criteria andKucHwIsNotNull() {
            addCriterion("kuc_hw is not null");
            return (Criteria) this;
        }

        public Criteria andKucHwEqualTo(String value) {
            addCriterion("kuc_hw =", value, "kucHw");
            return (Criteria) this;
        }

        public Criteria andKucHwNotEqualTo(String value) {
            addCriterion("kuc_hw <>", value, "kucHw");
            return (Criteria) this;
        }

        public Criteria andKucHwGreaterThan(String value) {
            addCriterion("kuc_hw >", value, "kucHw");
            return (Criteria) this;
        }

        public Criteria andKucHwGreaterThanOrEqualTo(String value) {
            addCriterion("kuc_hw >=", value, "kucHw");
            return (Criteria) this;
        }

        public Criteria andKucHwLessThan(String value) {
            addCriterion("kuc_hw <", value, "kucHw");
            return (Criteria) this;
        }

        public Criteria andKucHwLessThanOrEqualTo(String value) {
            addCriterion("kuc_hw <=", value, "kucHw");
            return (Criteria) this;
        }

        public Criteria andKucHwLike(String value) {
            addCriterion("kuc_hw like", value, "kucHw");
            return (Criteria) this;
        }

        public Criteria andKucHwNotLike(String value) {
            addCriterion("kuc_hw not like", value, "kucHw");
            return (Criteria) this;
        }

        public Criteria andKucHwIn(List<String> values) {
            addCriterion("kuc_hw in", values, "kucHw");
            return (Criteria) this;
        }

        public Criteria andKucHwNotIn(List<String> values) {
            addCriterion("kuc_hw not in", values, "kucHw");
            return (Criteria) this;
        }

        public Criteria andKucHwBetween(String value1, String value2) {
            addCriterion("kuc_hw between", value1, value2, "kucHw");
            return (Criteria) this;
        }

        public Criteria andKucHwNotBetween(String value1, String value2) {
            addCriterion("kuc_hw not between", value1, value2, "kucHw");
            return (Criteria) this;
        }

        public Criteria andXiaoSlIsNull() {
            addCriterion("xiao_sl is null");
            return (Criteria) this;
        }

        public Criteria andXiaoSlIsNotNull() {
            addCriterion("xiao_sl is not null");
            return (Criteria) this;
        }

        public Criteria andXiaoSlEqualTo(BigDecimal value) {
            addCriterion("xiao_sl =", value, "xiaoSl");
            return (Criteria) this;
        }

        public Criteria andXiaoSlNotEqualTo(BigDecimal value) {
            addCriterion("xiao_sl <>", value, "xiaoSl");
            return (Criteria) this;
        }

        public Criteria andXiaoSlGreaterThan(BigDecimal value) {
            addCriterion("xiao_sl >", value, "xiaoSl");
            return (Criteria) this;
        }

        public Criteria andXiaoSlGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("xiao_sl >=", value, "xiaoSl");
            return (Criteria) this;
        }

        public Criteria andXiaoSlLessThan(BigDecimal value) {
            addCriterion("xiao_sl <", value, "xiaoSl");
            return (Criteria) this;
        }

        public Criteria andXiaoSlLessThanOrEqualTo(BigDecimal value) {
            addCriterion("xiao_sl <=", value, "xiaoSl");
            return (Criteria) this;
        }

        public Criteria andXiaoSlIn(List<BigDecimal> values) {
            addCriterion("xiao_sl in", values, "xiaoSl");
            return (Criteria) this;
        }

        public Criteria andXiaoSlNotIn(List<BigDecimal> values) {
            addCriterion("xiao_sl not in", values, "xiaoSl");
            return (Criteria) this;
        }

        public Criteria andXiaoSlBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("xiao_sl between", value1, value2, "xiaoSl");
            return (Criteria) this;
        }

        public Criteria andXiaoSlNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("xiao_sl not between", value1, value2, "xiaoSl");
            return (Criteria) this;
        }

        public Criteria andJinhSlIsNull() {
            addCriterion("jinh_sl is null");
            return (Criteria) this;
        }

        public Criteria andJinhSlIsNotNull() {
            addCriterion("jinh_sl is not null");
            return (Criteria) this;
        }

        public Criteria andJinhSlEqualTo(BigDecimal value) {
            addCriterion("jinh_sl =", value, "jinhSl");
            return (Criteria) this;
        }

        public Criteria andJinhSlNotEqualTo(BigDecimal value) {
            addCriterion("jinh_sl <>", value, "jinhSl");
            return (Criteria) this;
        }

        public Criteria andJinhSlGreaterThan(BigDecimal value) {
            addCriterion("jinh_sl >", value, "jinhSl");
            return (Criteria) this;
        }

        public Criteria andJinhSlGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("jinh_sl >=", value, "jinhSl");
            return (Criteria) this;
        }

        public Criteria andJinhSlLessThan(BigDecimal value) {
            addCriterion("jinh_sl <", value, "jinhSl");
            return (Criteria) this;
        }

        public Criteria andJinhSlLessThanOrEqualTo(BigDecimal value) {
            addCriterion("jinh_sl <=", value, "jinhSl");
            return (Criteria) this;
        }

        public Criteria andJinhSlIn(List<BigDecimal> values) {
            addCriterion("jinh_sl in", values, "jinhSl");
            return (Criteria) this;
        }

        public Criteria andJinhSlNotIn(List<BigDecimal> values) {
            addCriterion("jinh_sl not in", values, "jinhSl");
            return (Criteria) this;
        }

        public Criteria andJinhSlBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("jinh_sl between", value1, value2, "jinhSl");
            return (Criteria) this;
        }

        public Criteria andJinhSlNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("jinh_sl not between", value1, value2, "jinhSl");
            return (Criteria) this;
        }

        public Criteria andXiaothSlIsNull() {
            addCriterion("xiaoth_sl is null");
            return (Criteria) this;
        }

        public Criteria andXiaothSlIsNotNull() {
            addCriterion("xiaoth_sl is not null");
            return (Criteria) this;
        }

        public Criteria andXiaothSlEqualTo(BigDecimal value) {
            addCriterion("xiaoth_sl =", value, "xiaothSl");
            return (Criteria) this;
        }

        public Criteria andXiaothSlNotEqualTo(BigDecimal value) {
            addCriterion("xiaoth_sl <>", value, "xiaothSl");
            return (Criteria) this;
        }

        public Criteria andXiaothSlGreaterThan(BigDecimal value) {
            addCriterion("xiaoth_sl >", value, "xiaothSl");
            return (Criteria) this;
        }

        public Criteria andXiaothSlGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("xiaoth_sl >=", value, "xiaothSl");
            return (Criteria) this;
        }

        public Criteria andXiaothSlLessThan(BigDecimal value) {
            addCriterion("xiaoth_sl <", value, "xiaothSl");
            return (Criteria) this;
        }

        public Criteria andXiaothSlLessThanOrEqualTo(BigDecimal value) {
            addCriterion("xiaoth_sl <=", value, "xiaothSl");
            return (Criteria) this;
        }

        public Criteria andXiaothSlIn(List<BigDecimal> values) {
            addCriterion("xiaoth_sl in", values, "xiaothSl");
            return (Criteria) this;
        }

        public Criteria andXiaothSlNotIn(List<BigDecimal> values) {
            addCriterion("xiaoth_sl not in", values, "xiaothSl");
            return (Criteria) this;
        }

        public Criteria andXiaothSlBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("xiaoth_sl between", value1, value2, "xiaothSl");
            return (Criteria) this;
        }

        public Criteria andXiaothSlNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("xiaoth_sl not between", value1, value2, "xiaothSl");
            return (Criteria) this;
        }

        public Criteria andJinhthSlIsNull() {
            addCriterion("jinhth_sl is null");
            return (Criteria) this;
        }

        public Criteria andJinhthSlIsNotNull() {
            addCriterion("jinhth_sl is not null");
            return (Criteria) this;
        }

        public Criteria andJinhthSlEqualTo(BigDecimal value) {
            addCriterion("jinhth_sl =", value, "jinhthSl");
            return (Criteria) this;
        }

        public Criteria andJinhthSlNotEqualTo(BigDecimal value) {
            addCriterion("jinhth_sl <>", value, "jinhthSl");
            return (Criteria) this;
        }

        public Criteria andJinhthSlGreaterThan(BigDecimal value) {
            addCriterion("jinhth_sl >", value, "jinhthSl");
            return (Criteria) this;
        }

        public Criteria andJinhthSlGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("jinhth_sl >=", value, "jinhthSl");
            return (Criteria) this;
        }

        public Criteria andJinhthSlLessThan(BigDecimal value) {
            addCriterion("jinhth_sl <", value, "jinhthSl");
            return (Criteria) this;
        }

        public Criteria andJinhthSlLessThanOrEqualTo(BigDecimal value) {
            addCriterion("jinhth_sl <=", value, "jinhthSl");
            return (Criteria) this;
        }

        public Criteria andJinhthSlIn(List<BigDecimal> values) {
            addCriterion("jinhth_sl in", values, "jinhthSl");
            return (Criteria) this;
        }

        public Criteria andJinhthSlNotIn(List<BigDecimal> values) {
            addCriterion("jinhth_sl not in", values, "jinhthSl");
            return (Criteria) this;
        }

        public Criteria andJinhthSlBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("jinhth_sl between", value1, value2, "jinhthSl");
            return (Criteria) this;
        }

        public Criteria andJinhthSlNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("jinhth_sl not between", value1, value2, "jinhthSl");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table kucshp_fl
     *
     * @mbggenerated do_not_delete_during_merge Fri Apr 25 10:12:29 CST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table kucshp_fl
     *
     * @mbggenerated Fri Apr 25 10:12:29 CST 2014
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}