package com.xym.bossed.db.mybatis.gys.leibie;

import com.xym.bossed.db.mybatis.gys.leibie.GongYSLeibie;
import com.xym.bossed.db.mybatis.gys.leibie.GongYSLeibieExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GongYSLeibieMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_gongyshlb
     *
     * @mbggenerated Mon Jul 15 16:35:50 CST 2013
     */
    int countByExample(GongYSLeibieExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_gongyshlb
     *
     * @mbggenerated Mon Jul 15 16:35:50 CST 2013
     */
    int deleteByExample(GongYSLeibieExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_gongyshlb
     *
     * @mbggenerated Mon Jul 15 16:35:50 CST 2013
     */
    int deleteByPrimaryKey(String kehulbDm);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_gongyshlb
     *
     * @mbggenerated Mon Jul 15 16:35:50 CST 2013
     */
    int insert(GongYSLeibie record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_gongyshlb
     *
     * @mbggenerated Mon Jul 15 16:35:50 CST 2013
     */
    int insertSelective(GongYSLeibie record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_gongyshlb
     *
     * @mbggenerated Mon Jul 15 16:35:50 CST 2013
     */
    List<GongYSLeibie> selectByExample(GongYSLeibieExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_gongyshlb
     *
     * @mbggenerated Mon Jul 15 16:35:50 CST 2013
     */
    GongYSLeibie selectByPrimaryKey(String kehulbDm);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_gongyshlb
     *
     * @mbggenerated Mon Jul 15 16:35:50 CST 2013
     */
    int updateByExampleSelective(@Param("record") GongYSLeibie record, @Param("example") GongYSLeibieExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_gongyshlb
     *
     * @mbggenerated Mon Jul 15 16:35:50 CST 2013
     */
    int updateByExample(@Param("record") GongYSLeibie record, @Param("example") GongYSLeibieExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_gongyshlb
     *
     * @mbggenerated Mon Jul 15 16:35:50 CST 2013
     */
    int updateByPrimaryKeySelective(GongYSLeibie record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_gongyshlb
     *
     * @mbggenerated Mon Jul 15 16:35:50 CST 2013
     */
    int updateByPrimaryKey(GongYSLeibie record);
}