package com.xym.bossed.db.mybatis.parts;

import com.xym.bossed.db.mybatis.parts.Parts;
import com.xym.bossed.db.mybatis.parts.PartsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PartsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kucshp_info
     *
     * @mbggenerated Wed Apr 23 18:32:26 CST 2014
     */
    int countByExample(PartsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kucshp_info
     *
     * @mbggenerated Wed Apr 23 18:32:26 CST 2014
     */
    int deleteByExample(PartsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kucshp_info
     *
     * @mbggenerated Wed Apr 23 18:32:26 CST 2014
     */
    int deleteByPrimaryKey(String peijNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kucshp_info
     *
     * @mbggenerated Wed Apr 23 18:32:26 CST 2014
     */
    int insert(Parts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kucshp_info
     *
     * @mbggenerated Wed Apr 23 18:32:26 CST 2014
     */
    int insertSelective(Parts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kucshp_info
     *
     * @mbggenerated Wed Apr 23 18:32:26 CST 2014
     */
    List<Parts> selectByExample(PartsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kucshp_info
     *
     * @mbggenerated Wed Apr 23 18:32:26 CST 2014
     */
    Parts selectByPrimaryKey(String peijNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kucshp_info
     *
     * @mbggenerated Wed Apr 23 18:32:26 CST 2014
     */
    int updateByExampleSelective(@Param("record") Parts record, @Param("example") PartsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kucshp_info
     *
     * @mbggenerated Wed Apr 23 18:32:26 CST 2014
     */
    int updateByExample(@Param("record") Parts record, @Param("example") PartsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kucshp_info
     *
     * @mbggenerated Wed Apr 23 18:32:26 CST 2014
     */
    int updateByPrimaryKeySelective(Parts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kucshp_info
     *
     * @mbggenerated Wed Apr 23 18:32:26 CST 2014
     */
    int updateByPrimaryKey(Parts record);
}