package com.xym.bossed.db.mybatis.jiesuan;

import java.io.Serializable;

public class JieSuan implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = 3665728979570941886L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sm_jiesuan.jiesuan_mc
     *
     * @mbggenerated Tue Apr 08 11:36:11 CST 2014
     */
    private String jiesuanMc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sm_jiesuan.reco_no
     *
     * @mbggenerated Tue Apr 08 11:36:11 CST 2014
     */
    private Long recoNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_jiesuan.jiesuan_mc
     *
     * @return the value of sm_jiesuan.jiesuan_mc
     *
     * @mbggenerated Tue Apr 08 11:36:11 CST 2014
     */
    public String getJiesuanMc() {
        return jiesuanMc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_jiesuan.jiesuan_mc
     *
     * @param jiesuanMc the value for sm_jiesuan.jiesuan_mc
     *
     * @mbggenerated Tue Apr 08 11:36:11 CST 2014
     */
    public void setJiesuanMc(String jiesuanMc) {
        this.jiesuanMc = jiesuanMc == null ? null : jiesuanMc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sm_jiesuan.reco_no
     *
     * @return the value of sm_jiesuan.reco_no
     *
     * @mbggenerated Tue Apr 08 11:36:11 CST 2014
     */
    public Long getRecoNo() {
        return recoNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sm_jiesuan.reco_no
     *
     * @param recoNo the value for sm_jiesuan.reco_no
     *
     * @mbggenerated Tue Apr 08 11:36:11 CST 2014
     */
    public void setRecoNo(Long recoNo) {
        this.recoNo = recoNo;
    }
}