package com.xym.bossed.db.mybatis.danwei;

import com.xym.bossed.db.mybatis.danwei.DanWei;
import com.xym.bossed.db.mybatis.danwei.DanWeiExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DanWeiMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_danwlc
     *
     * @mbggenerated Mon Apr 21 17:52:08 CST 2014
     */
    int countByExample(DanWeiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_danwlc
     *
     * @mbggenerated Mon Apr 21 17:52:08 CST 2014
     */
    int deleteByExample(DanWeiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_danwlc
     *
     * @mbggenerated Mon Apr 21 17:52:08 CST 2014
     */
    int deleteByPrimaryKey(String lcMc);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_danwlc
     *
     * @mbggenerated Mon Apr 21 17:52:08 CST 2014
     */
    int insert(DanWei record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_danwlc
     *
     * @mbggenerated Mon Apr 21 17:52:08 CST 2014
     */
    int insertSelective(DanWei record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_danwlc
     *
     * @mbggenerated Mon Apr 21 17:52:08 CST 2014
     */
    List<DanWei> selectByExample(DanWeiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_danwlc
     *
     * @mbggenerated Mon Apr 21 17:52:08 CST 2014
     */
    DanWei selectByPrimaryKey(String lcMc);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_danwlc
     *
     * @mbggenerated Mon Apr 21 17:52:08 CST 2014
     */
    int updateByExampleSelective(@Param("record") DanWei record, @Param("example") DanWeiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_danwlc
     *
     * @mbggenerated Mon Apr 21 17:52:08 CST 2014
     */
    int updateByExample(@Param("record") DanWei record, @Param("example") DanWeiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_danwlc
     *
     * @mbggenerated Mon Apr 21 17:52:08 CST 2014
     */
    int updateByPrimaryKeySelective(DanWei record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_danwlc
     *
     * @mbggenerated Mon Apr 21 17:52:08 CST 2014
     */
    int updateByPrimaryKey(DanWei record);
}