package com.xym.bossed.db.mybatis.parts.category;

import com.xym.bossed.db.mybatis.parts.category.PartsCategory;
import com.xym.bossed.db.mybatis.parts.category.PartsCategoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PartsCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_peijlb
     *
     * @mbggenerated Wed Apr 09 06:29:40 CST 2014
     */
    int countByExample(PartsCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_peijlb
     *
     * @mbggenerated Wed Apr 09 06:29:40 CST 2014
     */
    int deleteByExample(PartsCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_peijlb
     *
     * @mbggenerated Wed Apr 09 06:29:40 CST 2014
     */
    int deleteByPrimaryKey(String peijlbDm);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_peijlb
     *
     * @mbggenerated Wed Apr 09 06:29:40 CST 2014
     */
    int insert(PartsCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_peijlb
     *
     * @mbggenerated Wed Apr 09 06:29:40 CST 2014
     */
    int insertSelective(PartsCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_peijlb
     *
     * @mbggenerated Wed Apr 09 06:29:40 CST 2014
     */
    List<PartsCategory> selectByExample(PartsCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_peijlb
     *
     * @mbggenerated Wed Apr 09 06:29:40 CST 2014
     */
    PartsCategory selectByPrimaryKey(String peijlbDm);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_peijlb
     *
     * @mbggenerated Wed Apr 09 06:29:40 CST 2014
     */
    int updateByExampleSelective(@Param("record") PartsCategory record, @Param("example") PartsCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_peijlb
     *
     * @mbggenerated Wed Apr 09 06:29:40 CST 2014
     */
    int updateByExample(@Param("record") PartsCategory record, @Param("example") PartsCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_peijlb
     *
     * @mbggenerated Wed Apr 09 06:29:40 CST 2014
     */
    int updateByPrimaryKeySelective(PartsCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_peijlb
     *
     * @mbggenerated Wed Apr 09 06:29:40 CST 2014
     */
    int updateByPrimaryKey(PartsCategory record);
}