package com.xym.bossed.db.mybatis.parts;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class PartsExample {

	protected List<Criteria> andedCriteria;

	public List<Criteria> getAndedCriteria() {
		return andedCriteria;
	}

	public Criteria and() {
		Criteria criteria = createCriteriaInternal();
		andedCriteria.add(criteria);
		return criteria;
	}

	/**
	 * generated by mybatis genarator
	 */

	protected String orderByClause;

	protected boolean distinct;

	protected List<Criteria> oredCriteria;

	public PartsExample() {
		oredCriteria = new ArrayList<Criteria>();
		andedCriteria = new ArrayList<Criteria>();
	}

	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	public String getOrderByClause() {
		return orderByClause;
	}

	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	public boolean isDistinct() {
		return distinct;
	}

	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	public void clear() {
		oredCriteria.clear();
		andedCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andPeijNoIsNull() {
			addCriterion("peij_no is null");
			return (Criteria) this;
		}

		public Criteria andPeijNoIsNotNull() {
			addCriterion("peij_no is not null");
			return (Criteria) this;
		}

		public Criteria andPeijNoEqualTo(String value) {
			addCriterion("peij_no =", value, "peijNo");
			return (Criteria) this;
		}

		public Criteria andPeijNoNotEqualTo(String value) {
			addCriterion("peij_no <>", value, "peijNo");
			return (Criteria) this;
		}

		public Criteria andPeijNoGreaterThan(String value) {
			addCriterion("peij_no >", value, "peijNo");
			return (Criteria) this;
		}

		public Criteria andPeijNoGreaterThanOrEqualTo(String value) {
			addCriterion("peij_no >=", value, "peijNo");
			return (Criteria) this;
		}

		public Criteria andPeijNoLessThan(String value) {
			addCriterion("peij_no <", value, "peijNo");
			return (Criteria) this;
		}

		public Criteria andPeijNoLessThanOrEqualTo(String value) {
			addCriterion("peij_no <=", value, "peijNo");
			return (Criteria) this;
		}

		public Criteria andPeijNoLike(String value) {
			addCriterion("peij_no like", value, "peijNo");
			return (Criteria) this;
		}

		public Criteria andPeijNoNotLike(String value) {
			addCriterion("peij_no not like", value, "peijNo");
			return (Criteria) this;
		}

		public Criteria andPeijNoIn(List<String> values) {
			addCriterion("peij_no in", values, "peijNo");
			return (Criteria) this;
		}

		public Criteria andPeijNoNotIn(List<String> values) {
			addCriterion("peij_no not in", values, "peijNo");
			return (Criteria) this;
		}

		public Criteria andPeijNoBetween(String value1, String value2) {
			addCriterion("peij_no between", value1, value2, "peijNo");
			return (Criteria) this;
		}

		public Criteria andPeijNoNotBetween(String value1, String value2) {
			addCriterion("peij_no not between", value1, value2, "peijNo");
			return (Criteria) this;
		}

		public Criteria andRecoNo1IsNull() {
			addCriterion("reco_no1 is null");
			return (Criteria) this;
		}

		public Criteria andRecoNo1IsNotNull() {
			addCriterion("reco_no1 is not null");
			return (Criteria) this;
		}

		public Criteria andRecoNo1EqualTo(Long value) {
			addCriterion("reco_no1 =", value, "recoNo1");
			return (Criteria) this;
		}

		public Criteria andRecoNo1NotEqualTo(Long value) {
			addCriterion("reco_no1 <>", value, "recoNo1");
			return (Criteria) this;
		}

		public Criteria andRecoNo1GreaterThan(Long value) {
			addCriterion("reco_no1 >", value, "recoNo1");
			return (Criteria) this;
		}

		public Criteria andRecoNo1GreaterThanOrEqualTo(Long value) {
			addCriterion("reco_no1 >=", value, "recoNo1");
			return (Criteria) this;
		}

		public Criteria andRecoNo1LessThan(Long value) {
			addCriterion("reco_no1 <", value, "recoNo1");
			return (Criteria) this;
		}

		public Criteria andRecoNo1LessThanOrEqualTo(Long value) {
			addCriterion("reco_no1 <=", value, "recoNo1");
			return (Criteria) this;
		}

		public Criteria andRecoNo1In(List<Long> values) {
			addCriterion("reco_no1 in", values, "recoNo1");
			return (Criteria) this;
		}

		public Criteria andRecoNo1NotIn(List<Long> values) {
			addCriterion("reco_no1 not in", values, "recoNo1");
			return (Criteria) this;
		}

		public Criteria andRecoNo1Between(Long value1, Long value2) {
			addCriterion("reco_no1 between", value1, value2, "recoNo1");
			return (Criteria) this;
		}

		public Criteria andRecoNo1NotBetween(Long value1, Long value2) {
			addCriterion("reco_no1 not between", value1, value2, "recoNo1");
			return (Criteria) this;
		}

		public Criteria andPeijThIsNull() {
			addCriterion("peij_th is null");
			return (Criteria) this;
		}

		public Criteria andPeijThIsNotNull() {
			addCriterion("peij_th is not null");
			return (Criteria) this;
		}

		public Criteria andPeijThEqualTo(String value) {
			addCriterion("peij_th =", value, "peijTh");
			return (Criteria) this;
		}

		public Criteria andPeijThNotEqualTo(String value) {
			addCriterion("peij_th <>", value, "peijTh");
			return (Criteria) this;
		}

		public Criteria andPeijThGreaterThan(String value) {
			addCriterion("peij_th >", value, "peijTh");
			return (Criteria) this;
		}

		public Criteria andPeijThGreaterThanOrEqualTo(String value) {
			addCriterion("peij_th >=", value, "peijTh");
			return (Criteria) this;
		}

		public Criteria andPeijThLessThan(String value) {
			addCriterion("peij_th <", value, "peijTh");
			return (Criteria) this;
		}

		public Criteria andPeijThLessThanOrEqualTo(String value) {
			addCriterion("peij_th <=", value, "peijTh");
			return (Criteria) this;
		}

		public Criteria andPeijThLike(String value) {
			addCriterion("peij_th like", value, "peijTh");
			return (Criteria) this;
		}

		public Criteria andPeijThNotLike(String value) {
			addCriterion("peij_th not like", value, "peijTh");
			return (Criteria) this;
		}

		public Criteria andPeijThIn(List<String> values) {
			addCriterion("peij_th in", values, "peijTh");
			return (Criteria) this;
		}

		public Criteria andPeijThNotIn(List<String> values) {
			addCriterion("peij_th not in", values, "peijTh");
			return (Criteria) this;
		}

		public Criteria andPeijThBetween(String value1, String value2) {
			addCriterion("peij_th between", value1, value2, "peijTh");
			return (Criteria) this;
		}

		public Criteria andPeijThNotBetween(String value1, String value2) {
			addCriterion("peij_th not between", value1, value2, "peijTh");
			return (Criteria) this;
		}

		public Criteria andPeijMcIsNull() {
			addCriterion("peij_mc is null");
			return (Criteria) this;
		}

		public Criteria andPeijMcIsNotNull() {
			addCriterion("peij_mc is not null");
			return (Criteria) this;
		}

		public Criteria andPeijMcEqualTo(String value) {
			addCriterion("peij_mc =", value, "peijMc");
			return (Criteria) this;
		}

		public Criteria andPeijMcNotEqualTo(String value) {
			addCriterion("peij_mc <>", value, "peijMc");
			return (Criteria) this;
		}

		public Criteria andPeijMcGreaterThan(String value) {
			addCriterion("peij_mc >", value, "peijMc");
			return (Criteria) this;
		}

		public Criteria andPeijMcGreaterThanOrEqualTo(String value) {
			addCriterion("peij_mc >=", value, "peijMc");
			return (Criteria) this;
		}

		public Criteria andPeijMcLessThan(String value) {
			addCriterion("peij_mc <", value, "peijMc");
			return (Criteria) this;
		}

		public Criteria andPeijMcLessThanOrEqualTo(String value) {
			addCriterion("peij_mc <=", value, "peijMc");
			return (Criteria) this;
		}

		public Criteria andPeijMcLike(String value) {
			addCriterion("peij_mc like", value, "peijMc");
			return (Criteria) this;
		}

		public Criteria andPeijMcNotLike(String value) {
			addCriterion("peij_mc not like", value, "peijMc");
			return (Criteria) this;
		}

		public Criteria andPeijMcIn(List<String> values) {
			addCriterion("peij_mc in", values, "peijMc");
			return (Criteria) this;
		}

		public Criteria andPeijMcNotIn(List<String> values) {
			addCriterion("peij_mc not in", values, "peijMc");
			return (Criteria) this;
		}

		public Criteria andPeijMcBetween(String value1, String value2) {
			addCriterion("peij_mc between", value1, value2, "peijMc");
			return (Criteria) this;
		}

		public Criteria andPeijMcNotBetween(String value1, String value2) {
			addCriterion("peij_mc not between", value1, value2, "peijMc");
			return (Criteria) this;
		}

		public Criteria andPeijEnIsNull() {
			addCriterion("peij_en is null");
			return (Criteria) this;
		}

		public Criteria andPeijEnIsNotNull() {
			addCriterion("peij_en is not null");
			return (Criteria) this;
		}

		public Criteria andPeijEnEqualTo(String value) {
			addCriterion("peij_en =", value, "peijEn");
			return (Criteria) this;
		}

		public Criteria andPeijEnNotEqualTo(String value) {
			addCriterion("peij_en <>", value, "peijEn");
			return (Criteria) this;
		}

		public Criteria andPeijEnGreaterThan(String value) {
			addCriterion("peij_en >", value, "peijEn");
			return (Criteria) this;
		}

		public Criteria andPeijEnGreaterThanOrEqualTo(String value) {
			addCriterion("peij_en >=", value, "peijEn");
			return (Criteria) this;
		}

		public Criteria andPeijEnLessThan(String value) {
			addCriterion("peij_en <", value, "peijEn");
			return (Criteria) this;
		}

		public Criteria andPeijEnLessThanOrEqualTo(String value) {
			addCriterion("peij_en <=", value, "peijEn");
			return (Criteria) this;
		}

		public Criteria andPeijEnLike(String value) {
			addCriterion("peij_en like", value, "peijEn");
			return (Criteria) this;
		}

		public Criteria andPeijEnNotLike(String value) {
			addCriterion("peij_en not like", value, "peijEn");
			return (Criteria) this;
		}

		public Criteria andPeijEnIn(List<String> values) {
			addCriterion("peij_en in", values, "peijEn");
			return (Criteria) this;
		}

		public Criteria andPeijEnNotIn(List<String> values) {
			addCriterion("peij_en not in", values, "peijEn");
			return (Criteria) this;
		}

		public Criteria andPeijEnBetween(String value1, String value2) {
			addCriterion("peij_en between", value1, value2, "peijEn");
			return (Criteria) this;
		}

		public Criteria andPeijEnNotBetween(String value1, String value2) {
			addCriterion("peij_en not between", value1, value2, "peijEn");
			return (Criteria) this;
		}

		public Criteria andPeijlbMcIsNull() {
			addCriterion("peijlb_mc is null");
			return (Criteria) this;
		}

		public Criteria andPeijlbMcIsNotNull() {
			addCriterion("peijlb_mc is not null");
			return (Criteria) this;
		}

		public Criteria andPeijlbMcEqualTo(String value) {
			addCriterion("peijlb_mc =", value, "peijlbMc");
			return (Criteria) this;
		}

		public Criteria andPeijlbMcNotEqualTo(String value) {
			addCriterion("peijlb_mc <>", value, "peijlbMc");
			return (Criteria) this;
		}

		public Criteria andPeijlbMcGreaterThan(String value) {
			addCriterion("peijlb_mc >", value, "peijlbMc");
			return (Criteria) this;
		}

		public Criteria andPeijlbMcGreaterThanOrEqualTo(String value) {
			addCriterion("peijlb_mc >=", value, "peijlbMc");
			return (Criteria) this;
		}

		public Criteria andPeijlbMcLessThan(String value) {
			addCriterion("peijlb_mc <", value, "peijlbMc");
			return (Criteria) this;
		}

		public Criteria andPeijlbMcLessThanOrEqualTo(String value) {
			addCriterion("peijlb_mc <=", value, "peijlbMc");
			return (Criteria) this;
		}

		public Criteria andPeijlbMcLike(String value) {
			addCriterion("peijlb_mc like", value, "peijlbMc");
			return (Criteria) this;
		}

		public Criteria andPeijlbMcNotLike(String value) {
			addCriterion("peijlb_mc not like", value, "peijlbMc");
			return (Criteria) this;
		}

		public Criteria andPeijlbMcIn(List<String> values) {
			addCriterion("peijlb_mc in", values, "peijlbMc");
			return (Criteria) this;
		}

		public Criteria andPeijlbMcNotIn(List<String> values) {
			addCriterion("peijlb_mc not in", values, "peijlbMc");
			return (Criteria) this;
		}

		public Criteria andPeijlbMcBetween(String value1, String value2) {
			addCriterion("peijlb_mc between", value1, value2, "peijlbMc");
			return (Criteria) this;
		}

		public Criteria andPeijlbMcNotBetween(String value1, String value2) {
			addCriterion("peijlb_mc not between", value1, value2, "peijlbMc");
			return (Criteria) this;
		}

		public Criteria andPeijlbDmIsNull() {
			addCriterion("peijlb_dm is null");
			return (Criteria) this;
		}

		public Criteria andPeijlbDmIsNotNull() {
			addCriterion("peijlb_dm is not null");
			return (Criteria) this;
		}

		public Criteria andPeijlbDmEqualTo(String value) {
			addCriterion("peijlb_dm =", value, "peijlbDm");
			return (Criteria) this;
		}

		public Criteria andPeijlbDmNotEqualTo(String value) {
			addCriterion("peijlb_dm <>", value, "peijlbDm");
			return (Criteria) this;
		}

		public Criteria andPeijlbDmGreaterThan(String value) {
			addCriterion("peijlb_dm >", value, "peijlbDm");
			return (Criteria) this;
		}

		public Criteria andPeijlbDmGreaterThanOrEqualTo(String value) {
			addCriterion("peijlb_dm >=", value, "peijlbDm");
			return (Criteria) this;
		}

		public Criteria andPeijlbDmLessThan(String value) {
			addCriterion("peijlb_dm <", value, "peijlbDm");
			return (Criteria) this;
		}

		public Criteria andPeijlbDmLessThanOrEqualTo(String value) {
			addCriterion("peijlb_dm <=", value, "peijlbDm");
			return (Criteria) this;
		}

		public Criteria andPeijlbDmLike(String value) {
			addCriterion("peijlb_dm like", value, "peijlbDm");
			return (Criteria) this;
		}

		public Criteria andPeijlbDmNotLike(String value) {
			addCriterion("peijlb_dm not like", value, "peijlbDm");
			return (Criteria) this;
		}

		public Criteria andPeijlbDmIn(List<String> values) {
			addCriterion("peijlb_dm in", values, "peijlbDm");
			return (Criteria) this;
		}

		public Criteria andPeijlbDmNotIn(List<String> values) {
			addCriterion("peijlb_dm not in", values, "peijlbDm");
			return (Criteria) this;
		}

		public Criteria andPeijlbDmBetween(String value1, String value2) {
			addCriterion("peijlb_dm between", value1, value2, "peijlbDm");
			return (Criteria) this;
		}

		public Criteria andPeijlbDmNotBetween(String value1, String value2) {
			addCriterion("peijlb_dm not between", value1, value2, "peijlbDm");
			return (Criteria) this;
		}

		public Criteria andPeijPyIsNull() {
			addCriterion("peij_py is null");
			return (Criteria) this;
		}

		public Criteria andPeijPyIsNotNull() {
			addCriterion("peij_py is not null");
			return (Criteria) this;
		}

		public Criteria andPeijPyEqualTo(String value) {
			addCriterion("peij_py =", value, "peijPy");
			return (Criteria) this;
		}

		public Criteria andPeijPyNotEqualTo(String value) {
			addCriterion("peij_py <>", value, "peijPy");
			return (Criteria) this;
		}

		public Criteria andPeijPyGreaterThan(String value) {
			addCriterion("peij_py >", value, "peijPy");
			return (Criteria) this;
		}

		public Criteria andPeijPyGreaterThanOrEqualTo(String value) {
			addCriterion("peij_py >=", value, "peijPy");
			return (Criteria) this;
		}

		public Criteria andPeijPyLessThan(String value) {
			addCriterion("peij_py <", value, "peijPy");
			return (Criteria) this;
		}

		public Criteria andPeijPyLessThanOrEqualTo(String value) {
			addCriterion("peij_py <=", value, "peijPy");
			return (Criteria) this;
		}

		public Criteria andPeijPyLike(String value) {
			addCriterion("peij_py like", value, "peijPy");
			return (Criteria) this;
		}

		public Criteria andPeijPyNotLike(String value) {
			addCriterion("peij_py not like", value, "peijPy");
			return (Criteria) this;
		}

		public Criteria andPeijPyIn(List<String> values) {
			addCriterion("peij_py in", values, "peijPy");
			return (Criteria) this;
		}

		public Criteria andPeijPyNotIn(List<String> values) {
			addCriterion("peij_py not in", values, "peijPy");
			return (Criteria) this;
		}

		public Criteria andPeijPyBetween(String value1, String value2) {
			addCriterion("peij_py between", value1, value2, "peijPy");
			return (Criteria) this;
		}

		public Criteria andPeijPyNotBetween(String value1, String value2) {
			addCriterion("peij_py not between", value1, value2, "peijPy");
			return (Criteria) this;
		}

		public Criteria andPeijDwIsNull() {
			addCriterion("peij_dw is null");
			return (Criteria) this;
		}

		public Criteria andPeijDwIsNotNull() {
			addCriterion("peij_dw is not null");
			return (Criteria) this;
		}

		public Criteria andPeijDwEqualTo(String value) {
			addCriterion("peij_dw =", value, "peijDw");
			return (Criteria) this;
		}

		public Criteria andPeijDwNotEqualTo(String value) {
			addCriterion("peij_dw <>", value, "peijDw");
			return (Criteria) this;
		}

		public Criteria andPeijDwGreaterThan(String value) {
			addCriterion("peij_dw >", value, "peijDw");
			return (Criteria) this;
		}

		public Criteria andPeijDwGreaterThanOrEqualTo(String value) {
			addCriterion("peij_dw >=", value, "peijDw");
			return (Criteria) this;
		}

		public Criteria andPeijDwLessThan(String value) {
			addCriterion("peij_dw <", value, "peijDw");
			return (Criteria) this;
		}

		public Criteria andPeijDwLessThanOrEqualTo(String value) {
			addCriterion("peij_dw <=", value, "peijDw");
			return (Criteria) this;
		}

		public Criteria andPeijDwLike(String value) {
			addCriterion("peij_dw like", value, "peijDw");
			return (Criteria) this;
		}

		public Criteria andPeijDwNotLike(String value) {
			addCriterion("peij_dw not like", value, "peijDw");
			return (Criteria) this;
		}

		public Criteria andPeijDwIn(List<String> values) {
			addCriterion("peij_dw in", values, "peijDw");
			return (Criteria) this;
		}

		public Criteria andPeijDwNotIn(List<String> values) {
			addCriterion("peij_dw not in", values, "peijDw");
			return (Criteria) this;
		}

		public Criteria andPeijDwBetween(String value1, String value2) {
			addCriterion("peij_dw between", value1, value2, "peijDw");
			return (Criteria) this;
		}

		public Criteria andPeijDwNotBetween(String value1, String value2) {
			addCriterion("peij_dw not between", value1, value2, "peijDw");
			return (Criteria) this;
		}

		public Criteria andPeijJkIsNull() {
			addCriterion("peij_jk is null");
			return (Criteria) this;
		}

		public Criteria andPeijJkIsNotNull() {
			addCriterion("peij_jk is not null");
			return (Criteria) this;
		}

		public Criteria andPeijJkEqualTo(String value) {
			addCriterion("peij_jk =", value, "peijJk");
			return (Criteria) this;
		}

		public Criteria andPeijJkNotEqualTo(String value) {
			addCriterion("peij_jk <>", value, "peijJk");
			return (Criteria) this;
		}

		public Criteria andPeijJkGreaterThan(String value) {
			addCriterion("peij_jk >", value, "peijJk");
			return (Criteria) this;
		}

		public Criteria andPeijJkGreaterThanOrEqualTo(String value) {
			addCriterion("peij_jk >=", value, "peijJk");
			return (Criteria) this;
		}

		public Criteria andPeijJkLessThan(String value) {
			addCriterion("peij_jk <", value, "peijJk");
			return (Criteria) this;
		}

		public Criteria andPeijJkLessThanOrEqualTo(String value) {
			addCriterion("peij_jk <=", value, "peijJk");
			return (Criteria) this;
		}

		public Criteria andPeijJkLike(String value) {
			addCriterion("peij_jk like", value, "peijJk");
			return (Criteria) this;
		}

		public Criteria andPeijJkNotLike(String value) {
			addCriterion("peij_jk not like", value, "peijJk");
			return (Criteria) this;
		}

		public Criteria andPeijJkIn(List<String> values) {
			addCriterion("peij_jk in", values, "peijJk");
			return (Criteria) this;
		}

		public Criteria andPeijJkNotIn(List<String> values) {
			addCriterion("peij_jk not in", values, "peijJk");
			return (Criteria) this;
		}

		public Criteria andPeijJkBetween(String value1, String value2) {
			addCriterion("peij_jk between", value1, value2, "peijJk");
			return (Criteria) this;
		}

		public Criteria andPeijJkNotBetween(String value1, String value2) {
			addCriterion("peij_jk not between", value1, value2, "peijJk");
			return (Criteria) this;
		}

		public Criteria andPeijCxIsNull() {
			addCriterion("peij_cx is null");
			return (Criteria) this;
		}

		public Criteria andPeijCxIsNotNull() {
			addCriterion("peij_cx is not null");
			return (Criteria) this;
		}

		public Criteria andPeijCxEqualTo(String value) {
			addCriterion("peij_cx =", value, "peijCx");
			return (Criteria) this;
		}

		public Criteria andPeijCxNotEqualTo(String value) {
			addCriterion("peij_cx <>", value, "peijCx");
			return (Criteria) this;
		}

		public Criteria andPeijCxGreaterThan(String value) {
			addCriterion("peij_cx >", value, "peijCx");
			return (Criteria) this;
		}

		public Criteria andPeijCxGreaterThanOrEqualTo(String value) {
			addCriterion("peij_cx >=", value, "peijCx");
			return (Criteria) this;
		}

		public Criteria andPeijCxLessThan(String value) {
			addCriterion("peij_cx <", value, "peijCx");
			return (Criteria) this;
		}

		public Criteria andPeijCxLessThanOrEqualTo(String value) {
			addCriterion("peij_cx <=", value, "peijCx");
			return (Criteria) this;
		}

		public Criteria andPeijCxLike(String value) {
			addCriterion("peij_cx like", value, "peijCx");
			return (Criteria) this;
		}

		public Criteria andPeijCxNotLike(String value) {
			addCriterion("peij_cx not like", value, "peijCx");
			return (Criteria) this;
		}

		public Criteria andPeijCxIn(List<String> values) {
			addCriterion("peij_cx in", values, "peijCx");
			return (Criteria) this;
		}

		public Criteria andPeijCxNotIn(List<String> values) {
			addCriterion("peij_cx not in", values, "peijCx");
			return (Criteria) this;
		}

		public Criteria andPeijCxBetween(String value1, String value2) {
			addCriterion("peij_cx between", value1, value2, "peijCx");
			return (Criteria) this;
		}

		public Criteria andPeijCxNotBetween(String value1, String value2) {
			addCriterion("peij_cx not between", value1, value2, "peijCx");
			return (Criteria) this;
		}

		public Criteria andPeijCdIsNull() {
			addCriterion("peij_cd is null");
			return (Criteria) this;
		}

		public Criteria andPeijCdIsNotNull() {
			addCriterion("peij_cd is not null");
			return (Criteria) this;
		}

		public Criteria andPeijCdEqualTo(String value) {
			addCriterion("peij_cd =", value, "peijCd");
			return (Criteria) this;
		}

		public Criteria andPeijCdNotEqualTo(String value) {
			addCriterion("peij_cd <>", value, "peijCd");
			return (Criteria) this;
		}

		public Criteria andPeijCdGreaterThan(String value) {
			addCriterion("peij_cd >", value, "peijCd");
			return (Criteria) this;
		}

		public Criteria andPeijCdGreaterThanOrEqualTo(String value) {
			addCriterion("peij_cd >=", value, "peijCd");
			return (Criteria) this;
		}

		public Criteria andPeijCdLessThan(String value) {
			addCriterion("peij_cd <", value, "peijCd");
			return (Criteria) this;
		}

		public Criteria andPeijCdLessThanOrEqualTo(String value) {
			addCriterion("peij_cd <=", value, "peijCd");
			return (Criteria) this;
		}

		public Criteria andPeijCdLike(String value) {
			addCriterion("peij_cd like", value, "peijCd");
			return (Criteria) this;
		}

		public Criteria andPeijCdNotLike(String value) {
			addCriterion("peij_cd not like", value, "peijCd");
			return (Criteria) this;
		}

		public Criteria andPeijCdIn(List<String> values) {
			addCriterion("peij_cd in", values, "peijCd");
			return (Criteria) this;
		}

		public Criteria andPeijCdNotIn(List<String> values) {
			addCriterion("peij_cd not in", values, "peijCd");
			return (Criteria) this;
		}

		public Criteria andPeijCdBetween(String value1, String value2) {
			addCriterion("peij_cd between", value1, value2, "peijCd");
			return (Criteria) this;
		}

		public Criteria andPeijCdNotBetween(String value1, String value2) {
			addCriterion("peij_cd not between", value1, value2, "peijCd");
			return (Criteria) this;
		}

		public Criteria andPeijPpIsNull() {
			addCriterion("peij_pp is null");
			return (Criteria) this;
		}

		public Criteria andPeijPpIsNotNull() {
			addCriterion("peij_pp is not null");
			return (Criteria) this;
		}

		public Criteria andPeijPpEqualTo(String value) {
			addCriterion("peij_pp =", value, "peijPp");
			return (Criteria) this;
		}

		public Criteria andPeijPpNotEqualTo(String value) {
			addCriterion("peij_pp <>", value, "peijPp");
			return (Criteria) this;
		}

		public Criteria andPeijPpGreaterThan(String value) {
			addCriterion("peij_pp >", value, "peijPp");
			return (Criteria) this;
		}

		public Criteria andPeijPpGreaterThanOrEqualTo(String value) {
			addCriterion("peij_pp >=", value, "peijPp");
			return (Criteria) this;
		}

		public Criteria andPeijPpLessThan(String value) {
			addCriterion("peij_pp <", value, "peijPp");
			return (Criteria) this;
		}

		public Criteria andPeijPpLessThanOrEqualTo(String value) {
			addCriterion("peij_pp <=", value, "peijPp");
			return (Criteria) this;
		}

		public Criteria andPeijPpLike(String value) {
			addCriterion("peij_pp like", value, "peijPp");
			return (Criteria) this;
		}

		public Criteria andPeijPpNotLike(String value) {
			addCriterion("peij_pp not like", value, "peijPp");
			return (Criteria) this;
		}

		public Criteria andPeijPpIn(List<String> values) {
			addCriterion("peij_pp in", values, "peijPp");
			return (Criteria) this;
		}

		public Criteria andPeijPpNotIn(List<String> values) {
			addCriterion("peij_pp not in", values, "peijPp");
			return (Criteria) this;
		}

		public Criteria andPeijPpBetween(String value1, String value2) {
			addCriterion("peij_pp between", value1, value2, "peijPp");
			return (Criteria) this;
		}

		public Criteria andPeijPpNotBetween(String value1, String value2) {
			addCriterion("peij_pp not between", value1, value2, "peijPp");
			return (Criteria) this;
		}

		public Criteria andPeijThTyIsNull() {
			addCriterion("peij_th_ty is null");
			return (Criteria) this;
		}

		public Criteria andPeijThTyIsNotNull() {
			addCriterion("peij_th_ty is not null");
			return (Criteria) this;
		}

		public Criteria andPeijThTyEqualTo(String value) {
			addCriterion("peij_th_ty =", value, "peijThTy");
			return (Criteria) this;
		}

		public Criteria andPeijThTyNotEqualTo(String value) {
			addCriterion("peij_th_ty <>", value, "peijThTy");
			return (Criteria) this;
		}

		public Criteria andPeijThTyGreaterThan(String value) {
			addCriterion("peij_th_ty >", value, "peijThTy");
			return (Criteria) this;
		}

		public Criteria andPeijThTyGreaterThanOrEqualTo(String value) {
			addCriterion("peij_th_ty >=", value, "peijThTy");
			return (Criteria) this;
		}

		public Criteria andPeijThTyLessThan(String value) {
			addCriterion("peij_th_ty <", value, "peijThTy");
			return (Criteria) this;
		}

		public Criteria andPeijThTyLessThanOrEqualTo(String value) {
			addCriterion("peij_th_ty <=", value, "peijThTy");
			return (Criteria) this;
		}

		public Criteria andPeijThTyLike(String value) {
			addCriterion("peij_th_ty like", value, "peijThTy");
			return (Criteria) this;
		}

		public Criteria andPeijThTyNotLike(String value) {
			addCriterion("peij_th_ty not like", value, "peijThTy");
			return (Criteria) this;
		}

		public Criteria andPeijThTyIn(List<String> values) {
			addCriterion("peij_th_ty in", values, "peijThTy");
			return (Criteria) this;
		}

		public Criteria andPeijThTyNotIn(List<String> values) {
			addCriterion("peij_th_ty not in", values, "peijThTy");
			return (Criteria) this;
		}

		public Criteria andPeijThTyBetween(String value1, String value2) {
			addCriterion("peij_th_ty between", value1, value2, "peijThTy");
			return (Criteria) this;
		}

		public Criteria andPeijThTyNotBetween(String value1, String value2) {
			addCriterion("peij_th_ty not between", value1, value2, "peijThTy");
			return (Criteria) this;
		}

		public Criteria andPeijCxTyIsNull() {
			addCriterion("peij_cx_ty is null");
			return (Criteria) this;
		}

		public Criteria andPeijCxTyIsNotNull() {
			addCriterion("peij_cx_ty is not null");
			return (Criteria) this;
		}

		public Criteria andPeijCxTyEqualTo(String value) {
			addCriterion("peij_cx_ty =", value, "peijCxTy");
			return (Criteria) this;
		}

		public Criteria andPeijCxTyNotEqualTo(String value) {
			addCriterion("peij_cx_ty <>", value, "peijCxTy");
			return (Criteria) this;
		}

		public Criteria andPeijCxTyGreaterThan(String value) {
			addCriterion("peij_cx_ty >", value, "peijCxTy");
			return (Criteria) this;
		}

		public Criteria andPeijCxTyGreaterThanOrEqualTo(String value) {
			addCriterion("peij_cx_ty >=", value, "peijCxTy");
			return (Criteria) this;
		}

		public Criteria andPeijCxTyLessThan(String value) {
			addCriterion("peij_cx_ty <", value, "peijCxTy");
			return (Criteria) this;
		}

		public Criteria andPeijCxTyLessThanOrEqualTo(String value) {
			addCriterion("peij_cx_ty <=", value, "peijCxTy");
			return (Criteria) this;
		}

		public Criteria andPeijCxTyLike(String value) {
			addCriterion("peij_cx_ty like", value, "peijCxTy");
			return (Criteria) this;
		}

		public Criteria andPeijCxTyNotLike(String value) {
			addCriterion("peij_cx_ty not like", value, "peijCxTy");
			return (Criteria) this;
		}

		public Criteria andPeijCxTyIn(List<String> values) {
			addCriterion("peij_cx_ty in", values, "peijCxTy");
			return (Criteria) this;
		}

		public Criteria andPeijCxTyNotIn(List<String> values) {
			addCriterion("peij_cx_ty not in", values, "peijCxTy");
			return (Criteria) this;
		}

		public Criteria andPeijCxTyBetween(String value1, String value2) {
			addCriterion("peij_cx_ty between", value1, value2, "peijCxTy");
			return (Criteria) this;
		}

		public Criteria andPeijCxTyNotBetween(String value1, String value2) {
			addCriterion("peij_cx_ty not between", value1, value2, "peijCxTy");
			return (Criteria) this;
		}

		public Criteria andPeijZlIsNull() {
			addCriterion("peij_zl is null");
			return (Criteria) this;
		}

		public Criteria andPeijZlIsNotNull() {
			addCriterion("peij_zl is not null");
			return (Criteria) this;
		}

		public Criteria andPeijZlEqualTo(String value) {
			addCriterion("peij_zl =", value, "peijZl");
			return (Criteria) this;
		}

		public Criteria andPeijZlNotEqualTo(String value) {
			addCriterion("peij_zl <>", value, "peijZl");
			return (Criteria) this;
		}

		public Criteria andPeijZlGreaterThan(String value) {
			addCriterion("peij_zl >", value, "peijZl");
			return (Criteria) this;
		}

		public Criteria andPeijZlGreaterThanOrEqualTo(String value) {
			addCriterion("peij_zl >=", value, "peijZl");
			return (Criteria) this;
		}

		public Criteria andPeijZlLessThan(String value) {
			addCriterion("peij_zl <", value, "peijZl");
			return (Criteria) this;
		}

		public Criteria andPeijZlLessThanOrEqualTo(String value) {
			addCriterion("peij_zl <=", value, "peijZl");
			return (Criteria) this;
		}

		public Criteria andPeijZlLike(String value) {
			addCriterion("peij_zl like", value, "peijZl");
			return (Criteria) this;
		}

		public Criteria andPeijZlNotLike(String value) {
			addCriterion("peij_zl not like", value, "peijZl");
			return (Criteria) this;
		}

		public Criteria andPeijZlIn(List<String> values) {
			addCriterion("peij_zl in", values, "peijZl");
			return (Criteria) this;
		}

		public Criteria andPeijZlNotIn(List<String> values) {
			addCriterion("peij_zl not in", values, "peijZl");
			return (Criteria) this;
		}

		public Criteria andPeijZlBetween(String value1, String value2) {
			addCriterion("peij_zl between", value1, value2, "peijZl");
			return (Criteria) this;
		}

		public Criteria andPeijZlNotBetween(String value1, String value2) {
			addCriterion("peij_zl not between", value1, value2, "peijZl");
			return (Criteria) this;
		}

		public Criteria andPeijMbIsNull() {
			addCriterion("peij_mb is null");
			return (Criteria) this;
		}

		public Criteria andPeijMbIsNotNull() {
			addCriterion("peij_mb is not null");
			return (Criteria) this;
		}

		public Criteria andPeijMbEqualTo(String value) {
			addCriterion("peij_mb =", value, "peijMb");
			return (Criteria) this;
		}

		public Criteria andPeijMbNotEqualTo(String value) {
			addCriterion("peij_mb <>", value, "peijMb");
			return (Criteria) this;
		}

		public Criteria andPeijMbGreaterThan(String value) {
			addCriterion("peij_mb >", value, "peijMb");
			return (Criteria) this;
		}

		public Criteria andPeijMbGreaterThanOrEqualTo(String value) {
			addCriterion("peij_mb >=", value, "peijMb");
			return (Criteria) this;
		}

		public Criteria andPeijMbLessThan(String value) {
			addCriterion("peij_mb <", value, "peijMb");
			return (Criteria) this;
		}

		public Criteria andPeijMbLessThanOrEqualTo(String value) {
			addCriterion("peij_mb <=", value, "peijMb");
			return (Criteria) this;
		}

		public Criteria andPeijMbLike(String value) {
			addCriterion("peij_mb like", value, "peijMb");
			return (Criteria) this;
		}

		public Criteria andPeijMbNotLike(String value) {
			addCriterion("peij_mb not like", value, "peijMb");
			return (Criteria) this;
		}

		public Criteria andPeijMbIn(List<String> values) {
			addCriterion("peij_mb in", values, "peijMb");
			return (Criteria) this;
		}

		public Criteria andPeijMbNotIn(List<String> values) {
			addCriterion("peij_mb not in", values, "peijMb");
			return (Criteria) this;
		}

		public Criteria andPeijMbBetween(String value1, String value2) {
			addCriterion("peij_mb between", value1, value2, "peijMb");
			return (Criteria) this;
		}

		public Criteria andPeijMbNotBetween(String value1, String value2) {
			addCriterion("peij_mb not between", value1, value2, "peijMb");
			return (Criteria) this;
		}

		public Criteria andPeijScIsNull() {
			addCriterion("peij_sc is null");
			return (Criteria) this;
		}

		public Criteria andPeijScIsNotNull() {
			addCriterion("peij_sc is not null");
			return (Criteria) this;
		}

		public Criteria andPeijScEqualTo(String value) {
			addCriterion("peij_sc =", value, "peijSc");
			return (Criteria) this;
		}

		public Criteria andPeijScNotEqualTo(String value) {
			addCriterion("peij_sc <>", value, "peijSc");
			return (Criteria) this;
		}

		public Criteria andPeijScGreaterThan(String value) {
			addCriterion("peij_sc >", value, "peijSc");
			return (Criteria) this;
		}

		public Criteria andPeijScGreaterThanOrEqualTo(String value) {
			addCriterion("peij_sc >=", value, "peijSc");
			return (Criteria) this;
		}

		public Criteria andPeijScLessThan(String value) {
			addCriterion("peij_sc <", value, "peijSc");
			return (Criteria) this;
		}

		public Criteria andPeijScLessThanOrEqualTo(String value) {
			addCriterion("peij_sc <=", value, "peijSc");
			return (Criteria) this;
		}

		public Criteria andPeijScLike(String value) {
			addCriterion("peij_sc like", value, "peijSc");
			return (Criteria) this;
		}

		public Criteria andPeijScNotLike(String value) {
			addCriterion("peij_sc not like", value, "peijSc");
			return (Criteria) this;
		}

		public Criteria andPeijScIn(List<String> values) {
			addCriterion("peij_sc in", values, "peijSc");
			return (Criteria) this;
		}

		public Criteria andPeijScNotIn(List<String> values) {
			addCriterion("peij_sc not in", values, "peijSc");
			return (Criteria) this;
		}

		public Criteria andPeijScBetween(String value1, String value2) {
			addCriterion("peij_sc between", value1, value2, "peijSc");
			return (Criteria) this;
		}

		public Criteria andPeijScNotBetween(String value1, String value2) {
			addCriterion("peij_sc not between", value1, value2, "peijSc");
			return (Criteria) this;
		}

		public Criteria andPeijYcIsNull() {
			addCriterion("peij_yc is null");
			return (Criteria) this;
		}

		public Criteria andPeijYcIsNotNull() {
			addCriterion("peij_yc is not null");
			return (Criteria) this;
		}

		public Criteria andPeijYcEqualTo(String value) {
			addCriterion("peij_yc =", value, "peijYc");
			return (Criteria) this;
		}

		public Criteria andPeijYcNotEqualTo(String value) {
			addCriterion("peij_yc <>", value, "peijYc");
			return (Criteria) this;
		}

		public Criteria andPeijYcGreaterThan(String value) {
			addCriterion("peij_yc >", value, "peijYc");
			return (Criteria) this;
		}

		public Criteria andPeijYcGreaterThanOrEqualTo(String value) {
			addCriterion("peij_yc >=", value, "peijYc");
			return (Criteria) this;
		}

		public Criteria andPeijYcLessThan(String value) {
			addCriterion("peij_yc <", value, "peijYc");
			return (Criteria) this;
		}

		public Criteria andPeijYcLessThanOrEqualTo(String value) {
			addCriterion("peij_yc <=", value, "peijYc");
			return (Criteria) this;
		}

		public Criteria andPeijYcLike(String value) {
			addCriterion("peij_yc like", value, "peijYc");
			return (Criteria) this;
		}

		public Criteria andPeijYcNotLike(String value) {
			addCriterion("peij_yc not like", value, "peijYc");
			return (Criteria) this;
		}

		public Criteria andPeijYcIn(List<String> values) {
			addCriterion("peij_yc in", values, "peijYc");
			return (Criteria) this;
		}

		public Criteria andPeijYcNotIn(List<String> values) {
			addCriterion("peij_yc not in", values, "peijYc");
			return (Criteria) this;
		}

		public Criteria andPeijYcBetween(String value1, String value2) {
			addCriterion("peij_yc between", value1, value2, "peijYc");
			return (Criteria) this;
		}

		public Criteria andPeijYcNotBetween(String value1, String value2) {
			addCriterion("peij_yc not between", value1, value2, "peijYc");
			return (Criteria) this;
		}

		public Criteria andPeijXhIsNull() {
			addCriterion("peij_xh is null");
			return (Criteria) this;
		}

		public Criteria andPeijXhIsNotNull() {
			addCriterion("peij_xh is not null");
			return (Criteria) this;
		}

		public Criteria andPeijXhEqualTo(String value) {
			addCriterion("peij_xh =", value, "peijXh");
			return (Criteria) this;
		}

		public Criteria andPeijXhNotEqualTo(String value) {
			addCriterion("peij_xh <>", value, "peijXh");
			return (Criteria) this;
		}

		public Criteria andPeijXhGreaterThan(String value) {
			addCriterion("peij_xh >", value, "peijXh");
			return (Criteria) this;
		}

		public Criteria andPeijXhGreaterThanOrEqualTo(String value) {
			addCriterion("peij_xh >=", value, "peijXh");
			return (Criteria) this;
		}

		public Criteria andPeijXhLessThan(String value) {
			addCriterion("peij_xh <", value, "peijXh");
			return (Criteria) this;
		}

		public Criteria andPeijXhLessThanOrEqualTo(String value) {
			addCriterion("peij_xh <=", value, "peijXh");
			return (Criteria) this;
		}

		public Criteria andPeijXhLike(String value) {
			addCriterion("peij_xh like", value, "peijXh");
			return (Criteria) this;
		}

		public Criteria andPeijXhNotLike(String value) {
			addCriterion("peij_xh not like", value, "peijXh");
			return (Criteria) this;
		}

		public Criteria andPeijXhIn(List<String> values) {
			addCriterion("peij_xh in", values, "peijXh");
			return (Criteria) this;
		}

		public Criteria andPeijXhNotIn(List<String> values) {
			addCriterion("peij_xh not in", values, "peijXh");
			return (Criteria) this;
		}

		public Criteria andPeijXhBetween(String value1, String value2) {
			addCriterion("peij_xh between", value1, value2, "peijXh");
			return (Criteria) this;
		}

		public Criteria andPeijXhNotBetween(String value1, String value2) {
			addCriterion("peij_xh not between", value1, value2, "peijXh");
			return (Criteria) this;
		}

		public Criteria andPeijShIsNull() {
			addCriterion("peij_sh is null");
			return (Criteria) this;
		}

		public Criteria andPeijShIsNotNull() {
			addCriterion("peij_sh is not null");
			return (Criteria) this;
		}

		public Criteria andPeijShEqualTo(String value) {
			addCriterion("peij_sh =", value, "peijSh");
			return (Criteria) this;
		}

		public Criteria andPeijShNotEqualTo(String value) {
			addCriterion("peij_sh <>", value, "peijSh");
			return (Criteria) this;
		}

		public Criteria andPeijShGreaterThan(String value) {
			addCriterion("peij_sh >", value, "peijSh");
			return (Criteria) this;
		}

		public Criteria andPeijShGreaterThanOrEqualTo(String value) {
			addCriterion("peij_sh >=", value, "peijSh");
			return (Criteria) this;
		}

		public Criteria andPeijShLessThan(String value) {
			addCriterion("peij_sh <", value, "peijSh");
			return (Criteria) this;
		}

		public Criteria andPeijShLessThanOrEqualTo(String value) {
			addCriterion("peij_sh <=", value, "peijSh");
			return (Criteria) this;
		}

		public Criteria andPeijShLike(String value) {
			addCriterion("peij_sh like", value, "peijSh");
			return (Criteria) this;
		}

		public Criteria andPeijShNotLike(String value) {
			addCriterion("peij_sh not like", value, "peijSh");
			return (Criteria) this;
		}

		public Criteria andPeijShIn(List<String> values) {
			addCriterion("peij_sh in", values, "peijSh");
			return (Criteria) this;
		}

		public Criteria andPeijShNotIn(List<String> values) {
			addCriterion("peij_sh not in", values, "peijSh");
			return (Criteria) this;
		}

		public Criteria andPeijShBetween(String value1, String value2) {
			addCriterion("peij_sh between", value1, value2, "peijSh");
			return (Criteria) this;
		}

		public Criteria andPeijShNotBetween(String value1, String value2) {
			addCriterion("peij_sh not between", value1, value2, "peijSh");
			return (Criteria) this;
		}

		public Criteria andPeijShlvIsNull() {
			addCriterion("peij_shlv is null");
			return (Criteria) this;
		}

		public Criteria andPeijShlvIsNotNull() {
			addCriterion("peij_shlv is not null");
			return (Criteria) this;
		}

		public Criteria andPeijShlvEqualTo(BigDecimal value) {
			addCriterion("peij_shlv =", value, "peijShlv");
			return (Criteria) this;
		}

		public Criteria andPeijShlvNotEqualTo(BigDecimal value) {
			addCriterion("peij_shlv <>", value, "peijShlv");
			return (Criteria) this;
		}

		public Criteria andPeijShlvGreaterThan(BigDecimal value) {
			addCriterion("peij_shlv >", value, "peijShlv");
			return (Criteria) this;
		}

		public Criteria andPeijShlvGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("peij_shlv >=", value, "peijShlv");
			return (Criteria) this;
		}

		public Criteria andPeijShlvLessThan(BigDecimal value) {
			addCriterion("peij_shlv <", value, "peijShlv");
			return (Criteria) this;
		}

		public Criteria andPeijShlvLessThanOrEqualTo(BigDecimal value) {
			addCriterion("peij_shlv <=", value, "peijShlv");
			return (Criteria) this;
		}

		public Criteria andPeijShlvIn(List<BigDecimal> values) {
			addCriterion("peij_shlv in", values, "peijShlv");
			return (Criteria) this;
		}

		public Criteria andPeijShlvNotIn(List<BigDecimal> values) {
			addCriterion("peij_shlv not in", values, "peijShlv");
			return (Criteria) this;
		}

		public Criteria andPeijShlvBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("peij_shlv between", value1, value2, "peijShlv");
			return (Criteria) this;
		}

		public Criteria andPeijShlvNotBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("peij_shlv not between", value1, value2, "peijShlv");
			return (Criteria) this;
		}

		public Criteria andPeijBzIsNull() {
			addCriterion("peij_bz is null");
			return (Criteria) this;
		}

		public Criteria andPeijBzIsNotNull() {
			addCriterion("peij_bz is not null");
			return (Criteria) this;
		}

		public Criteria andPeijBzEqualTo(String value) {
			addCriterion("peij_bz =", value, "peijBz");
			return (Criteria) this;
		}

		public Criteria andPeijBzNotEqualTo(String value) {
			addCriterion("peij_bz <>", value, "peijBz");
			return (Criteria) this;
		}

		public Criteria andPeijBzGreaterThan(String value) {
			addCriterion("peij_bz >", value, "peijBz");
			return (Criteria) this;
		}

		public Criteria andPeijBzGreaterThanOrEqualTo(String value) {
			addCriterion("peij_bz >=", value, "peijBz");
			return (Criteria) this;
		}

		public Criteria andPeijBzLessThan(String value) {
			addCriterion("peij_bz <", value, "peijBz");
			return (Criteria) this;
		}

		public Criteria andPeijBzLessThanOrEqualTo(String value) {
			addCriterion("peij_bz <=", value, "peijBz");
			return (Criteria) this;
		}

		public Criteria andPeijBzLike(String value) {
			addCriterion("peij_bz like", value, "peijBz");
			return (Criteria) this;
		}

		public Criteria andPeijBzNotLike(String value) {
			addCriterion("peij_bz not like", value, "peijBz");
			return (Criteria) this;
		}

		public Criteria andPeijBzIn(List<String> values) {
			addCriterion("peij_bz in", values, "peijBz");
			return (Criteria) this;
		}

		public Criteria andPeijBzNotIn(List<String> values) {
			addCriterion("peij_bz not in", values, "peijBz");
			return (Criteria) this;
		}

		public Criteria andPeijBzBetween(String value1, String value2) {
			addCriterion("peij_bz between", value1, value2, "peijBz");
			return (Criteria) this;
		}

		public Criteria andPeijBzNotBetween(String value1, String value2) {
			addCriterion("peij_bz not between", value1, value2, "peijBz");
			return (Criteria) this;
		}

		public Criteria andPeijTiaomaIsNull() {
			addCriterion("peij_tiaoma is null");
			return (Criteria) this;
		}

		public Criteria andPeijTiaomaIsNotNull() {
			addCriterion("peij_tiaoma is not null");
			return (Criteria) this;
		}

		public Criteria andPeijTiaomaEqualTo(String value) {
			addCriterion("peij_tiaoma =", value, "peijTiaoma");
			return (Criteria) this;
		}

		public Criteria andPeijTiaomaNotEqualTo(String value) {
			addCriterion("peij_tiaoma <>", value, "peijTiaoma");
			return (Criteria) this;
		}

		public Criteria andPeijTiaomaGreaterThan(String value) {
			addCriterion("peij_tiaoma >", value, "peijTiaoma");
			return (Criteria) this;
		}

		public Criteria andPeijTiaomaGreaterThanOrEqualTo(String value) {
			addCriterion("peij_tiaoma >=", value, "peijTiaoma");
			return (Criteria) this;
		}

		public Criteria andPeijTiaomaLessThan(String value) {
			addCriterion("peij_tiaoma <", value, "peijTiaoma");
			return (Criteria) this;
		}

		public Criteria andPeijTiaomaLessThanOrEqualTo(String value) {
			addCriterion("peij_tiaoma <=", value, "peijTiaoma");
			return (Criteria) this;
		}

		public Criteria andPeijTiaomaLike(String value) {
			addCriterion("peij_tiaoma like", value, "peijTiaoma");
			return (Criteria) this;
		}

		public Criteria andPeijTiaomaNotLike(String value) {
			addCriterion("peij_tiaoma not like", value, "peijTiaoma");
			return (Criteria) this;
		}

		public Criteria andPeijTiaomaIn(List<String> values) {
			addCriterion("peij_tiaoma in", values, "peijTiaoma");
			return (Criteria) this;
		}

		public Criteria andPeijTiaomaNotIn(List<String> values) {
			addCriterion("peij_tiaoma not in", values, "peijTiaoma");
			return (Criteria) this;
		}

		public Criteria andPeijTiaomaBetween(String value1, String value2) {
			addCriterion("peij_tiaoma between", value1, value2, "peijTiaoma");
			return (Criteria) this;
		}

		public Criteria andPeijTiaomaNotBetween(String value1, String value2) {
			addCriterion("peij_tiaoma not between", value1, value2,
					"peijTiaoma");
			return (Criteria) this;
		}

		public Criteria andPeijClIsNull() {
			addCriterion("peij_cl is null");
			return (Criteria) this;
		}

		public Criteria andPeijClIsNotNull() {
			addCriterion("peij_cl is not null");
			return (Criteria) this;
		}

		public Criteria andPeijClEqualTo(String value) {
			addCriterion("peij_cl =", value, "peijCl");
			return (Criteria) this;
		}

		public Criteria andPeijClNotEqualTo(String value) {
			addCriterion("peij_cl <>", value, "peijCl");
			return (Criteria) this;
		}

		public Criteria andPeijClGreaterThan(String value) {
			addCriterion("peij_cl >", value, "peijCl");
			return (Criteria) this;
		}

		public Criteria andPeijClGreaterThanOrEqualTo(String value) {
			addCriterion("peij_cl >=", value, "peijCl");
			return (Criteria) this;
		}

		public Criteria andPeijClLessThan(String value) {
			addCriterion("peij_cl <", value, "peijCl");
			return (Criteria) this;
		}

		public Criteria andPeijClLessThanOrEqualTo(String value) {
			addCriterion("peij_cl <=", value, "peijCl");
			return (Criteria) this;
		}

		public Criteria andPeijClLike(String value) {
			addCriterion("peij_cl like", value, "peijCl");
			return (Criteria) this;
		}

		public Criteria andPeijClNotLike(String value) {
			addCriterion("peij_cl not like", value, "peijCl");
			return (Criteria) this;
		}

		public Criteria andPeijClIn(List<String> values) {
			addCriterion("peij_cl in", values, "peijCl");
			return (Criteria) this;
		}

		public Criteria andPeijClNotIn(List<String> values) {
			addCriterion("peij_cl not in", values, "peijCl");
			return (Criteria) this;
		}

		public Criteria andPeijClBetween(String value1, String value2) {
			addCriterion("peij_cl between", value1, value2, "peijCl");
			return (Criteria) this;
		}

		public Criteria andPeijClNotBetween(String value1, String value2) {
			addCriterion("peij_cl not between", value1, value2, "peijCl");
			return (Criteria) this;
		}

		public Criteria andPeijZkIsNull() {
			addCriterion("peij_zk is null");
			return (Criteria) this;
		}

		public Criteria andPeijZkIsNotNull() {
			addCriterion("peij_zk is not null");
			return (Criteria) this;
		}

		public Criteria andPeijZkEqualTo(BigDecimal value) {
			addCriterion("peij_zk =", value, "peijZk");
			return (Criteria) this;
		}

		public Criteria andPeijZkNotEqualTo(BigDecimal value) {
			addCriterion("peij_zk <>", value, "peijZk");
			return (Criteria) this;
		}

		public Criteria andPeijZkGreaterThan(BigDecimal value) {
			addCriterion("peij_zk >", value, "peijZk");
			return (Criteria) this;
		}

		public Criteria andPeijZkGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("peij_zk >=", value, "peijZk");
			return (Criteria) this;
		}

		public Criteria andPeijZkLessThan(BigDecimal value) {
			addCriterion("peij_zk <", value, "peijZk");
			return (Criteria) this;
		}

		public Criteria andPeijZkLessThanOrEqualTo(BigDecimal value) {
			addCriterion("peij_zk <=", value, "peijZk");
			return (Criteria) this;
		}

		public Criteria andPeijZkIn(List<BigDecimal> values) {
			addCriterion("peij_zk in", values, "peijZk");
			return (Criteria) this;
		}

		public Criteria andPeijZkNotIn(List<BigDecimal> values) {
			addCriterion("peij_zk not in", values, "peijZk");
			return (Criteria) this;
		}

		public Criteria andPeijZkBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("peij_zk between", value1, value2, "peijZk");
			return (Criteria) this;
		}

		public Criteria andPeijZkNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("peij_zk not between", value1, value2, "peijZk");
			return (Criteria) this;
		}

		public Criteria andPeijTichenglvIsNull() {
			addCriterion("peij_TiChengLv is null");
			return (Criteria) this;
		}

		public Criteria andPeijTichenglvIsNotNull() {
			addCriterion("peij_TiChengLv is not null");
			return (Criteria) this;
		}

		public Criteria andPeijTichenglvEqualTo(BigDecimal value) {
			addCriterion("peij_TiChengLv =", value, "peijTichenglv");
			return (Criteria) this;
		}

		public Criteria andPeijTichenglvNotEqualTo(BigDecimal value) {
			addCriterion("peij_TiChengLv <>", value, "peijTichenglv");
			return (Criteria) this;
		}

		public Criteria andPeijTichenglvGreaterThan(BigDecimal value) {
			addCriterion("peij_TiChengLv >", value, "peijTichenglv");
			return (Criteria) this;
		}

		public Criteria andPeijTichenglvGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("peij_TiChengLv >=", value, "peijTichenglv");
			return (Criteria) this;
		}

		public Criteria andPeijTichenglvLessThan(BigDecimal value) {
			addCriterion("peij_TiChengLv <", value, "peijTichenglv");
			return (Criteria) this;
		}

		public Criteria andPeijTichenglvLessThanOrEqualTo(BigDecimal value) {
			addCriterion("peij_TiChengLv <=", value, "peijTichenglv");
			return (Criteria) this;
		}

		public Criteria andPeijTichenglvIn(List<BigDecimal> values) {
			addCriterion("peij_TiChengLv in", values, "peijTichenglv");
			return (Criteria) this;
		}

		public Criteria andPeijTichenglvNotIn(List<BigDecimal> values) {
			addCriterion("peij_TiChengLv not in", values, "peijTichenglv");
			return (Criteria) this;
		}

		public Criteria andPeijTichenglvBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("peij_TiChengLv between", value1, value2,
					"peijTichenglv");
			return (Criteria) this;
		}

		public Criteria andPeijTichenglvNotBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("peij_TiChengLv not between", value1, value2,
					"peijTichenglv");
			return (Criteria) this;
		}

		public Criteria andPeijCxpyIsNull() {
			addCriterion("peij_cxpy is null");
			return (Criteria) this;
		}

		public Criteria andPeijCxpyIsNotNull() {
			addCriterion("peij_cxpy is not null");
			return (Criteria) this;
		}

		public Criteria andPeijCxpyEqualTo(String value) {
			addCriterion("peij_cxpy =", value, "peijCxpy");
			return (Criteria) this;
		}

		public Criteria andPeijCxpyNotEqualTo(String value) {
			addCriterion("peij_cxpy <>", value, "peijCxpy");
			return (Criteria) this;
		}

		public Criteria andPeijCxpyGreaterThan(String value) {
			addCriterion("peij_cxpy >", value, "peijCxpy");
			return (Criteria) this;
		}

		public Criteria andPeijCxpyGreaterThanOrEqualTo(String value) {
			addCriterion("peij_cxpy >=", value, "peijCxpy");
			return (Criteria) this;
		}

		public Criteria andPeijCxpyLessThan(String value) {
			addCriterion("peij_cxpy <", value, "peijCxpy");
			return (Criteria) this;
		}

		public Criteria andPeijCxpyLessThanOrEqualTo(String value) {
			addCriterion("peij_cxpy <=", value, "peijCxpy");
			return (Criteria) this;
		}

		public Criteria andPeijCxpyLike(String value) {
			addCriterion("peij_cxpy like", value, "peijCxpy");
			return (Criteria) this;
		}

		public Criteria andPeijCxpyNotLike(String value) {
			addCriterion("peij_cxpy not like", value, "peijCxpy");
			return (Criteria) this;
		}

		public Criteria andPeijCxpyIn(List<String> values) {
			addCriterion("peij_cxpy in", values, "peijCxpy");
			return (Criteria) this;
		}

		public Criteria andPeijCxpyNotIn(List<String> values) {
			addCriterion("peij_cxpy not in", values, "peijCxpy");
			return (Criteria) this;
		}

		public Criteria andPeijCxpyBetween(String value1, String value2) {
			addCriterion("peij_cxpy between", value1, value2, "peijCxpy");
			return (Criteria) this;
		}

		public Criteria andPeijCxpyNotBetween(String value1, String value2) {
			addCriterion("peij_cxpy not between", value1, value2, "peijCxpy");
			return (Criteria) this;
		}

		public Criteria andKehuNoIsNull() {
			addCriterion("kehu_no is null");
			return (Criteria) this;
		}

		public Criteria andKehuNoIsNotNull() {
			addCriterion("kehu_no is not null");
			return (Criteria) this;
		}

		public Criteria andKehuNoEqualTo(String value) {
			addCriterion("kehu_no =", value, "kehuNo");
			return (Criteria) this;
		}

		public Criteria andKehuNoNotEqualTo(String value) {
			addCriterion("kehu_no <>", value, "kehuNo");
			return (Criteria) this;
		}

		public Criteria andKehuNoGreaterThan(String value) {
			addCriterion("kehu_no >", value, "kehuNo");
			return (Criteria) this;
		}

		public Criteria andKehuNoGreaterThanOrEqualTo(String value) {
			addCriterion("kehu_no >=", value, "kehuNo");
			return (Criteria) this;
		}

		public Criteria andKehuNoLessThan(String value) {
			addCriterion("kehu_no <", value, "kehuNo");
			return (Criteria) this;
		}

		public Criteria andKehuNoLessThanOrEqualTo(String value) {
			addCriterion("kehu_no <=", value, "kehuNo");
			return (Criteria) this;
		}

		public Criteria andKehuNoLike(String value) {
			addCriterion("kehu_no like", value, "kehuNo");
			return (Criteria) this;
		}

		public Criteria andKehuNoNotLike(String value) {
			addCriterion("kehu_no not like", value, "kehuNo");
			return (Criteria) this;
		}

		public Criteria andKehuNoIn(List<String> values) {
			addCriterion("kehu_no in", values, "kehuNo");
			return (Criteria) this;
		}

		public Criteria andKehuNoNotIn(List<String> values) {
			addCriterion("kehu_no not in", values, "kehuNo");
			return (Criteria) this;
		}

		public Criteria andKehuNoBetween(String value1, String value2) {
			addCriterion("kehu_no between", value1, value2, "kehuNo");
			return (Criteria) this;
		}

		public Criteria andKehuNoNotBetween(String value1, String value2) {
			addCriterion("kehu_no not between", value1, value2, "kehuNo");
			return (Criteria) this;
		}

		public Criteria andKehuMcIsNull() {
			addCriterion("kehu_mc is null");
			return (Criteria) this;
		}

		public Criteria andKehuMcIsNotNull() {
			addCriterion("kehu_mc is not null");
			return (Criteria) this;
		}

		public Criteria andKehuMcEqualTo(String value) {
			addCriterion("kehu_mc =", value, "kehuMc");
			return (Criteria) this;
		}

		public Criteria andKehuMcNotEqualTo(String value) {
			addCriterion("kehu_mc <>", value, "kehuMc");
			return (Criteria) this;
		}

		public Criteria andKehuMcGreaterThan(String value) {
			addCriterion("kehu_mc >", value, "kehuMc");
			return (Criteria) this;
		}

		public Criteria andKehuMcGreaterThanOrEqualTo(String value) {
			addCriterion("kehu_mc >=", value, "kehuMc");
			return (Criteria) this;
		}

		public Criteria andKehuMcLessThan(String value) {
			addCriterion("kehu_mc <", value, "kehuMc");
			return (Criteria) this;
		}

		public Criteria andKehuMcLessThanOrEqualTo(String value) {
			addCriterion("kehu_mc <=", value, "kehuMc");
			return (Criteria) this;
		}

		public Criteria andKehuMcLike(String value) {
			addCriterion("kehu_mc like", value, "kehuMc");
			return (Criteria) this;
		}

		public Criteria andKehuMcNotLike(String value) {
			addCriterion("kehu_mc not like", value, "kehuMc");
			return (Criteria) this;
		}

		public Criteria andKehuMcIn(List<String> values) {
			addCriterion("kehu_mc in", values, "kehuMc");
			return (Criteria) this;
		}

		public Criteria andKehuMcNotIn(List<String> values) {
			addCriterion("kehu_mc not in", values, "kehuMc");
			return (Criteria) this;
		}

		public Criteria andKehuMcBetween(String value1, String value2) {
			addCriterion("kehu_mc between", value1, value2, "kehuMc");
			return (Criteria) this;
		}

		public Criteria andKehuMcNotBetween(String value1, String value2) {
			addCriterion("kehu_mc not between", value1, value2, "kehuMc");
			return (Criteria) this;
		}

		public Criteria andPeijMcwbIsNull() {
			addCriterion("peij_mcwb is null");
			return (Criteria) this;
		}

		public Criteria andPeijMcwbIsNotNull() {
			addCriterion("peij_mcwb is not null");
			return (Criteria) this;
		}

		public Criteria andPeijMcwbEqualTo(String value) {
			addCriterion("peij_mcwb =", value, "peijMcwb");
			return (Criteria) this;
		}

		public Criteria andPeijMcwbNotEqualTo(String value) {
			addCriterion("peij_mcwb <>", value, "peijMcwb");
			return (Criteria) this;
		}

		public Criteria andPeijMcwbGreaterThan(String value) {
			addCriterion("peij_mcwb >", value, "peijMcwb");
			return (Criteria) this;
		}

		public Criteria andPeijMcwbGreaterThanOrEqualTo(String value) {
			addCriterion("peij_mcwb >=", value, "peijMcwb");
			return (Criteria) this;
		}

		public Criteria andPeijMcwbLessThan(String value) {
			addCriterion("peij_mcwb <", value, "peijMcwb");
			return (Criteria) this;
		}

		public Criteria andPeijMcwbLessThanOrEqualTo(String value) {
			addCriterion("peij_mcwb <=", value, "peijMcwb");
			return (Criteria) this;
		}

		public Criteria andPeijMcwbLike(String value) {
			addCriterion("peij_mcwb like", value, "peijMcwb");
			return (Criteria) this;
		}

		public Criteria andPeijMcwbNotLike(String value) {
			addCriterion("peij_mcwb not like", value, "peijMcwb");
			return (Criteria) this;
		}

		public Criteria andPeijMcwbIn(List<String> values) {
			addCriterion("peij_mcwb in", values, "peijMcwb");
			return (Criteria) this;
		}

		public Criteria andPeijMcwbNotIn(List<String> values) {
			addCriterion("peij_mcwb not in", values, "peijMcwb");
			return (Criteria) this;
		}

		public Criteria andPeijMcwbBetween(String value1, String value2) {
			addCriterion("peij_mcwb between", value1, value2, "peijMcwb");
			return (Criteria) this;
		}

		public Criteria andPeijMcwbNotBetween(String value1, String value2) {
			addCriterion("peij_mcwb not between", value1, value2, "peijMcwb");
			return (Criteria) this;
		}

		public Criteria andPeijCxwbIsNull() {
			addCriterion("peij_cxwb is null");
			return (Criteria) this;
		}

		public Criteria andPeijCxwbIsNotNull() {
			addCriterion("peij_cxwb is not null");
			return (Criteria) this;
		}

		public Criteria andPeijCxwbEqualTo(String value) {
			addCriterion("peij_cxwb =", value, "peijCxwb");
			return (Criteria) this;
		}

		public Criteria andPeijCxwbNotEqualTo(String value) {
			addCriterion("peij_cxwb <>", value, "peijCxwb");
			return (Criteria) this;
		}

		public Criteria andPeijCxwbGreaterThan(String value) {
			addCriterion("peij_cxwb >", value, "peijCxwb");
			return (Criteria) this;
		}

		public Criteria andPeijCxwbGreaterThanOrEqualTo(String value) {
			addCriterion("peij_cxwb >=", value, "peijCxwb");
			return (Criteria) this;
		}

		public Criteria andPeijCxwbLessThan(String value) {
			addCriterion("peij_cxwb <", value, "peijCxwb");
			return (Criteria) this;
		}

		public Criteria andPeijCxwbLessThanOrEqualTo(String value) {
			addCriterion("peij_cxwb <=", value, "peijCxwb");
			return (Criteria) this;
		}

		public Criteria andPeijCxwbLike(String value) {
			addCriterion("peij_cxwb like", value, "peijCxwb");
			return (Criteria) this;
		}

		public Criteria andPeijCxwbNotLike(String value) {
			addCriterion("peij_cxwb not like", value, "peijCxwb");
			return (Criteria) this;
		}

		public Criteria andPeijCxwbIn(List<String> values) {
			addCriterion("peij_cxwb in", values, "peijCxwb");
			return (Criteria) this;
		}

		public Criteria andPeijCxwbNotIn(List<String> values) {
			addCriterion("peij_cxwb not in", values, "peijCxwb");
			return (Criteria) this;
		}

		public Criteria andPeijCxwbBetween(String value1, String value2) {
			addCriterion("peij_cxwb between", value1, value2, "peijCxwb");
			return (Criteria) this;
		}

		public Criteria andPeijCxwbNotBetween(String value1, String value2) {
			addCriterion("peij_cxwb not between", value1, value2, "peijCxwb");
			return (Criteria) this;
		}

		public Criteria andPeijScmcIsNull() {
			addCriterion("peij_scmc is null");
			return (Criteria) this;
		}

		public Criteria andPeijScmcIsNotNull() {
			addCriterion("peij_scmc is not null");
			return (Criteria) this;
		}

		public Criteria andPeijScmcEqualTo(String value) {
			addCriterion("peij_scmc =", value, "peijScmc");
			return (Criteria) this;
		}

		public Criteria andPeijScmcNotEqualTo(String value) {
			addCriterion("peij_scmc <>", value, "peijScmc");
			return (Criteria) this;
		}

		public Criteria andPeijScmcGreaterThan(String value) {
			addCriterion("peij_scmc >", value, "peijScmc");
			return (Criteria) this;
		}

		public Criteria andPeijScmcGreaterThanOrEqualTo(String value) {
			addCriterion("peij_scmc >=", value, "peijScmc");
			return (Criteria) this;
		}

		public Criteria andPeijScmcLessThan(String value) {
			addCriterion("peij_scmc <", value, "peijScmc");
			return (Criteria) this;
		}

		public Criteria andPeijScmcLessThanOrEqualTo(String value) {
			addCriterion("peij_scmc <=", value, "peijScmc");
			return (Criteria) this;
		}

		public Criteria andPeijScmcLike(String value) {
			addCriterion("peij_scmc like", value, "peijScmc");
			return (Criteria) this;
		}

		public Criteria andPeijScmcNotLike(String value) {
			addCriterion("peij_scmc not like", value, "peijScmc");
			return (Criteria) this;
		}

		public Criteria andPeijScmcIn(List<String> values) {
			addCriterion("peij_scmc in", values, "peijScmc");
			return (Criteria) this;
		}

		public Criteria andPeijScmcNotIn(List<String> values) {
			addCriterion("peij_scmc not in", values, "peijScmc");
			return (Criteria) this;
		}

		public Criteria andPeijScmcBetween(String value1, String value2) {
			addCriterion("peij_scmc between", value1, value2, "peijScmc");
			return (Criteria) this;
		}

		public Criteria andPeijScmcNotBetween(String value1, String value2) {
			addCriterion("peij_scmc not between", value1, value2, "peijScmc");
			return (Criteria) this;
		}
	}

	public static class Criteria extends GeneratedCriteria {

		protected Criteria() {
			super();
		}
	}

	public static class Criterion {
		private String condition;

		private Object value;

		private Object secondValue;

		private boolean noValue;

		private boolean singleValue;

		private boolean betweenValue;

		private boolean listValue;

		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}
}