package com.xym.bossed.db.mybatis.parts;

import java.io.Serializable;
import java.math.BigDecimal;

public class Parts implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = -4043122827408047210L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kucshp_info.peij_no
     *
     * @mbggenerated Wed Apr 23 18:32:26 CST 2014
     */
    private String peijNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kucshp_info.reco_no1
     *
     * @mbggenerated Wed Apr 23 18:32:26 CST 2014
     */
    private Long recoNo1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kucshp_info.peij_th
     *
     * @mbggenerated Wed Apr 23 18:32:26 CST 2014
     */
    private String peijTh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kucshp_info.peij_mc
     *
     * @mbggenerated Wed Apr 23 18:32:26 CST 2014
     */
    private String peijMc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kucshp_info.peij_en
     *
     * @mbggenerated Wed Apr 23 18:32:26 CST 2014
     */
    private String peijEn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kucshp_info.peijlb_mc
     *
     * @mbggenerated Wed Apr 23 18:32:26 CST 2014
     */
    private String peijlbMc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kucshp_info.peijlb_dm
     *
     * @mbggenerated Wed Apr 23 18:32:26 CST 2014
     */
    private String peijlbDm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kucshp_info.peij_py
     *
     * @mbggenerated Wed Apr 23 18:32:26 CST 2014
     */
    private String peijPy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kucshp_info.peij_dw
     *
     * @mbggenerated Wed Apr 23 18:32:26 CST 2014
     */
    private String peijDw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kucshp_info.peij_jk
     *
     * @mbggenerated Wed Apr 23 18:32:26 CST 2014
     */
    private String peijJk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kucshp_info.peij_cx
     *
     * @mbggenerated Wed Apr 23 18:32:26 CST 2014
     */
    private String peijCx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kucshp_info.peij_cd
     *
     * @mbggenerated Wed Apr 23 18:32:26 CST 2014
     */
    private String peijCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kucshp_info.peij_pp
     *
     * @mbggenerated Wed Apr 23 18:32:26 CST 2014
     */
    private String peijPp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kucshp_info.peij_th_ty
     *
     * @mbggenerated Wed Apr 23 18:32:26 CST 2014
     */
    private String peijThTy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kucshp_info.peij_cx_ty
     *
     * @mbggenerated Wed Apr 23 18:32:26 CST 2014
     */
    private String peijCxTy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kucshp_info.peij_zl
     *
     * @mbggenerated Wed Apr 23 18:32:26 CST 2014
     */
    private String peijZl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kucshp_info.peij_mb
     *
     * @mbggenerated Wed Apr 23 18:32:26 CST 2014
     */
    private String peijMb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kucshp_info.peij_sc
     *
     * @mbggenerated Wed Apr 23 18:32:26 CST 2014
     */
    private String peijSc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kucshp_info.peij_yc
     *
     * @mbggenerated Wed Apr 23 18:32:26 CST 2014
     */
    private String peijYc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kucshp_info.peij_xh
     *
     * @mbggenerated Wed Apr 23 18:32:26 CST 2014
     */
    private String peijXh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kucshp_info.peij_sh
     *
     * @mbggenerated Wed Apr 23 18:32:26 CST 2014
     */
    private String peijSh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kucshp_info.peij_shlv
     *
     * @mbggenerated Wed Apr 23 18:32:26 CST 2014
     */
    private BigDecimal peijShlv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kucshp_info.peij_bz
     *
     * @mbggenerated Wed Apr 23 18:32:26 CST 2014
     */
    private String peijBz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kucshp_info.peij_tiaoma
     *
     * @mbggenerated Wed Apr 23 18:32:26 CST 2014
     */
    private String peijTiaoma;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kucshp_info.peij_cl
     *
     * @mbggenerated Wed Apr 23 18:32:26 CST 2014
     */
    private String peijCl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kucshp_info.peij_zk
     *
     * @mbggenerated Wed Apr 23 18:32:26 CST 2014
     */
    private BigDecimal peijZk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kucshp_info.peij_TiChengLv
     *
     * @mbggenerated Wed Apr 23 18:32:26 CST 2014
     */
    private BigDecimal peijTichenglv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kucshp_info.peij_cxpy
     *
     * @mbggenerated Wed Apr 23 18:32:26 CST 2014
     */
    private String peijCxpy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kucshp_info.kehu_no
     *
     * @mbggenerated Wed Apr 23 18:32:26 CST 2014
     */
    private String kehuNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kucshp_info.kehu_mc
     *
     * @mbggenerated Wed Apr 23 18:32:26 CST 2014
     */
    private String kehuMc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kucshp_info.peij_mcwb
     *
     * @mbggenerated Wed Apr 23 18:32:26 CST 2014
     */
    private String peijMcwb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kucshp_info.peij_cxwb
     *
     * @mbggenerated Wed Apr 23 18:32:26 CST 2014
     */
    private String peijCxwb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kucshp_info.peij_scmc
     *
     * @mbggenerated Wed Apr 23 18:32:26 CST 2014
     */
    private String peijScmc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kucshp_info.peij_no
     *
     * @return the value of kucshp_info.peij_no
     *
     * @mbggenerated Wed Apr 23 18:32:26 CST 2014
     */
    public String getPeijNo() {
        return peijNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kucshp_info.peij_no
     *
     * @param peijNo the value for kucshp_info.peij_no
     *
     * @mbggenerated Wed Apr 23 18:32:26 CST 2014
     */
    public void setPeijNo(String peijNo) {
        this.peijNo = peijNo == null ? null : peijNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kucshp_info.reco_no1
     *
     * @return the value of kucshp_info.reco_no1
     *
     * @mbggenerated Wed Apr 23 18:32:26 CST 2014
     */
    public Long getRecoNo1() {
        return recoNo1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kucshp_info.reco_no1
     *
     * @param recoNo1 the value for kucshp_info.reco_no1
     *
     * @mbggenerated Wed Apr 23 18:32:26 CST 2014
     */
    public void setRecoNo1(Long recoNo1) {
        this.recoNo1 = recoNo1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kucshp_info.peij_th
     *
     * @return the value of kucshp_info.peij_th
     *
     * @mbggenerated Wed Apr 23 18:32:26 CST 2014
     */
    public String getPeijTh() {
        return peijTh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kucshp_info.peij_th
     *
     * @param peijTh the value for kucshp_info.peij_th
     *
     * @mbggenerated Wed Apr 23 18:32:26 CST 2014
     */
    public void setPeijTh(String peijTh) {
        this.peijTh = peijTh == null ? null : peijTh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kucshp_info.peij_mc
     *
     * @return the value of kucshp_info.peij_mc
     *
     * @mbggenerated Wed Apr 23 18:32:26 CST 2014
     */
    public String getPeijMc() {
        return peijMc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kucshp_info.peij_mc
     *
     * @param peijMc the value for kucshp_info.peij_mc
     *
     * @mbggenerated Wed Apr 23 18:32:26 CST 2014
     */
    public void setPeijMc(String peijMc) {
        this.peijMc = peijMc == null ? null : peijMc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kucshp_info.peij_en
     *
     * @return the value of kucshp_info.peij_en
     *
     * @mbggenerated Wed Apr 23 18:32:26 CST 2014
     */
    public String getPeijEn() {
        return peijEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kucshp_info.peij_en
     *
     * @param peijEn the value for kucshp_info.peij_en
     *
     * @mbggenerated Wed Apr 23 18:32:26 CST 2014
     */
    public void setPeijEn(String peijEn) {
        this.peijEn = peijEn == null ? null : peijEn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kucshp_info.peijlb_mc
     *
     * @return the value of kucshp_info.peijlb_mc
     *
     * @mbggenerated Wed Apr 23 18:32:26 CST 2014
     */
    public String getPeijlbMc() {
        return peijlbMc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kucshp_info.peijlb_mc
     *
     * @param peijlbMc the value for kucshp_info.peijlb_mc
     *
     * @mbggenerated Wed Apr 23 18:32:26 CST 2014
     */
    public void setPeijlbMc(String peijlbMc) {
        this.peijlbMc = peijlbMc == null ? null : peijlbMc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kucshp_info.peijlb_dm
     *
     * @return the value of kucshp_info.peijlb_dm
     *
     * @mbggenerated Wed Apr 23 18:32:26 CST 2014
     */
    public String getPeijlbDm() {
        return peijlbDm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kucshp_info.peijlb_dm
     *
     * @param peijlbDm the value for kucshp_info.peijlb_dm
     *
     * @mbggenerated Wed Apr 23 18:32:26 CST 2014
     */
    public void setPeijlbDm(String peijlbDm) {
        this.peijlbDm = peijlbDm == null ? null : peijlbDm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kucshp_info.peij_py
     *
     * @return the value of kucshp_info.peij_py
     *
     * @mbggenerated Wed Apr 23 18:32:26 CST 2014
     */
    public String getPeijPy() {
        return peijPy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kucshp_info.peij_py
     *
     * @param peijPy the value for kucshp_info.peij_py
     *
     * @mbggenerated Wed Apr 23 18:32:26 CST 2014
     */
    public void setPeijPy(String peijPy) {
        this.peijPy = peijPy == null ? null : peijPy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kucshp_info.peij_dw
     *
     * @return the value of kucshp_info.peij_dw
     *
     * @mbggenerated Wed Apr 23 18:32:26 CST 2014
     */
    public String getPeijDw() {
        return peijDw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kucshp_info.peij_dw
     *
     * @param peijDw the value for kucshp_info.peij_dw
     *
     * @mbggenerated Wed Apr 23 18:32:26 CST 2014
     */
    public void setPeijDw(String peijDw) {
        this.peijDw = peijDw == null ? null : peijDw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kucshp_info.peij_jk
     *
     * @return the value of kucshp_info.peij_jk
     *
     * @mbggenerated Wed Apr 23 18:32:26 CST 2014
     */
    public String getPeijJk() {
        return peijJk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kucshp_info.peij_jk
     *
     * @param peijJk the value for kucshp_info.peij_jk
     *
     * @mbggenerated Wed Apr 23 18:32:26 CST 2014
     */
    public void setPeijJk(String peijJk) {
        this.peijJk = peijJk == null ? null : peijJk.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kucshp_info.peij_cx
     *
     * @return the value of kucshp_info.peij_cx
     *
     * @mbggenerated Wed Apr 23 18:32:26 CST 2014
     */
    public String getPeijCx() {
        return peijCx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kucshp_info.peij_cx
     *
     * @param peijCx the value for kucshp_info.peij_cx
     *
     * @mbggenerated Wed Apr 23 18:32:26 CST 2014
     */
    public void setPeijCx(String peijCx) {
        this.peijCx = peijCx == null ? null : peijCx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kucshp_info.peij_cd
     *
     * @return the value of kucshp_info.peij_cd
     *
     * @mbggenerated Wed Apr 23 18:32:26 CST 2014
     */
    public String getPeijCd() {
        return peijCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kucshp_info.peij_cd
     *
     * @param peijCd the value for kucshp_info.peij_cd
     *
     * @mbggenerated Wed Apr 23 18:32:26 CST 2014
     */
    public void setPeijCd(String peijCd) {
        this.peijCd = peijCd == null ? null : peijCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kucshp_info.peij_pp
     *
     * @return the value of kucshp_info.peij_pp
     *
     * @mbggenerated Wed Apr 23 18:32:26 CST 2014
     */
    public String getPeijPp() {
        return peijPp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kucshp_info.peij_pp
     *
     * @param peijPp the value for kucshp_info.peij_pp
     *
     * @mbggenerated Wed Apr 23 18:32:26 CST 2014
     */
    public void setPeijPp(String peijPp) {
        this.peijPp = peijPp == null ? null : peijPp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kucshp_info.peij_th_ty
     *
     * @return the value of kucshp_info.peij_th_ty
     *
     * @mbggenerated Wed Apr 23 18:32:26 CST 2014
     */
    public String getPeijThTy() {
        return peijThTy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kucshp_info.peij_th_ty
     *
     * @param peijThTy the value for kucshp_info.peij_th_ty
     *
     * @mbggenerated Wed Apr 23 18:32:26 CST 2014
     */
    public void setPeijThTy(String peijThTy) {
        this.peijThTy = peijThTy == null ? null : peijThTy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kucshp_info.peij_cx_ty
     *
     * @return the value of kucshp_info.peij_cx_ty
     *
     * @mbggenerated Wed Apr 23 18:32:26 CST 2014
     */
    public String getPeijCxTy() {
        return peijCxTy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kucshp_info.peij_cx_ty
     *
     * @param peijCxTy the value for kucshp_info.peij_cx_ty
     *
     * @mbggenerated Wed Apr 23 18:32:26 CST 2014
     */
    public void setPeijCxTy(String peijCxTy) {
        this.peijCxTy = peijCxTy == null ? null : peijCxTy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kucshp_info.peij_zl
     *
     * @return the value of kucshp_info.peij_zl
     *
     * @mbggenerated Wed Apr 23 18:32:26 CST 2014
     */
    public String getPeijZl() {
        return peijZl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kucshp_info.peij_zl
     *
     * @param peijZl the value for kucshp_info.peij_zl
     *
     * @mbggenerated Wed Apr 23 18:32:26 CST 2014
     */
    public void setPeijZl(String peijZl) {
        this.peijZl = peijZl == null ? null : peijZl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kucshp_info.peij_mb
     *
     * @return the value of kucshp_info.peij_mb
     *
     * @mbggenerated Wed Apr 23 18:32:26 CST 2014
     */
    public String getPeijMb() {
        return peijMb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kucshp_info.peij_mb
     *
     * @param peijMb the value for kucshp_info.peij_mb
     *
     * @mbggenerated Wed Apr 23 18:32:26 CST 2014
     */
    public void setPeijMb(String peijMb) {
        this.peijMb = peijMb == null ? null : peijMb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kucshp_info.peij_sc
     *
     * @return the value of kucshp_info.peij_sc
     *
     * @mbggenerated Wed Apr 23 18:32:26 CST 2014
     */
    public String getPeijSc() {
        return peijSc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kucshp_info.peij_sc
     *
     * @param peijSc the value for kucshp_info.peij_sc
     *
     * @mbggenerated Wed Apr 23 18:32:26 CST 2014
     */
    public void setPeijSc(String peijSc) {
        this.peijSc = peijSc == null ? null : peijSc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kucshp_info.peij_yc
     *
     * @return the value of kucshp_info.peij_yc
     *
     * @mbggenerated Wed Apr 23 18:32:26 CST 2014
     */
    public String getPeijYc() {
        return peijYc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kucshp_info.peij_yc
     *
     * @param peijYc the value for kucshp_info.peij_yc
     *
     * @mbggenerated Wed Apr 23 18:32:26 CST 2014
     */
    public void setPeijYc(String peijYc) {
        this.peijYc = peijYc == null ? null : peijYc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kucshp_info.peij_xh
     *
     * @return the value of kucshp_info.peij_xh
     *
     * @mbggenerated Wed Apr 23 18:32:26 CST 2014
     */
    public String getPeijXh() {
        return peijXh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kucshp_info.peij_xh
     *
     * @param peijXh the value for kucshp_info.peij_xh
     *
     * @mbggenerated Wed Apr 23 18:32:26 CST 2014
     */
    public void setPeijXh(String peijXh) {
        this.peijXh = peijXh == null ? null : peijXh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kucshp_info.peij_sh
     *
     * @return the value of kucshp_info.peij_sh
     *
     * @mbggenerated Wed Apr 23 18:32:26 CST 2014
     */
    public String getPeijSh() {
        return peijSh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kucshp_info.peij_sh
     *
     * @param peijSh the value for kucshp_info.peij_sh
     *
     * @mbggenerated Wed Apr 23 18:32:26 CST 2014
     */
    public void setPeijSh(String peijSh) {
        this.peijSh = peijSh == null ? null : peijSh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kucshp_info.peij_shlv
     *
     * @return the value of kucshp_info.peij_shlv
     *
     * @mbggenerated Wed Apr 23 18:32:26 CST 2014
     */
    public BigDecimal getPeijShlv() {
        return peijShlv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kucshp_info.peij_shlv
     *
     * @param peijShlv the value for kucshp_info.peij_shlv
     *
     * @mbggenerated Wed Apr 23 18:32:26 CST 2014
     */
    public void setPeijShlv(BigDecimal peijShlv) {
        this.peijShlv = peijShlv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kucshp_info.peij_bz
     *
     * @return the value of kucshp_info.peij_bz
     *
     * @mbggenerated Wed Apr 23 18:32:26 CST 2014
     */
    public String getPeijBz() {
        return peijBz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kucshp_info.peij_bz
     *
     * @param peijBz the value for kucshp_info.peij_bz
     *
     * @mbggenerated Wed Apr 23 18:32:26 CST 2014
     */
    public void setPeijBz(String peijBz) {
        this.peijBz = peijBz == null ? null : peijBz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kucshp_info.peij_tiaoma
     *
     * @return the value of kucshp_info.peij_tiaoma
     *
     * @mbggenerated Wed Apr 23 18:32:26 CST 2014
     */
    public String getPeijTiaoma() {
        return peijTiaoma;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kucshp_info.peij_tiaoma
     *
     * @param peijTiaoma the value for kucshp_info.peij_tiaoma
     *
     * @mbggenerated Wed Apr 23 18:32:26 CST 2014
     */
    public void setPeijTiaoma(String peijTiaoma) {
        this.peijTiaoma = peijTiaoma == null ? null : peijTiaoma.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kucshp_info.peij_cl
     *
     * @return the value of kucshp_info.peij_cl
     *
     * @mbggenerated Wed Apr 23 18:32:26 CST 2014
     */
    public String getPeijCl() {
        return peijCl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kucshp_info.peij_cl
     *
     * @param peijCl the value for kucshp_info.peij_cl
     *
     * @mbggenerated Wed Apr 23 18:32:26 CST 2014
     */
    public void setPeijCl(String peijCl) {
        this.peijCl = peijCl == null ? null : peijCl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kucshp_info.peij_zk
     *
     * @return the value of kucshp_info.peij_zk
     *
     * @mbggenerated Wed Apr 23 18:32:26 CST 2014
     */
    public BigDecimal getPeijZk() {
        return peijZk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kucshp_info.peij_zk
     *
     * @param peijZk the value for kucshp_info.peij_zk
     *
     * @mbggenerated Wed Apr 23 18:32:26 CST 2014
     */
    public void setPeijZk(BigDecimal peijZk) {
        this.peijZk = peijZk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kucshp_info.peij_TiChengLv
     *
     * @return the value of kucshp_info.peij_TiChengLv
     *
     * @mbggenerated Wed Apr 23 18:32:26 CST 2014
     */
    public BigDecimal getPeijTichenglv() {
        return peijTichenglv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kucshp_info.peij_TiChengLv
     *
     * @param peijTichenglv the value for kucshp_info.peij_TiChengLv
     *
     * @mbggenerated Wed Apr 23 18:32:26 CST 2014
     */
    public void setPeijTichenglv(BigDecimal peijTichenglv) {
        this.peijTichenglv = peijTichenglv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kucshp_info.peij_cxpy
     *
     * @return the value of kucshp_info.peij_cxpy
     *
     * @mbggenerated Wed Apr 23 18:32:26 CST 2014
     */
    public String getPeijCxpy() {
        return peijCxpy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kucshp_info.peij_cxpy
     *
     * @param peijCxpy the value for kucshp_info.peij_cxpy
     *
     * @mbggenerated Wed Apr 23 18:32:26 CST 2014
     */
    public void setPeijCxpy(String peijCxpy) {
        this.peijCxpy = peijCxpy == null ? null : peijCxpy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kucshp_info.kehu_no
     *
     * @return the value of kucshp_info.kehu_no
     *
     * @mbggenerated Wed Apr 23 18:32:26 CST 2014
     */
    public String getKehuNo() {
        return kehuNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kucshp_info.kehu_no
     *
     * @param kehuNo the value for kucshp_info.kehu_no
     *
     * @mbggenerated Wed Apr 23 18:32:26 CST 2014
     */
    public void setKehuNo(String kehuNo) {
        this.kehuNo = kehuNo == null ? null : kehuNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kucshp_info.kehu_mc
     *
     * @return the value of kucshp_info.kehu_mc
     *
     * @mbggenerated Wed Apr 23 18:32:26 CST 2014
     */
    public String getKehuMc() {
        return kehuMc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kucshp_info.kehu_mc
     *
     * @param kehuMc the value for kucshp_info.kehu_mc
     *
     * @mbggenerated Wed Apr 23 18:32:26 CST 2014
     */
    public void setKehuMc(String kehuMc) {
        this.kehuMc = kehuMc == null ? null : kehuMc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kucshp_info.peij_mcwb
     *
     * @return the value of kucshp_info.peij_mcwb
     *
     * @mbggenerated Wed Apr 23 18:32:26 CST 2014
     */
    public String getPeijMcwb() {
        return peijMcwb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kucshp_info.peij_mcwb
     *
     * @param peijMcwb the value for kucshp_info.peij_mcwb
     *
     * @mbggenerated Wed Apr 23 18:32:26 CST 2014
     */
    public void setPeijMcwb(String peijMcwb) {
        this.peijMcwb = peijMcwb == null ? null : peijMcwb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kucshp_info.peij_cxwb
     *
     * @return the value of kucshp_info.peij_cxwb
     *
     * @mbggenerated Wed Apr 23 18:32:26 CST 2014
     */
    public String getPeijCxwb() {
        return peijCxwb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kucshp_info.peij_cxwb
     *
     * @param peijCxwb the value for kucshp_info.peij_cxwb
     *
     * @mbggenerated Wed Apr 23 18:32:26 CST 2014
     */
    public void setPeijCxwb(String peijCxwb) {
        this.peijCxwb = peijCxwb == null ? null : peijCxwb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kucshp_info.peij_scmc
     *
     * @return the value of kucshp_info.peij_scmc
     *
     * @mbggenerated Wed Apr 23 18:32:26 CST 2014
     */
    public String getPeijScmc() {
        return peijScmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kucshp_info.peij_scmc
     *
     * @param peijScmc the value for kucshp_info.peij_scmc
     *
     * @mbggenerated Wed Apr 23 18:32:26 CST 2014
     */
    public void setPeijScmc(String peijScmc) {
        this.peijScmc = peijScmc == null ? null : peijScmc.trim();
    }
}