package com.xym.bossed.db.mybatis.fapiao;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

import com.xym.bossed.db.mybatis.kehu.Kehu;

public class FaPiao implements Serializable{

	/**
	 * 
	 */
	private static final long serialVersionUID = 6174923549900910947L;

	private Kehu kehu;

	public Kehu getKehu() {
		return kehu;
	}

	public void setKehu(Kehu kehu) {
		this.kehu = kehu;
	}

	private int save_Return_Value;

	public int getSave_Return_Value() {
		return save_Return_Value;
	}

	public void setSave_Return_Value(int save_Return_Value) {
		this.save_Return_Value = save_Return_Value;
	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column fapiao_kp_pz.reco_no
	 * 
	 * @mbggenerated Wed May 29 15:33:28 CST 2013
	 */
	private Long recoNo;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column fapiao_kp_pz.kaip_no
	 * 
	 * @mbggenerated Wed May 29 15:33:28 CST 2013
	 */
	private String kaipNo;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column fapiao_kp_pz.kehu_no
	 * 
	 * @mbggenerated Wed May 29 15:33:28 CST 2013
	 */
	private String kehuNo;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column fapiao_kp_pz.kaip_rq
	 * 
	 * @mbggenerated Wed May 29 15:33:28 CST 2013
	 */
	private Date kaipRq;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column fapiao_kp_pz.kaip_zy
	 * 
	 * @mbggenerated Wed May 29 15:33:28 CST 2013
	 */
	private String kaipZy;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column fapiao_kp_pz.kaip_fpmc
	 * 
	 * @mbggenerated Wed May 29 15:33:28 CST 2013
	 */
	private String kaipFpmc;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column fapiao_kp_pz.kaip_fpno
	 * 
	 * @mbggenerated Wed May 29 15:33:28 CST 2013
	 */
	private String kaipFpno;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column fapiao_kp_pz.kaip_jfje
	 * 
	 * @mbggenerated Wed May 29 15:33:28 CST 2013
	 */
	private BigDecimal kaipJfje;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column fapiao_kp_pz.kaip_jfse
	 * 
	 * @mbggenerated Wed May 29 15:33:28 CST 2013
	 */
	private BigDecimal kaipJfse;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column fapiao_kp_pz.kaip_dfje
	 * 
	 * @mbggenerated Wed May 29 15:33:28 CST 2013
	 */
	private BigDecimal kaipDfje;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column fapiao_kp_pz.kaip_dfse
	 * 
	 * @mbggenerated Wed May 29 15:33:28 CST 2013
	 */
	private BigDecimal kaipDfse;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column fapiao_kp_pz.kaip_yuje
	 * 
	 * @mbggenerated Wed May 29 15:33:28 CST 2013
	 */
	private BigDecimal kaipYuje;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column fapiao_kp_pz.kaip_yuse
	 * 
	 * @mbggenerated Wed May 29 15:33:28 CST 2013
	 */
	private BigDecimal kaipYuse;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column fapiao_kp_pz.kaip_validity
	 * 
	 * @mbggenerated Wed May 29 15:33:28 CST 2013
	 */
	private Boolean kaipValidity;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column fapiao_kp_pz.kaip_xz
	 * 
	 * @mbggenerated Wed May 29 15:33:28 CST 2013
	 */
	private Integer kaipXz;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column fapiao_kp_pz.kaip_jb
	 * 
	 * @mbggenerated Wed May 29 15:33:28 CST 2013
	 */
	private String kaipJb;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column fapiao_kp_pz.kaip_czy
	 * 
	 * @mbggenerated Wed May 29 15:33:28 CST 2013
	 */
	private String kaipCzy;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column fapiao_kp_pz.dept_mc
	 * 
	 * @mbggenerated Wed May 29 15:33:28 CST 2013
	 */
	private String deptMc;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column fapiao_kp_pz.kaip_bz
	 * 
	 * @mbggenerated Wed May 29 15:33:28 CST 2013
	 */
	private String kaipBz;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column fapiao_kp_pz.kaip_qm
	 * 
	 * @mbggenerated Wed May 29 15:33:28 CST 2013
	 */
	private BigDecimal kaipQm;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column fapiao_kp_pz.kaip_bcje
	 * 
	 * @mbggenerated Wed May 29 15:33:28 CST 2013
	 */
	private BigDecimal kaipBcje;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column fapiao_kp_pz.kaip_miankaije
	 * 
	 * @mbggenerated Wed May 29 15:33:28 CST 2013
	 */
	private BigDecimal kaipMiankaije;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column fapiao_kp_pz.kaip_miankaise
	 * 
	 * @mbggenerated Wed May 29 15:33:28 CST 2013
	 */
	private BigDecimal kaipMiankaise;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column fapiao_kp_pz.reco_no
	 * 
	 * @return the value of fapiao_kp_pz.reco_no
	 * 
	 * @mbggenerated Wed May 29 15:33:28 CST 2013
	 */
	public Long getRecoNo() {
		return recoNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column fapiao_kp_pz.reco_no
	 * 
	 * @param recoNo
	 *            the value for fapiao_kp_pz.reco_no
	 * 
	 * @mbggenerated Wed May 29 15:33:28 CST 2013
	 */
	public void setRecoNo(Long recoNo) {
		this.recoNo = recoNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column fapiao_kp_pz.kaip_no
	 * 
	 * @return the value of fapiao_kp_pz.kaip_no
	 * 
	 * @mbggenerated Wed May 29 15:33:28 CST 2013
	 */
	public String getKaipNo() {
		return kaipNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column fapiao_kp_pz.kaip_no
	 * 
	 * @param kaipNo
	 *            the value for fapiao_kp_pz.kaip_no
	 * 
	 * @mbggenerated Wed May 29 15:33:28 CST 2013
	 */
	public void setKaipNo(String kaipNo) {
		this.kaipNo = kaipNo == null ? null : kaipNo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column fapiao_kp_pz.kehu_no
	 * 
	 * @return the value of fapiao_kp_pz.kehu_no
	 * 
	 * @mbggenerated Wed May 29 15:33:28 CST 2013
	 */
	public String getKehuNo() {
		return kehuNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column fapiao_kp_pz.kehu_no
	 * 
	 * @param kehuNo
	 *            the value for fapiao_kp_pz.kehu_no
	 * 
	 * @mbggenerated Wed May 29 15:33:28 CST 2013
	 */
	public void setKehuNo(String kehuNo) {
		this.kehuNo = kehuNo == null ? null : kehuNo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column fapiao_kp_pz.kaip_rq
	 * 
	 * @return the value of fapiao_kp_pz.kaip_rq
	 * 
	 * @mbggenerated Wed May 29 15:33:28 CST 2013
	 */
	public Date getKaipRq() {
		return kaipRq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column fapiao_kp_pz.kaip_rq
	 * 
	 * @param kaipRq
	 *            the value for fapiao_kp_pz.kaip_rq
	 * 
	 * @mbggenerated Wed May 29 15:33:28 CST 2013
	 */
	public void setKaipRq(Date kaipRq) {
		this.kaipRq = kaipRq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column fapiao_kp_pz.kaip_zy
	 * 
	 * @return the value of fapiao_kp_pz.kaip_zy
	 * 
	 * @mbggenerated Wed May 29 15:33:28 CST 2013
	 */
	public String getKaipZy() {
		return kaipZy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column fapiao_kp_pz.kaip_zy
	 * 
	 * @param kaipZy
	 *            the value for fapiao_kp_pz.kaip_zy
	 * 
	 * @mbggenerated Wed May 29 15:33:28 CST 2013
	 */
	public void setKaipZy(String kaipZy) {
		this.kaipZy = kaipZy == null ? null : kaipZy.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column fapiao_kp_pz.kaip_fpmc
	 * 
	 * @return the value of fapiao_kp_pz.kaip_fpmc
	 * 
	 * @mbggenerated Wed May 29 15:33:28 CST 2013
	 */
	public String getKaipFpmc() {
		return kaipFpmc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column fapiao_kp_pz.kaip_fpmc
	 * 
	 * @param kaipFpmc
	 *            the value for fapiao_kp_pz.kaip_fpmc
	 * 
	 * @mbggenerated Wed May 29 15:33:28 CST 2013
	 */
	public void setKaipFpmc(String kaipFpmc) {
		this.kaipFpmc = kaipFpmc == null ? null : kaipFpmc.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column fapiao_kp_pz.kaip_fpno
	 * 
	 * @return the value of fapiao_kp_pz.kaip_fpno
	 * 
	 * @mbggenerated Wed May 29 15:33:28 CST 2013
	 */
	public String getKaipFpno() {
		return kaipFpno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column fapiao_kp_pz.kaip_fpno
	 * 
	 * @param kaipFpno
	 *            the value for fapiao_kp_pz.kaip_fpno
	 * 
	 * @mbggenerated Wed May 29 15:33:28 CST 2013
	 */
	public void setKaipFpno(String kaipFpno) {
		this.kaipFpno = kaipFpno == null ? null : kaipFpno.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column fapiao_kp_pz.kaip_jfje
	 * 
	 * @return the value of fapiao_kp_pz.kaip_jfje
	 * 
	 * @mbggenerated Wed May 29 15:33:28 CST 2013
	 */
	public BigDecimal getKaipJfje() {
		return kaipJfje;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column fapiao_kp_pz.kaip_jfje
	 * 
	 * @param kaipJfje
	 *            the value for fapiao_kp_pz.kaip_jfje
	 * 
	 * @mbggenerated Wed May 29 15:33:28 CST 2013
	 */
	public void setKaipJfje(BigDecimal kaipJfje) {
		this.kaipJfje = kaipJfje;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column fapiao_kp_pz.kaip_jfse
	 * 
	 * @return the value of fapiao_kp_pz.kaip_jfse
	 * 
	 * @mbggenerated Wed May 29 15:33:28 CST 2013
	 */
	public BigDecimal getKaipJfse() {
		return kaipJfse;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column fapiao_kp_pz.kaip_jfse
	 * 
	 * @param kaipJfse
	 *            the value for fapiao_kp_pz.kaip_jfse
	 * 
	 * @mbggenerated Wed May 29 15:33:28 CST 2013
	 */
	public void setKaipJfse(BigDecimal kaipJfse) {
		this.kaipJfse = kaipJfse;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column fapiao_kp_pz.kaip_dfje
	 * 
	 * @return the value of fapiao_kp_pz.kaip_dfje
	 * 
	 * @mbggenerated Wed May 29 15:33:28 CST 2013
	 */
	public BigDecimal getKaipDfje() {
		return kaipDfje;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column fapiao_kp_pz.kaip_dfje
	 * 
	 * @param kaipDfje
	 *            the value for fapiao_kp_pz.kaip_dfje
	 * 
	 * @mbggenerated Wed May 29 15:33:28 CST 2013
	 */
	public void setKaipDfje(BigDecimal kaipDfje) {
		this.kaipDfje = kaipDfje;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column fapiao_kp_pz.kaip_dfse
	 * 
	 * @return the value of fapiao_kp_pz.kaip_dfse
	 * 
	 * @mbggenerated Wed May 29 15:33:28 CST 2013
	 */
	public BigDecimal getKaipDfse() {
		return kaipDfse;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column fapiao_kp_pz.kaip_dfse
	 * 
	 * @param kaipDfse
	 *            the value for fapiao_kp_pz.kaip_dfse
	 * 
	 * @mbggenerated Wed May 29 15:33:28 CST 2013
	 */
	public void setKaipDfse(BigDecimal kaipDfse) {
		this.kaipDfse = kaipDfse;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column fapiao_kp_pz.kaip_yuje
	 * 
	 * @return the value of fapiao_kp_pz.kaip_yuje
	 * 
	 * @mbggenerated Wed May 29 15:33:28 CST 2013
	 */
	public BigDecimal getKaipYuje() {
		return kaipYuje;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column fapiao_kp_pz.kaip_yuje
	 * 
	 * @param kaipYuje
	 *            the value for fapiao_kp_pz.kaip_yuje
	 * 
	 * @mbggenerated Wed May 29 15:33:28 CST 2013
	 */
	public void setKaipYuje(BigDecimal kaipYuje) {
		this.kaipYuje = kaipYuje;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column fapiao_kp_pz.kaip_yuse
	 * 
	 * @return the value of fapiao_kp_pz.kaip_yuse
	 * 
	 * @mbggenerated Wed May 29 15:33:28 CST 2013
	 */
	public BigDecimal getKaipYuse() {
		return kaipYuse;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column fapiao_kp_pz.kaip_yuse
	 * 
	 * @param kaipYuse
	 *            the value for fapiao_kp_pz.kaip_yuse
	 * 
	 * @mbggenerated Wed May 29 15:33:28 CST 2013
	 */
	public void setKaipYuse(BigDecimal kaipYuse) {
		this.kaipYuse = kaipYuse;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column fapiao_kp_pz.kaip_validity
	 * 
	 * @return the value of fapiao_kp_pz.kaip_validity
	 * 
	 * @mbggenerated Wed May 29 15:33:28 CST 2013
	 */
	public Boolean getKaipValidity() {
		return kaipValidity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column fapiao_kp_pz.kaip_validity
	 * 
	 * @param kaipValidity
	 *            the value for fapiao_kp_pz.kaip_validity
	 * 
	 * @mbggenerated Wed May 29 15:33:28 CST 2013
	 */
	public void setKaipValidity(Boolean kaipValidity) {
		this.kaipValidity = kaipValidity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column fapiao_kp_pz.kaip_xz
	 * 
	 * @return the value of fapiao_kp_pz.kaip_xz
	 * 
	 * @mbggenerated Wed May 29 15:33:28 CST 2013
	 */
	public Integer getKaipXz() {
		return kaipXz;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column fapiao_kp_pz.kaip_xz
	 * 
	 * @param kaipXz
	 *            the value for fapiao_kp_pz.kaip_xz
	 * 
	 * @mbggenerated Wed May 29 15:33:28 CST 2013
	 */
	public void setKaipXz(Integer kaipXz) {
		this.kaipXz = kaipXz;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column fapiao_kp_pz.kaip_jb
	 * 
	 * @return the value of fapiao_kp_pz.kaip_jb
	 * 
	 * @mbggenerated Wed May 29 15:33:28 CST 2013
	 */
	public String getKaipJb() {
		return kaipJb;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column fapiao_kp_pz.kaip_jb
	 * 
	 * @param kaipJb
	 *            the value for fapiao_kp_pz.kaip_jb
	 * 
	 * @mbggenerated Wed May 29 15:33:28 CST 2013
	 */
	public void setKaipJb(String kaipJb) {
		this.kaipJb = kaipJb == null ? null : kaipJb.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column fapiao_kp_pz.kaip_czy
	 * 
	 * @return the value of fapiao_kp_pz.kaip_czy
	 * 
	 * @mbggenerated Wed May 29 15:33:28 CST 2013
	 */
	public String getKaipCzy() {
		return kaipCzy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column fapiao_kp_pz.kaip_czy
	 * 
	 * @param kaipCzy
	 *            the value for fapiao_kp_pz.kaip_czy
	 * 
	 * @mbggenerated Wed May 29 15:33:28 CST 2013
	 */
	public void setKaipCzy(String kaipCzy) {
		this.kaipCzy = kaipCzy == null ? null : kaipCzy.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column fapiao_kp_pz.dept_mc
	 * 
	 * @return the value of fapiao_kp_pz.dept_mc
	 * 
	 * @mbggenerated Wed May 29 15:33:28 CST 2013
	 */
	public String getDeptMc() {
		return deptMc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column fapiao_kp_pz.dept_mc
	 * 
	 * @param deptMc
	 *            the value for fapiao_kp_pz.dept_mc
	 * 
	 * @mbggenerated Wed May 29 15:33:28 CST 2013
	 */
	public void setDeptMc(String deptMc) {
		this.deptMc = deptMc == null ? null : deptMc.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column fapiao_kp_pz.kaip_bz
	 * 
	 * @return the value of fapiao_kp_pz.kaip_bz
	 * 
	 * @mbggenerated Wed May 29 15:33:28 CST 2013
	 */
	public String getKaipBz() {
		return kaipBz;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column fapiao_kp_pz.kaip_bz
	 * 
	 * @param kaipBz
	 *            the value for fapiao_kp_pz.kaip_bz
	 * 
	 * @mbggenerated Wed May 29 15:33:28 CST 2013
	 */
	public void setKaipBz(String kaipBz) {
		this.kaipBz = kaipBz == null ? null : kaipBz.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column fapiao_kp_pz.kaip_qm
	 * 
	 * @return the value of fapiao_kp_pz.kaip_qm
	 * 
	 * @mbggenerated Wed May 29 15:33:28 CST 2013
	 */
	public BigDecimal getKaipQm() {
		return kaipQm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column fapiao_kp_pz.kaip_qm
	 * 
	 * @param kaipQm
	 *            the value for fapiao_kp_pz.kaip_qm
	 * 
	 * @mbggenerated Wed May 29 15:33:28 CST 2013
	 */
	public void setKaipQm(BigDecimal kaipQm) {
		this.kaipQm = kaipQm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column fapiao_kp_pz.kaip_bcje
	 * 
	 * @return the value of fapiao_kp_pz.kaip_bcje
	 * 
	 * @mbggenerated Wed May 29 15:33:28 CST 2013
	 */
	public BigDecimal getKaipBcje() {
		return kaipBcje;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column fapiao_kp_pz.kaip_bcje
	 * 
	 * @param kaipBcje
	 *            the value for fapiao_kp_pz.kaip_bcje
	 * 
	 * @mbggenerated Wed May 29 15:33:28 CST 2013
	 */
	public void setKaipBcje(BigDecimal kaipBcje) {
		this.kaipBcje = kaipBcje;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column fapiao_kp_pz.kaip_miankaije
	 * 
	 * @return the value of fapiao_kp_pz.kaip_miankaije
	 * 
	 * @mbggenerated Wed May 29 15:33:28 CST 2013
	 */
	public BigDecimal getKaipMiankaije() {
		return kaipMiankaije;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column fapiao_kp_pz.kaip_miankaije
	 * 
	 * @param kaipMiankaije
	 *            the value for fapiao_kp_pz.kaip_miankaije
	 * 
	 * @mbggenerated Wed May 29 15:33:28 CST 2013
	 */
	public void setKaipMiankaije(BigDecimal kaipMiankaije) {
		this.kaipMiankaije = kaipMiankaije;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column fapiao_kp_pz.kaip_miankaise
	 * 
	 * @return the value of fapiao_kp_pz.kaip_miankaise
	 * 
	 * @mbggenerated Wed May 29 15:33:28 CST 2013
	 */
	public BigDecimal getKaipMiankaise() {
		return kaipMiankaise;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column fapiao_kp_pz.kaip_miankaise
	 * 
	 * @param kaipMiankaise
	 *            the value for fapiao_kp_pz.kaip_miankaise
	 * 
	 * @mbggenerated Wed May 29 15:33:28 CST 2013
	 */
	public void setKaipMiankaise(BigDecimal kaipMiankaise) {
		this.kaipMiankaise = kaipMiankaise;
	}
}