package com.xym.bossed.db.mybatis.log;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_log
     *
     * @mbggenerated Thu Sep 05 14:09:09 CST 2013
     */
    int countByExample(LogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_log
     *
     * @mbggenerated Thu Sep 05 14:09:09 CST 2013
     */
    int deleteByExample(LogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_log
     *
     * @mbggenerated Thu Sep 05 14:09:09 CST 2013
     */
    int insert(Log record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_log
     *
     * @mbggenerated Thu Sep 05 14:09:09 CST 2013
     */
    int insertSelective(Log record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_log
     *
     * @mbggenerated Thu Sep 05 14:09:09 CST 2013
     */
    List<Log> selectByExample(LogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_log
     *
     * @mbggenerated Thu Sep 05 14:09:09 CST 2013
     */
    int updateByExampleSelective(@Param("record") Log record, @Param("example") LogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_log
     *
     * @mbggenerated Thu Sep 05 14:09:09 CST 2013
     */
    int updateByExample(@Param("record") Log record, @Param("example") LogExample example);
}