package com.xym.bossed.db.mybatis.parts.category;

import java.util.ArrayList;
import java.util.List;

public class PartsCategoryExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sm_peijlb
     *
     * @mbggenerated Wed Apr 09 06:29:40 CST 2014
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sm_peijlb
     *
     * @mbggenerated Wed Apr 09 06:29:40 CST 2014
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sm_peijlb
     *
     * @mbggenerated Wed Apr 09 06:29:40 CST 2014
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_peijlb
     *
     * @mbggenerated Wed Apr 09 06:29:40 CST 2014
     */
    public PartsCategoryExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_peijlb
     *
     * @mbggenerated Wed Apr 09 06:29:40 CST 2014
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_peijlb
     *
     * @mbggenerated Wed Apr 09 06:29:40 CST 2014
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_peijlb
     *
     * @mbggenerated Wed Apr 09 06:29:40 CST 2014
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_peijlb
     *
     * @mbggenerated Wed Apr 09 06:29:40 CST 2014
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_peijlb
     *
     * @mbggenerated Wed Apr 09 06:29:40 CST 2014
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_peijlb
     *
     * @mbggenerated Wed Apr 09 06:29:40 CST 2014
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_peijlb
     *
     * @mbggenerated Wed Apr 09 06:29:40 CST 2014
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_peijlb
     *
     * @mbggenerated Wed Apr 09 06:29:40 CST 2014
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_peijlb
     *
     * @mbggenerated Wed Apr 09 06:29:40 CST 2014
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_peijlb
     *
     * @mbggenerated Wed Apr 09 06:29:40 CST 2014
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sm_peijlb
     *
     * @mbggenerated Wed Apr 09 06:29:40 CST 2014
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPeijlbDmIsNull() {
            addCriterion("peijlb_dm is null");
            return (Criteria) this;
        }

        public Criteria andPeijlbDmIsNotNull() {
            addCriterion("peijlb_dm is not null");
            return (Criteria) this;
        }

        public Criteria andPeijlbDmEqualTo(String value) {
            addCriterion("peijlb_dm =", value, "peijlbDm");
            return (Criteria) this;
        }

        public Criteria andPeijlbDmNotEqualTo(String value) {
            addCriterion("peijlb_dm <>", value, "peijlbDm");
            return (Criteria) this;
        }

        public Criteria andPeijlbDmGreaterThan(String value) {
            addCriterion("peijlb_dm >", value, "peijlbDm");
            return (Criteria) this;
        }

        public Criteria andPeijlbDmGreaterThanOrEqualTo(String value) {
            addCriterion("peijlb_dm >=", value, "peijlbDm");
            return (Criteria) this;
        }

        public Criteria andPeijlbDmLessThan(String value) {
            addCriterion("peijlb_dm <", value, "peijlbDm");
            return (Criteria) this;
        }

        public Criteria andPeijlbDmLessThanOrEqualTo(String value) {
            addCriterion("peijlb_dm <=", value, "peijlbDm");
            return (Criteria) this;
        }

        public Criteria andPeijlbDmLike(String value) {
            addCriterion("peijlb_dm like", value, "peijlbDm");
            return (Criteria) this;
        }

        public Criteria andPeijlbDmNotLike(String value) {
            addCriterion("peijlb_dm not like", value, "peijlbDm");
            return (Criteria) this;
        }

        public Criteria andPeijlbDmIn(List<String> values) {
            addCriterion("peijlb_dm in", values, "peijlbDm");
            return (Criteria) this;
        }

        public Criteria andPeijlbDmNotIn(List<String> values) {
            addCriterion("peijlb_dm not in", values, "peijlbDm");
            return (Criteria) this;
        }

        public Criteria andPeijlbDmBetween(String value1, String value2) {
            addCriterion("peijlb_dm between", value1, value2, "peijlbDm");
            return (Criteria) this;
        }

        public Criteria andPeijlbDmNotBetween(String value1, String value2) {
            addCriterion("peijlb_dm not between", value1, value2, "peijlbDm");
            return (Criteria) this;
        }

        public Criteria andPeijlbTopIsNull() {
            addCriterion("peijlb_top is null");
            return (Criteria) this;
        }

        public Criteria andPeijlbTopIsNotNull() {
            addCriterion("peijlb_top is not null");
            return (Criteria) this;
        }

        public Criteria andPeijlbTopEqualTo(String value) {
            addCriterion("peijlb_top =", value, "peijlbTop");
            return (Criteria) this;
        }

        public Criteria andPeijlbTopNotEqualTo(String value) {
            addCriterion("peijlb_top <>", value, "peijlbTop");
            return (Criteria) this;
        }

        public Criteria andPeijlbTopGreaterThan(String value) {
            addCriterion("peijlb_top >", value, "peijlbTop");
            return (Criteria) this;
        }

        public Criteria andPeijlbTopGreaterThanOrEqualTo(String value) {
            addCriterion("peijlb_top >=", value, "peijlbTop");
            return (Criteria) this;
        }

        public Criteria andPeijlbTopLessThan(String value) {
            addCriterion("peijlb_top <", value, "peijlbTop");
            return (Criteria) this;
        }

        public Criteria andPeijlbTopLessThanOrEqualTo(String value) {
            addCriterion("peijlb_top <=", value, "peijlbTop");
            return (Criteria) this;
        }

        public Criteria andPeijlbTopLike(String value) {
            addCriterion("peijlb_top like", value, "peijlbTop");
            return (Criteria) this;
        }

        public Criteria andPeijlbTopNotLike(String value) {
            addCriterion("peijlb_top not like", value, "peijlbTop");
            return (Criteria) this;
        }

        public Criteria andPeijlbTopIn(List<String> values) {
            addCriterion("peijlb_top in", values, "peijlbTop");
            return (Criteria) this;
        }

        public Criteria andPeijlbTopNotIn(List<String> values) {
            addCriterion("peijlb_top not in", values, "peijlbTop");
            return (Criteria) this;
        }

        public Criteria andPeijlbTopBetween(String value1, String value2) {
            addCriterion("peijlb_top between", value1, value2, "peijlbTop");
            return (Criteria) this;
        }

        public Criteria andPeijlbTopNotBetween(String value1, String value2) {
            addCriterion("peijlb_top not between", value1, value2, "peijlbTop");
            return (Criteria) this;
        }

        public Criteria andPeijlbMcIsNull() {
            addCriterion("peijlb_mc is null");
            return (Criteria) this;
        }

        public Criteria andPeijlbMcIsNotNull() {
            addCriterion("peijlb_mc is not null");
            return (Criteria) this;
        }

        public Criteria andPeijlbMcEqualTo(String value) {
            addCriterion("peijlb_mc =", value, "peijlbMc");
            return (Criteria) this;
        }

        public Criteria andPeijlbMcNotEqualTo(String value) {
            addCriterion("peijlb_mc <>", value, "peijlbMc");
            return (Criteria) this;
        }

        public Criteria andPeijlbMcGreaterThan(String value) {
            addCriterion("peijlb_mc >", value, "peijlbMc");
            return (Criteria) this;
        }

        public Criteria andPeijlbMcGreaterThanOrEqualTo(String value) {
            addCriterion("peijlb_mc >=", value, "peijlbMc");
            return (Criteria) this;
        }

        public Criteria andPeijlbMcLessThan(String value) {
            addCriterion("peijlb_mc <", value, "peijlbMc");
            return (Criteria) this;
        }

        public Criteria andPeijlbMcLessThanOrEqualTo(String value) {
            addCriterion("peijlb_mc <=", value, "peijlbMc");
            return (Criteria) this;
        }

        public Criteria andPeijlbMcLike(String value) {
            addCriterion("peijlb_mc like", value, "peijlbMc");
            return (Criteria) this;
        }

        public Criteria andPeijlbMcNotLike(String value) {
            addCriterion("peijlb_mc not like", value, "peijlbMc");
            return (Criteria) this;
        }

        public Criteria andPeijlbMcIn(List<String> values) {
            addCriterion("peijlb_mc in", values, "peijlbMc");
            return (Criteria) this;
        }

        public Criteria andPeijlbMcNotIn(List<String> values) {
            addCriterion("peijlb_mc not in", values, "peijlbMc");
            return (Criteria) this;
        }

        public Criteria andPeijlbMcBetween(String value1, String value2) {
            addCriterion("peijlb_mc between", value1, value2, "peijlbMc");
            return (Criteria) this;
        }

        public Criteria andPeijlbMcNotBetween(String value1, String value2) {
            addCriterion("peijlb_mc not between", value1, value2, "peijlbMc");
            return (Criteria) this;
        }

        public Criteria andPeijlbQzIsNull() {
            addCriterion("peijlb_qz is null");
            return (Criteria) this;
        }

        public Criteria andPeijlbQzIsNotNull() {
            addCriterion("peijlb_qz is not null");
            return (Criteria) this;
        }

        public Criteria andPeijlbQzEqualTo(String value) {
            addCriterion("peijlb_qz =", value, "peijlbQz");
            return (Criteria) this;
        }

        public Criteria andPeijlbQzNotEqualTo(String value) {
            addCriterion("peijlb_qz <>", value, "peijlbQz");
            return (Criteria) this;
        }

        public Criteria andPeijlbQzGreaterThan(String value) {
            addCriterion("peijlb_qz >", value, "peijlbQz");
            return (Criteria) this;
        }

        public Criteria andPeijlbQzGreaterThanOrEqualTo(String value) {
            addCriterion("peijlb_qz >=", value, "peijlbQz");
            return (Criteria) this;
        }

        public Criteria andPeijlbQzLessThan(String value) {
            addCriterion("peijlb_qz <", value, "peijlbQz");
            return (Criteria) this;
        }

        public Criteria andPeijlbQzLessThanOrEqualTo(String value) {
            addCriterion("peijlb_qz <=", value, "peijlbQz");
            return (Criteria) this;
        }

        public Criteria andPeijlbQzLike(String value) {
            addCriterion("peijlb_qz like", value, "peijlbQz");
            return (Criteria) this;
        }

        public Criteria andPeijlbQzNotLike(String value) {
            addCriterion("peijlb_qz not like", value, "peijlbQz");
            return (Criteria) this;
        }

        public Criteria andPeijlbQzIn(List<String> values) {
            addCriterion("peijlb_qz in", values, "peijlbQz");
            return (Criteria) this;
        }

        public Criteria andPeijlbQzNotIn(List<String> values) {
            addCriterion("peijlb_qz not in", values, "peijlbQz");
            return (Criteria) this;
        }

        public Criteria andPeijlbQzBetween(String value1, String value2) {
            addCriterion("peijlb_qz between", value1, value2, "peijlbQz");
            return (Criteria) this;
        }

        public Criteria andPeijlbQzNotBetween(String value1, String value2) {
            addCriterion("peijlb_qz not between", value1, value2, "peijlbQz");
            return (Criteria) this;
        }

        public Criteria andPeijlbLenIsNull() {
            addCriterion("peijlb_len is null");
            return (Criteria) this;
        }

        public Criteria andPeijlbLenIsNotNull() {
            addCriterion("peijlb_len is not null");
            return (Criteria) this;
        }

        public Criteria andPeijlbLenEqualTo(Integer value) {
            addCriterion("peijlb_len =", value, "peijlbLen");
            return (Criteria) this;
        }

        public Criteria andPeijlbLenNotEqualTo(Integer value) {
            addCriterion("peijlb_len <>", value, "peijlbLen");
            return (Criteria) this;
        }

        public Criteria andPeijlbLenGreaterThan(Integer value) {
            addCriterion("peijlb_len >", value, "peijlbLen");
            return (Criteria) this;
        }

        public Criteria andPeijlbLenGreaterThanOrEqualTo(Integer value) {
            addCriterion("peijlb_len >=", value, "peijlbLen");
            return (Criteria) this;
        }

        public Criteria andPeijlbLenLessThan(Integer value) {
            addCriterion("peijlb_len <", value, "peijlbLen");
            return (Criteria) this;
        }

        public Criteria andPeijlbLenLessThanOrEqualTo(Integer value) {
            addCriterion("peijlb_len <=", value, "peijlbLen");
            return (Criteria) this;
        }

        public Criteria andPeijlbLenIn(List<Integer> values) {
            addCriterion("peijlb_len in", values, "peijlbLen");
            return (Criteria) this;
        }

        public Criteria andPeijlbLenNotIn(List<Integer> values) {
            addCriterion("peijlb_len not in", values, "peijlbLen");
            return (Criteria) this;
        }

        public Criteria andPeijlbLenBetween(Integer value1, Integer value2) {
            addCriterion("peijlb_len between", value1, value2, "peijlbLen");
            return (Criteria) this;
        }

        public Criteria andPeijlbLenNotBetween(Integer value1, Integer value2) {
            addCriterion("peijlb_len not between", value1, value2, "peijlbLen");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sm_peijlb
     *
     * @mbggenerated do_not_delete_during_merge Wed Apr 09 06:29:40 CST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sm_peijlb
     *
     * @mbggenerated Wed Apr 09 06:29:40 CST 2014
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}