package com.xym.bossed.db.mybatis.jiesuan;

import com.xym.bossed.db.mybatis.jiesuan.JieSuan;
import com.xym.bossed.db.mybatis.jiesuan.JieSuanExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JieSuanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_jiesuan
     *
     * @mbggenerated Tue Apr 08 11:36:11 CST 2014
     */
    int countByExample(JieSuanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_jiesuan
     *
     * @mbggenerated Tue Apr 08 11:36:11 CST 2014
     */
    int deleteByExample(JieSuanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_jiesuan
     *
     * @mbggenerated Tue Apr 08 11:36:11 CST 2014
     */
    int deleteByPrimaryKey(String jiesuanMc);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_jiesuan
     *
     * @mbggenerated Tue Apr 08 11:36:11 CST 2014
     */
    int insert(JieSuan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_jiesuan
     *
     * @mbggenerated Tue Apr 08 11:36:11 CST 2014
     */
    int insertSelective(JieSuan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_jiesuan
     *
     * @mbggenerated Tue Apr 08 11:36:11 CST 2014
     */
    List<JieSuan> selectByExample(JieSuanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_jiesuan
     *
     * @mbggenerated Tue Apr 08 11:36:11 CST 2014
     */
    JieSuan selectByPrimaryKey(String jiesuanMc);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_jiesuan
     *
     * @mbggenerated Tue Apr 08 11:36:11 CST 2014
     */
    int updateByExampleSelective(@Param("record") JieSuan record, @Param("example") JieSuanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_jiesuan
     *
     * @mbggenerated Tue Apr 08 11:36:11 CST 2014
     */
    int updateByExample(@Param("record") JieSuan record, @Param("example") JieSuanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_jiesuan
     *
     * @mbggenerated Tue Apr 08 11:36:11 CST 2014
     */
    int updateByPrimaryKeySelective(JieSuan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sm_jiesuan
     *
     * @mbggenerated Tue Apr 08 11:36:11 CST 2014
     */
    int updateByPrimaryKey(JieSuan record);
}